// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 xinpian-tech
package me.jiuyang.utlib

/** The emitted DPI-export wrapper: an SV module and a C lifecycle shim generated from the DPI contract. The SV
  * instantiates the lib model and exposes an `export "DPI-C"` `poke_<input>` for each drive/clock/reset port and a
  * `peek_probe_<name>` for each probe point. The C shim exposes `sim_new` / `sim_eval` / `sim_delete`. Built together
  * with the lib model (`verilator --cc --lib-create --build`) they become a `.so` an external driver (e.g. Python via
  * ctypes) loads and calls: poke the inputs, step with `sim_eval`, peek the probes.
  *
  * CIRCT's ExportVerilog can emit `import "DPI-C"` but not `export "DPI-C"`, so this wrapper is code-generated from the
  * contract rather than lowered through the dialect — but it is derived, not hand-authored: every function corresponds
  * to a contract port.
  */
final case class DpiWrapper(top: String, sources: Seq[os.Path])

private[utlib] object DpiWrapper:
  /** The wrapper's top module name (and the scope the C shim binds). */
  def top(spec: DPISpec): String = s"${spec.dut}_dpi"

  /** A port wider than 64 bits crosses as a packed vector (`svBitVecVal*`) rather than a scalar. */
  private def isWide(width: Int): Boolean = width > 64

  /** The SV DPI type for a `width`-bit port: a scalar up to 64 bits, else a packed bit vector. */
  private def dpiType(width: Int): String =
    if width <= 8 then "byte"
    else if width <= 16 then "shortint"
    else if width <= 32 then "int"
    else if width <= 64 then "longint"
    else s"bit [${width - 1}:0]"

  /** The matching C scalar type for a `<= 64`-bit [[dpiType]] (svByte/svShortInt/svInt/svLongInt). */
  private def cType(width: Int): String =
    if width <= 8 then "char" else if width <= 16 then "short" else if width <= 32 then "int" else "long long"

  /** The lib model's port name for a contract input: drive ports are prefixed, clock/reset keep their name. */
  private def libInput(port: DPIPort): String =
    if port.role == DPIRole.Drive then s"drive_${port.name}" else port.name

  private def libProbe(port: DPIPort): String = s"probe_${port.name}"

  /** The SV wrapper: instantiate `libTop` and export a poke per input, a peek per probe. */
  def svString(libTop: String, spec: DPISpec): String =
    val inputs     = spec.clock.toSeq ++ spec.reset.toSeq ++ spec.drive
    val inputDecls = inputs.map(p => s"  logic [${p.width - 1}:0] ${libInput(p)};").mkString("\n")
    val probeDecls = spec.probe.map(p => s"  wire  [${p.width - 1}:0] ${libProbe(p)};").mkString("\n")
    val conns      =
      (inputs.map(p => s".${libInput(p)}(${libInput(p)})") ++
        spec.probe.map(p => s".${libProbe(p)}(${libProbe(p)})")).mkString(",\n    ")
    val pokes      = inputs.map { p =>
      s"""|  export "DPI-C" function poke_${libInput(p)};
          |  function void poke_${libInput(p)}(input ${dpiType(p.width)} v);
          |    ${libInput(p)} = v;
          |  endfunction""".stripMargin
    }
      .mkString("\n")
    val peeks      = spec.probe.map { p =>
      // A scalar (<= 64 bit) probe returns by value; a wide one is passed out through an arg
      // (SV cannot return a packed vector by value).
      if isWide(p.width) then s"""|  export "DPI-C" function peek_${libProbe(p)};
                                  |  function void peek_${libProbe(p)}(output ${dpiType(p.width)} v);
                                  |    v = ${libProbe(p)};
                                  |  endfunction""".stripMargin
      else s"""|  export "DPI-C" function peek_${libProbe(p)};
               |  function ${dpiType(p.width)} peek_${libProbe(p)}();
               |    return ${libProbe(p)};
               |  endfunction""".stripMargin
    }
      .mkString("\n")
    s"""|// Generated by me.jiuyang.utlib.DpiWrapper — export "DPI-C" bindings for the DPI contract.
        |module ${top(spec)};
        |$inputDecls
        |$probeDecls
        |  $libTop lib(
        |    $conns
        |  );
        |$pokes
        |$peeks
        |endmodule
        |""".stripMargin

  /** The C lifecycle + data shim exposing the stable ABI (see `doc/dpi-abi.md`).
    *
    * `sim_new`/`sim_eval`/`sim_delete` manage the model; every data symbol is handle-first — `dpi_poke_<input>(h, v)`
    * and `dpi_peek_probe_<name>(h)` take the model handle, bind the DPI scope from it, and call the scope-bound
    * `export "DPI-C"` function. Handle-first keeps the ABI multi-instance-shaped; the actual concurrency a backend
    * allows is its own concern (Verilator shares one scope per top name, so it is single-instance in practice).
    */
  def capiString(spec: DPISpec): String =
    val t      = top(spec)
    val inputs = spec.clock.toSeq ++ spec.reset.toSeq ++ spec.drive
    // Wide ports (> 64 bit) cross as `svBitVecVal*` (packed uint32 chunks); scalars pass by value.
    val pokes  = inputs.map { p =>
      val n = libInput(p)
      if isWide(p.width) then
        s"  void dpi_poke_$n(void* h, const svBitVecVal* v) { svSetScope(((Sim*)h)->scope); poke_$n(v); }"
      else s"  void dpi_poke_$n(void* h, ${cType(p.width)} v) { svSetScope(((Sim*)h)->scope); poke_$n(v); }"
    }
      .mkString("\n")
    val peeks  = spec.probe.map { p =>
      val n = libProbe(p)
      if isWide(p.width) then
        s"  void dpi_peek_$n(void* h, svBitVecVal* out) { svSetScope(((Sim*)h)->scope); peek_$n(out); }"
      else s"  ${cType(p.width)} dpi_peek_$n(void* h) { svSetScope(((Sim*)h)->scope); return peek_$n(); }"
    }
      .mkString("\n")
    s"""|// Generated by me.jiuyang.utlib.DpiWrapper — C ABI shim for the Verilated model.
        |#include "V$t.h"
        |#include "V${t}__Dpi.h"
        |#include "svdpi.h"
        |#include "verilated.h"
        |struct Sim { V$t* model; svScope scope; };
        |extern "C" {
        |  void* sim_new() {
        |    Sim* s = new Sim();
        |    s->model = new V$t();
        |    s->scope = svGetScopeFromName("TOP.$t");
        |    return s;
        |  }
        |  void sim_eval(void* h) { ((Sim*)h)->model->eval(); }
        |  void sim_delete(void* h) { Sim* s = (Sim*)h; delete s->model; delete s; }
        |$pokes
        |$peeks
        |}
        |""".stripMargin
