// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 xinpian-tech
package me.jiuyang.utlib

/** The emitted DPI-export wrapper: an SV module and a C lifecycle shim generated from the DPI contract. The SV
  * instantiates the lib model and exposes an `export "DPI-C"` `poke_<input>` for each drive/clock/reset port and a
  * `peek_probe_<name>` for each probe point. The C shim exposes `sim_new` / `sim_eval` / `sim_delete`. Built together
  * with the lib model (`verilator --cc --lib-create --build`) they become a `.so` an external driver (e.g. Python via
  * ctypes) loads and calls: poke the inputs, step with `sim_eval`, peek the probes.
  *
  * CIRCT's ExportVerilog can emit `import "DPI-C"` but not `export "DPI-C"`, so this wrapper is code-generated from the
  * contract rather than lowered through the dialect — but it is derived, not hand-authored: every function corresponds
  * to a contract port.
  */
final case class DpiWrapper(top: String, sources: Seq[os.Path])

private[utlib] object DpiWrapper:
  /** The wrapper's top module name (and the scope the C shim binds). */
  def top(spec: DPISpec): String = s"${spec.dut}_dpi"

  /** The DPI-C scalar type wide enough to carry a `width`-bit port across the boundary. */
  private def dpiType(width: Int): String =
    require(width <= 64, s"DPI wrapper supports ports up to 64 bits; got $width (use packed vectors / open arrays)")
    if width <= 8 then "byte" else if width <= 16 then "shortint" else if width <= 32 then "int" else "longint"

  /** The lib model's port name for a contract input: drive ports are prefixed, clock/reset keep their name. */
  private def libInput(port: DPIPort): String =
    if port.role == DPIRole.Drive then s"drive_${port.name}" else port.name

  private def libProbe(port: DPIPort): String = s"probe_${port.name}"

  /** The SV wrapper: instantiate `libTop` and export a poke per input, a peek per probe. */
  def svString(libTop: String, spec: DPISpec): String =
    val inputs     = spec.clock.toSeq ++ spec.reset.toSeq ++ spec.drive
    val inputDecls = inputs.map(p => s"  logic [${p.width - 1}:0] ${libInput(p)};").mkString("\n")
    val probeDecls = spec.probe.map(p => s"  wire  [${p.width - 1}:0] ${libProbe(p)};").mkString("\n")
    val conns      =
      (inputs.map(p => s".${libInput(p)}(${libInput(p)})") ++
        spec.probe.map(p => s".${libProbe(p)}(${libProbe(p)})")).mkString(",\n    ")
    val pokes      = inputs.map { p =>
      s"""|  export "DPI-C" function poke_${libInput(p)};
          |  function void poke_${libInput(p)}(input ${dpiType(p.width)} v);
          |    ${libInput(p)} = v;
          |  endfunction""".stripMargin
    }
      .mkString("\n")
    val peeks      = spec.probe.map { p =>
      s"""|  export "DPI-C" function peek_${libProbe(p)};
          |  function ${dpiType(p.width)} peek_${libProbe(p)}();
          |    return ${libProbe(p)};
          |  endfunction""".stripMargin
    }
      .mkString("\n")
    s"""|// Generated by me.jiuyang.utlib.DpiWrapper — export "DPI-C" bindings for the DPI contract.
        |module ${top(spec)};
        |$inputDecls
        |$probeDecls
        |  $libTop lib(
        |    $conns
        |  );
        |$pokes
        |$peeks
        |endmodule
        |""".stripMargin

  /** The C lifecycle shim: construct/evaluate/destroy the Verilated model and bind the DPI scope. */
  def capiString(spec: DPISpec): String =
    val t = top(spec)
    s"""|// Generated by me.jiuyang.utlib.DpiWrapper — C lifecycle shim for the Verilated model.
        |#include "V$t.h"
        |#include "svdpi.h"
        |#include "verilated.h"
        |extern "C" {
        |  void* sim_new() {
        |    V$t* m = new V$t;
        |    svSetScope(svGetScopeFromName("TOP.$t"));
        |    return m;
        |  }
        |  void sim_eval(void* m) { ((V$t*)m)->eval(); }
        |  void sim_delete(void* m) { delete (V$t*)m; }
        |}
        |""".stripMargin
