// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 xinpian-tech
package me.jiuyang.utlib

/** The single hand-written primitive of the UT flow: a minimal SystemVerilog top that
  * generates the clock and reset and instantiates the elaborated harness.
  *
  * Everything else — stimulus, done/timeout detection, printing, and `$finish` — is generated
  * from the Zaozi DSL through the `sim` dialect (see [[DefaultUTHarnessGenerator]] and
  * [[SimControl]]). Only the clock oscillator (`always #5`) is irreducible: CIRCT models a
  * clock as an external input and has no MLIR construct that emits a `#`-delay, so a testbench
  * must supply the clock from outside. Reset is a plain `initial`/`@(posedge)` sequence here
  * for the same reason a synchronous design cannot bootstrap its own reset.
  */
object Driver:
  val topModuleName: String = "ut_top"

  def topString(harnessModule: String, trace: Boolean, traceFile: String): String =
    val dump =
      if !trace then ""
      else s"""|
               |  initial begin
               |    $$dumpfile("$traceFile");
               |    $$dumpvars(0, $topModuleName);
               |  end
               |""".stripMargin
    s"""|// Generated by me.jiuyang.utlib.Driver — the only hand-written testbench primitive.
        |// It generates clock and reset; the harness generates everything else.
        |module $topModuleName;
        |  reg  clock = 1'b0;
        |  reg  reset = 1'b1;
        |  wire done;
        |
        |  always #5 clock = ~clock;
        |
        |  initial begin
        |    repeat (4) @(posedge clock);
        |    reset = 1'b0;
        |  end
        |$dump
        |  $harnessModule harness (
        |    .clock (clock),
        |    .reset (reset),
        |    .done  (done)
        |  );
        |endmodule
        |""".stripMargin
