// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 xinpian-tech
package me.jiuyang.utlib

/** Emit C++ frontends that drive a lib-harness Verilated model.
  *
  * The frontend owns the loop: each cycle it pokes the drive ports, advances the model, and peeks the probe ports. The
  * Verilated model built from [[LibHarnessGenerator]] is the single harness — the "library" — and a frontend is just
  * one caller of it. Replaying the solver's stimulus is therefore only one frontend among many: pass a different
  * per-cycle sequence for a different one (a fixed vector, values read from JSON, a Rust/Python driver over FFI, …).
  */
object Frontend:
  /** The Verilated model class name Verilator generates for a top module. */
  def modelClass(topModule: String): String = s"V$topModule"

  /** The signed C integer type wide enough to reinterpret a `width`-bit port for printing. */
  private def signedType(width: Int): String =
    if width <= 8 then "int8_t" else if width <= 16 then "int16_t" else if width <= 32 then "int32_t" else "int64_t"

  private def mask(value: BigInt, width: Int): BigInt = value & ((BigInt(1) << width) - 1)

  /** A driver frontend fed a fixed per-cycle stimulus.
    *
    * `sequence(c)(portName)` is the value poked on drive port `portName` at cycle `c`; a missing port defaults to 0.
    * Each printed line is `"<label> cyc=<n> <probe>=<signed> …"`.
    */
  def driver(
    spec:      DPISpec,
    topModule: String,
    sequence:  Seq[Map[String, BigInt]],
    label:     String
  ): String =
    val cls     = modelClass(topModule)
    val clocked = spec.clock.isDefined
    val advance =
      if clocked then
        val c = spec.clock.get.name
        s"top->$c = 0; top->eval(); top->$c = 1; top->eval();"
      else "top->eval();"

    val resetPhase = spec.reset match
      case Some(r) if clocked =>
        s"""|  top->${r.name} = 1;
            |  for (int i = 0; i < 4; i++) step();
            |  top->${r.name} = 0;
            |""".stripMargin
      case _                  => "" // combinational / reset-less DUT: nothing to bootstrap

    val seqDecls = spec.drive.map { d =>
      val vals = sequence.map(cycle => mask(cycle.getOrElse(d.name, BigInt(0)), d.width)).mkString(", ")
      s"  static const uint64_t seq_${d.name}[] = { $vals };"
    }
      .mkString("\n")
    val pokes    = spec.drive.map(d => s"top->${d.name} = (uint64_t)seq_${d.name}[c];").mkString("\n    ")
    val peeks    = spec.probe
      .map(p => s"""printf(" ${p.name}=%d", (int)(${signedType(p.width)})top->${LibHarness.probePort(p.name)});""")
      .mkString("\n    ")

    s"""|// Generated by me.jiuyang.utlib.Frontend — one caller of the lib-harness model.
        |#include "$cls.h"
        |#include "verilated.h"
        |#include <cstdio>
        |#include <cstdint>
        |static $cls* top;
        |static void step() { $advance }
        |int main(int argc, char** argv) {
        |  Verilated::commandArgs(argc, argv);
        |  top = new $cls;
        |$resetPhase$seqDecls
        |  const int CYC = ${sequence.size};
        |  for (int c = 0; c < CYC; c++) {
        |    $pokes
        |    step();
        |    printf("$label cyc=%d", c + 1);
        |    $peeks
        |    printf("\\n");
        |  }
        |  top->final();
        |  delete top;
        |  return 0;
        |}
        |""".stripMargin
