// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 xinpian-tech
package me.jiuyang.utlib

/** Model B: the SV owns the loop. The harness ([[DpiHarnessGenerator]]) is generated through the sim dialect — each
  * cycle it reads the DUT's probes and calls `import "DPI-C" <dut>_tick`, driving the DUT with the value the callback
  * returns; a tiny clock oscillator ([[Driver]]) is the only hand-written SystemVerilog. This object generates the
  * *callback* — the C ABI derived from the contract (`abi.json`) — that implements `<dut>_tick`: it observes the probes
  * and supplies the per-cycle drive from `stimulus.txt` (one value per line).
  *
  * Single drive port for now: the FIRRTL DPI call yields one result, so a multi-drive DUT needs the multi-output shape
  * (left for later).
  */
final case class Testbench(top: String, sources: Seq[os.Path])

private[utlib] object Testbench:
  private def cType(width: Int): String =
    if width <= 8 then "char" else if width <= 16 then "short" else if width <= 32 then "int" else "long long"

  /** The `<dut>_tick(probes…, drive*)` callback: probes by value, the single drive as an output. */
  def tickCapi(spec: AbiSpec): String =
    require(spec.drive.size == 1, s"${spec.dut}: Model B supports exactly one drive port")
    val drive     = spec.drive.head
    val probeArgs = spec.probe.map(p => s"${cType(p.width)} probe_${p.name}")
    val args      = (probeArgs :+ s"${cType(drive.width)}* drive_${drive.name}").mkString(", ")
    val fmt       = spec.probe.map(p => s" ${p.name}=%d").mkString
    val vals      = spec.probe.map(p => s", (int)probe_${p.name}").mkString
    s"""|// Generated by me.jiuyang.utlib.Testbench — the <dut>_tick callback (import "DPI-C").
        |#include <stdio.h>
        |extern "C" {
        |static int cyc = 0;
        |static long stim[4096];
        |static int nstim = -1;
        |void ${spec.dut}_tick($args) {
        |  if (nstim < 0) {
        |    nstim = 0;
        |    FILE* f = fopen("stimulus.txt", "r");
        |    if (f) { while (nstim < 4096 && fscanf(f, "%ld", &stim[nstim]) == 1) nstim++; fclose(f); }
        |  }
        |  long drv = (cyc < nstim) ? stim[cyc] : 0;
        |  printf("TB cyc=%d$fmt drive=%ld\\n", cyc + 1$vals, drv);
        |  *drive_${drive.name} = (${cType(drive.width)})drv;
        |  cyc++;
        |}
        |}
        |""".stripMargin
