// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.utlib

/** A [[StimulusCodec]] that emits a UVM sequence of concrete transactions.
  *
  * A template-generated UVM testbench is fixed apart from its sequences: for one protocol the agent, driver, monitor
  * and scoreboard are byte-identical across designs, and only the interface, the transaction fields and the sequences
  * vary. So a solved witness can be dropped into someone else's testbench by replacing the sequence layer alone —
  * which is what this codec does, and why the two arms of the experiment can be measured inside *the same*
  * infrastructure rather than two testbenches that differ in a hundred ways.
  *
  * Two fills, because an intent is a *constraint* and a witness is only one of its solutions:
  *   - `pinned = None` replays the witness exactly — one concrete transaction per beat.
  *   - `pinned = Some(fields)` pins just the fields the intent constrained and randomizes the rest, so one solved
  *     witness expands into `repeatPerBeat` transactions that all still satisfy it. This is how directed generation
  *     reaches volume without paying a solver call per transaction: the solver supplies the structure, the simulator
  *     fills the free data.
  */
final case class UvmSequence(
  sequenceName:  String,
  itemType:      String,
  pinned:        Option[Set[String]] = None,
  repeatPerBeat: Int = 1,
  strobe:        Option[String] = None,
  periodNs:      Int = 10)
    extends StimulusCodec:

  /** With `strobe` set, the witness is read the way a handshaking driver would produce it: a run of beats with the
    * strobe low is a wait of that many clock periods, and a run of identical beats with the strobe high — a request
    * held until its acknowledge — is one transaction. Without it every beat is a transaction.
    */
  private def transactions(stimulus: AbstractStimulus): Vector[Either[Int, Beat]] = strobe match
    case None    => stimulus.beats.map(Right(_))
    case Some(p) =>
      val out = Vector.newBuilder[Either[Int, Beat]]
      var i   = 0
      while i < stimulus.beats.length do
        val b = stimulus.beats(i)
        if b.values.getOrElse(p, BigInt(0)) == BigInt(0) then
          var n = 0
          while i < stimulus.beats.length && stimulus.beats(i).values.getOrElse(p, BigInt(0)) == BigInt(0) do
            n += 1; i += 1
          out += Left(n)
        else
          // Identical in what will be rendered: the pinned fields, or every drive port. A free port the engine
          // happened to vary from cycle to cycle does not make a held request several transactions.
          val keys = pinned.getOrElse(stimulus.spec.drive.map(_.name).toSet)
          def view(x: Beat) = x.values.filter((k, _) => keys.contains(k))
          while i < stimulus.beats.length && view(stimulus.beats(i)) == view(b)
            && stimulus.beats(i).values.getOrElse(p, BigInt(0)) != BigInt(0)
          do i += 1
          out += Right(b)
      out.result()

  def render(stimulus: AbstractStimulus): String =
    val beats = transactions(stimulus).zipWithIndex.map {
      case (Left(idle), i) => s"      // beat $i — ${idle} idle cycles\n      #(${idle * periodNs});"
      case (Right(beat), i) =>
        def value(p: AbiPort) = s"${p.width}'h${beat.values(p.name).toString(16)}"
        pinned match
          // Every field concrete: the witness replayed exactly.
          case None       =>
            val assignments = stimulus.spec.drive.map(p => s"      txn.${p.name} = ${value(p)};").mkString("\n")
            s"""|      // beat $i
                |      txn = $itemType::type_id::create("txn");
                |      start_item(txn);
                |$assignments
                |      finish_item(txn);""".stripMargin
          // Only the fields the intent actually constrained are pinned; the rest randomize, so one solved
          // witness expands into `repeatPerBeat` transactions that all still satisfy the intent.
          case Some(keys) =>
            val constraints = stimulus.spec.drive
              .filter(p => keys.contains(p.name))
              .map(p => s"${p.name} == ${value(p)};")
              .mkString(" ")
            s"""|      // beat $i — pinned { $constraints } with the remaining fields randomized
                |      repeat ($repeatPerBeat) begin
                |        txn = $itemType::type_id::create("txn");
                |        start_item(txn);
                |        assert(txn.randomize() with { $constraints });
                |        finish_item(txn);
                |      end""".stripMargin
    }.mkString("\n\n")

    s"""|// Generated by me.jiuyang.utlib.UvmSequence — concrete transactions from a solved witness.
        |// Each beat is the solver's assignment to the DUT's drive ports; nothing here is randomized.
        |class $sequenceName extends uvm_sequence #($itemType);
        |  `uvm_object_utils($sequenceName)
        |
        |  function new(string name = "$sequenceName");
        |    super.new(name);
        |  endfunction
        |
        |  task body();
        |    $itemType txn;
        |
        |$beats
        |  endtask
        |endclass
        |""".stripMargin

  def write(stimulus: AbstractStimulus, path: os.Path): os.Path =
    os.makeDir.all(path / os.up)
    os.write.over(path, render(stimulus))
    path

object UvmSequence:

  /** Concatenate several solved witnesses into one stimulus stream over a shared ABI — the way a set of directed
    * intents becomes a single sequence the testbench can run in one simulation.
    *
    * The witnesses need not come from the same module: directed generation typically solves one intent per
    * *parameterization* of a UT, so the DUT names differ by construction. What must agree is the drive-port
    * signature, since that is what a beat assigns and what the transaction's fields are named after.
    */
  def concat(spec: AbiSpec, stimuli: Seq[AbstractStimulus]): AbstractStimulus =
    def signature(s: AbiSpec) = s.drive.map(p => (p.name, p.width, p.signed))
    val want                  = signature(spec)
    for s <- stimuli do
      require(
        signature(s.spec) == want,
        s"witness from ${s.spec.dut} drives ${signature(s.spec)}, but the stream's ABI drives $want"
      )
    AbstractStimulus(spec, stimuli.flatMap(_.beats).toVector)
