// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.rvprobe.scripts

import me.jiuyang.rvprobe.*
import org.chipsalliance.rvdecoderdb.{Encoding, Instruction, InstructionSet}
import os.Path
import java.io.{File, FileWriter}

// Register argument names (raw names from rvdecoderdb ArgLUT) that should use Register enum type
val registerArgNames: Set[String] = Set(
  "rd",
  "rs1",
  "rs2",
  "rs3",
  "rt",
  "vd",
  "vs1",
  "vs2",
  "vs3",
  "rd_p",
  "rs1_p",
  "rs2_p",
  "rd_rs1",
  "rd_rs1_p",
  "rd_rs1_n0",
  "rd_n0",
  "rd_n2",
  "rs1_n0",
  "c_rs1_n0",
  "c_rs2_n0",
  "c_rs2",
  "c_sreg1",
  "c_sreg2"
)

// Run with: mill rvprobe.runMain me.jiuyang.rvprobe.scripts.UpdateAsmApi rvprobe/src/AsmApi.scala
// make sure git repo is clear before running this script

// Instructions that should NOT generate label-based overloads
// (because rvdecoderdb defines them as pseudo-instructions with wrong args)
val skipLabelOverload: Set[String] = Set("jalr", "jr", "c.jalr", "c.jr")

@main def UpdateAsmApi(outputPath: String): Unit =
  val writer = new FileWriter(new File(outputPath))

  writer.write(
    """// SPDX-License-Identifier: Apache-2.0
      |// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
      |package me.jiuyang.rvprobe
      |
      |import me.jiuyang.rvprobe.Register
      |import me.jiuyang.rvprobe.constraints.*
      |
      |import me.jiuyang.smtlib.default.{*, given}
      |import me.jiuyang.smtlib.tpe.*
      |
      |import org.llvm.mlir.scalalib.capi.ir.{Block, Context, given}
      |
      |import java.lang.foreign.Arena
      |
      |// format: off
      |// ================= AUTO GENERATED BY UpdateAsmApi.scala =======================
      |//
      |//  Assembly-like API for writing fixed-value constraints.
      |//
      |//  The instruction index is auto-incremented via Recipe.nextIdx().
      |//  Parameters follow the rvdecoderdb argument order for each instruction.
      |//  Zero-arg instructions (ecall, mret, etc.) are also generated.
      |// =============================================================================
      |
""".stripMargin
  )

  // For each instruction, generate an assembly-like convenience function:
  //   def instrName(arg1: Int, arg2: Int, ...)(using Arena, Context, Block, Recipe): Unit =
  //     instruction(summon[Recipe].nextIdx(), isInstrName()) { arg1Equal(v1) & arg2Equal(v2) & ... }
  //   For zero-arg instructions (ecall, mret, etc.):
  //   def ecall()(using Arena, Context, Block, Recipe): Unit =
  //     instruction(summon[Recipe].nextIdx(), isEcall()) { ArgConstraint(true.B) }
  getInstructions().foreach { instruction =>
    val name = translateToCamelCase(instruction.name)

    val funcName = name.head.toLower + name.tail
    val isFunc   = s"is${name}"

    val argNames = instruction.args.map(_.name).toSet
    val hasBimm  = argNames.contains("bimm12hi") && argNames.contains("bimm12lo")
    val hasJimm  = argNames.contains("jimm20")

    if (instruction.args.nonEmpty) {
      // Build parameter list and constraint body from instruction args
      val params = instruction.args.map { arg =>
        val argName        = translateToCamelCase(arg.name)
        val argNameLowered = argName.head.toLower + argName.tail
        val tpe            = if registerArgNames.contains(arg.name) then "Register" else "Int"
        s"$argNameLowered: $tpe"
      }.mkString(", ")

      val constraints = instruction.args.map { arg =>
        val argName        = translateToCamelCase(arg.name)
        val argNameLowered = argName.head.toLower + argName.tail
        val value          = if registerArgNames.contains(arg.name) then s"$argNameLowered.ordinal" else argNameLowered
        s"${argNameLowered}Equal($value)"
      }.mkString(" & ")

      writer.write(
        s"def $funcName($params)(using Arena, Context, Block, Recipe): Unit = instruction(summon[Recipe].nextIdx(), $isFunc()) { $constraints }\n"
      )

      // Generate label-based overload for branch instructions (bimm12hi/bimm12lo)
      if (hasBimm && !skipLabelOverload.contains(instruction.name)) {
        val nonImmArgs = instruction.args.filter(arg => arg.name != "bimm12hi" && arg.name != "bimm12lo")
        val nonImmParams = nonImmArgs.map { arg =>
          val argName        = translateToCamelCase(arg.name)
          val argNameLowered = argName.head.toLower + argName.tail
          val tpe            = if registerArgNames.contains(arg.name) then "Register" else "Int"
          s"$argNameLowered: $tpe"
        }.mkString(", ")
        val labelParams = if (nonImmParams.isEmpty) "target: String" else s"$nonImmParams, target: String"

        val labelConstraints = nonImmArgs.map { arg =>
          val argName        = translateToCamelCase(arg.name)
          val argNameLowered = argName.head.toLower + argName.tail
          val value          = if registerArgNames.contains(arg.name) then s"$argNameLowered.ordinal" else argNameLowered
          s"${argNameLowered}Equal($value)"
        }.mkString(" & ")
        val fullConstraints = if (labelConstraints.isEmpty) "bimm12hiEqual(0) & bimm12loEqual(0)" else s"$labelConstraints & bimm12hiEqual(0) & bimm12loEqual(0)"

        writer.write(
          s"def $funcName($labelParams)(using Arena, Context, Block, Recipe): Unit = {\n"
        )
        writer.write(
          s"  val idx = summon[Recipe].nextIdx()\n"
        )
        writer.write(
          s"  instruction(idx, $isFunc()) { $fullConstraints }\n"
        )
        writer.write(
          s"  labelRef(idx, target)\n"
        )
        writer.write(
          s"}\n"
        )
      }

      // Generate label-based overload for jump instructions (jimm20)
      if (hasJimm) {
        val nonImmArgs = instruction.args.filter(arg => arg.name != "jimm20")
        val nonImmParams = nonImmArgs.map { arg =>
          val argName        = translateToCamelCase(arg.name)
          val argNameLowered = argName.head.toLower + argName.tail
          val tpe            = if registerArgNames.contains(arg.name) then "Register" else "Int"
          s"$argNameLowered: $tpe"
        }.mkString(", ")
        val labelParams = if (nonImmParams.isEmpty) "target: String" else s"$nonImmParams, target: String"

        val labelConstraints = nonImmArgs.map { arg =>
          val argName        = translateToCamelCase(arg.name)
          val argNameLowered = argName.head.toLower + argName.tail
          val value          = if registerArgNames.contains(arg.name) then s"$argNameLowered.ordinal" else argNameLowered
          s"${argNameLowered}Equal($value)"
        }.mkString(" & ")
        val fullConstraints = if (labelConstraints.isEmpty) "jimm20Equal(0)" else s"$labelConstraints & jimm20Equal(0)"

        writer.write(
          s"def $funcName($labelParams)(using Arena, Context, Block, Recipe): Unit = {\n"
        )
        writer.write(
          s"  val idx = summon[Recipe].nextIdx()\n"
        )
        writer.write(
          s"  instruction(idx, $isFunc()) { $fullConstraints }\n"
        )
        writer.write(
          s"  labelRef(idx, target)\n"
        )
        writer.write(
          s"}\n"
        )
      }
    } else {
      // Zero-arg instructions (ecall, ebreak, mret, etc.)
      writer.write(
        s"def $funcName()(using Arena, Context, Block, Recipe): Unit = instruction(summon[Recipe].nextIdx(), $isFunc()) { ArgConstraint.noArgs }\n"
      )
    }
  }

  writer.write("\n// format: on\n")
  writer.close()
