// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.rvprobe.scripts

import me.jiuyang.rvprobe.*
import org.chipsalliance.rvdecoderdb.{Encoding, Instruction, InstructionSet}
import os.Path
import java.io.{File, FileWriter}

// Run with: mill rvprobe.runMain me.jiuyang.rvprobe.scripts.UpdateRVConstraints rvprobe/src/constraints/RVConstraints.scala
// make sure git repo is clear before running this script
@main def UpdateRVConstraints(outputPath: String): Unit =
  val writer = new FileWriter(new File(outputPath))
  val riscvOpcodesPath: Path = Path(
    sys.env.getOrElse(
      "RISCV_OPCODES_INSTALL_PATH",
      throw new RuntimeException("Environment variable RISCV_OPCODES_INSTALL_PATH not set")
    )
  )

  writer.write(
    """// SPDX-License-Identifier: Apache-2.0
      |// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
      |package me.jiuyang.rvprobe.constraints
      |
      |import me.jiuyang.rvprobe.InstructionArgsCache
      |
      |import me.jiuyang.smtlib.default.{*, given}
      |import me.jiuyang.smtlib.tpe.*
      |
      |import org.llvm.mlir.scalalib.capi.ir.{Block, Context, Location, LocationApi, Operation, Type, Value, given}
      |
      |import java.lang.foreign.Arena
      |
      |// format: off
      |// ================= AUTO GENERATED BY GenerateConstraints.scala =======================
""".stripMargin
  )

  // ======================================================================================================
  // def amoopRange(start: Int, end: Int)(using Arena, Context, Block, Index): ArgConstraint = ArgConstraint(summon[Index].amoop >= start.S & summon[Index].amoop < end.S)
  // ======================================================================================================
  getArgLut().foreach { case (name, arg) =>
    // camelCase the argument name
    val argName: String = translateToCamelCase(name)
    val argNameLowered = argName.head.toLower + argName.tail

    writer.write(
      s"def ${argNameLowered}Range(start: Int, end: Int)(using Arena, Context, Block, Index): ArgConstraint = ArgConstraint(summon[Index].${argNameLowered} >= start.S & summon[Index].${argNameLowered} < end.S)\n"
    )
  }

  writer.write("\n")

  // ======================================================================================================
  // def amoopEqual(n: Int)(using Arena, Context, Block, Index): ArgConstraint = ArgConstraint(summon[Index].amoop === n.S)
  // ======================================================================================================
  getArgLut().foreach { case (name, arg) =>
    // camelCase the argument name
    val argName: String = translateToCamelCase(name)
    val argNameLowered = argName.head.toLower + argName.tail

    writer.write(
      s"def ${argNameLowered}Equal(n: Int)(using Arena, Context, Block, Index): ArgConstraint = ArgConstraint(summon[Index].${argNameLowered} === n.S)\n"
    )
  }

  writer.write("\n")

  // ======================================================================================================
  // def hasAmoop()(using Arena, Context, Block, Index): ArgConstraint = amoopRange(0, 32)
  // ======================================================================================================
  getArgLut().foreach { case (name, arg) =>
    // camelCase the argument name
    val argName: String = translateToCamelCase(name)
    val argNameLowered = argName.head.toLower + argName.tail

    val width = arg.msb - arg.lsb + 1
    // if the argument name contains "imm" (case insensitive), use signed range
    val range = if (argName.toLowerCase.contains("imm")) {
      val min = -(1 << (width - 1))
      val max = (1 << (width - 1))
      s"($min, $max)"
    } else {
      s"(0, ${1 << width})"
    }

    writer.write(
      s"def has$argName()(using Arena, Context, Block, Index): ArgConstraint = ${argNameLowered}Range$range\n"
    )
  }

  writer.write("\n")

  // ======================================================================================================
  // def nameId(idx: Int)(using Arena, Context, Block, Index): OpcodeConstraint = OpcodeConstraint(summon[Index].nameId === idx.S)
  // ======================================================================================================
  writer.write(
    "def nameId(idx: Int)(using Arena, Context, Block, Index): OpcodeConstraint = OpcodeConstraint(summon[Index].nameId === idx.S)\n"
  )

  // ======================================================================================================
  // def isRV32C()(using Recipe): SetConstraint = SetConstraint(summon[Recipe].rv32_c)
  // ======================================================================================================
  getExtensions().foreach { ext =>
    val extName = ext.replace("_", "").toUpperCase()
    writer.write(
      s"def is$extName()(using Recipe): SetConstraint = SetConstraint(summon[Recipe].$ext)\n"
    )
  }

  // ======================================================================================================
  // opaque type IsAdd <: InstConstraint = InstConstraint
  // object IsAdd { def apply(r: InstConstraint): IsAdd = r }
  // def isAdd()(using Arena, Context, Block, Index, Recipe): IsAdd = IsAdd(InstConstraint(nameId(238) & isRVI()))
  // ======================================================================================================
  getInstructions().zipWithIndex.foreach { case (instruction, idx) =>
    // CamelCase the instruction name
    val name = translateToCamelCase(instruction.name)

    val suffix = name match {
      case "Slli" => instruction.instructionSet.name.replace("_", "").toUpperCase()
      case "Srai" => instruction.instructionSet.name.replace("_", "").toUpperCase()
      case "Srli" => instruction.instructionSet.name.replace("_", "").toUpperCase()
      case _      => ""
    }

    val typeName = s"Is${name}${suffix}"

    // Unique opaque type for type-safe SpecFor dispatch.
    // Outside this file: IsXxx <: InstConstraint (subtype relationship is known).
    // Within this file: IsXxx = InstConstraint (transparent, enabling the apply).
    writer.write(s"opaque type $typeName <: InstConstraint = InstConstraint\n")
    writer.write(s"object $typeName { def apply(r: InstConstraint): $typeName = r }\n")

    val sets = instruction.instructionSets
      .map(_.name) // e.g., "rv_i", "rv_zicsr", etc.
      .map("is" + _.replace("_", "").toUpperCase() + "()") // e.g., "isRVI()", "isRVZICSR()", etc.

    val s =
      if (sets.length == 1) sets.mkString(" | ") // If there's only one extension, just return join it with " | "
      else sets.mkString("(", " | ", ")")        // If there are multiple extensions, join them with "( | )"

    writer.write(s"def is${name}${suffix}()(using Arena, Context, Block, Index, Recipe): $typeName = $typeName(InstConstraint(nameId($idx) & ${s}))\n")
  }

  writer.write("\n")

  // ======================================================================================================
  // case class Recipe(val name: String)(using Arena, Context, Block)
  // ======================================================================================================
  writer.write("""case class Recipe(val name: String)(using Arena, Context, Block) {
  private val indices = scala.collection.mutable.Map[Int, Index]()
  private val sets = scala.collection.mutable.ListBuffer[Recipe => Ref[Bool]]()
  private val crossIndexConstraints = scala.collection.mutable.ListBuffer[() => Unit]()

  def addIndex(idx: Index): Index = indices.getOrElseUpdate(idx.idx, idx)
  def getIndex(idx: Int): Index = indices(idx)

  def addSetConstraint(c: Recipe => Ref[Bool]): Unit = sets += c
  def getSetConstraints(): Seq[Recipe => Ref[Bool]] = sets.toSeq

  // Cross-index constraints (e.g., cover constraints) - executed in Stage 2
  def addCrossIndexConstraint(c: () => Unit): Unit = crossIndexConstraints += c
  def executeCrossIndexConstraints(): Unit = crossIndexConstraints.foreach(_())

  def allIndices(): Seq[Int] = indices.keys.toSeq.sorted

  // Using lazy val so set variables are only created when accessed (Stage 1 only)
""")

  getExtensions().foreach { ext =>
    writer.write(s"  lazy val $ext = smtValue(\"$ext\", Bool)\n")
  }

  writer.write(s"  lazy val allSets: List[Ref[Bool]] = List(${getExtensions().mkString(", ")})\n")

  writer.write("""

  override def toString(): String = s"Recipe: $name\nIndices:\n${indices.values.map(_.toString).mkString("\n")}"
}

""")

  // ======================================================================================================
  // case class Index(val idx: Int)(using Arena, Context, Block)
  // ======================================================================================================
  writer.write("""case class Index(val idx: Int)(using Arena, Context, Block) {
  // Opcode ID solved in Stage 1
  private var _opcodeId: Option[Int] = None
  def opcodeId: Int = _opcodeId.getOrElse(
    throw new RuntimeException(s"Opcode not yet solved for index $idx. Call this after Stage 1 solving.")
  )
  def setOpcodeId(id: Int): Unit = _opcodeId = Some(id)
  def hasOpcodeId: Boolean = _opcodeId.isDefined

  // Constraints stored in Index
  private val _opcodeConstraints = scala.collection.mutable.ListBuffer[Index => Ref[Bool]]()
  private val _argConstraints = scala.collection.mutable.ListBuffer[Index => Ref[Bool]]()

  def addOpcodeConstraint(c: Index => Ref[Bool]): Unit = _opcodeConstraints += c
  def addArgConstraint(c: Index => Ref[Bool]): Unit = _argConstraints += c
  def getOpcodeConstraints(): Seq[Index => Ref[Bool]] = _opcodeConstraints.toSeq
  def getArgConstraints(): Seq[Index => Ref[Bool]] = _argConstraints.toSeq

  // Convenience methods to check instruction args (requires opcodeId to be set)
  // Uses cached lookup table for performance optimization
  def hasArg(argName: String): Boolean = InstructionArgsCache.hasArg(opcodeId, argName)
  def hasRd: Boolean = InstructionArgsCache.hasRd(opcodeId)
  def hasRs1: Boolean = InstructionArgsCache.hasRs1(opcodeId)
  def hasRs2: Boolean = InstructionArgsCache.hasRs2(opcodeId)

  // Legacy field for compatibility
  var solvedNameId: Option[Int] = None
  // Using lazy val so variables are only created when accessed
  lazy val nameId = smtValue(s"nameId_${idx}", SInt)
""")

  getArgLut().foreach { case (name, arg) =>
    val argName: String = translateToCamelCase(name)
    val argNameLowered = argName.head.toLower + argName.tail
    writer.write(s"  lazy val ${argNameLowered} = smtValue(s\"${name.replace(".", "_")}_$${idx}\", SInt)\n")
  }

  val s = getArgLut().map { case (name, arg) =>
    // CamelCase the argument name
    val argName: String = translateToCamelCase(name)
    val argNameLowered = argName.head.toLower + argName.tail
    s"$$$${${argNameLowered}_$${idx}}"
  }.mkString(", ")

  writer.write(s"""}\n""")

  writer.close()
