// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.rvprobe.scripts

import me.jiuyang.rvprobe.*
import org.chipsalliance.rvdecoderdb.{Encoding, Instruction, InstructionSet}
import os.Path
import java.io.{File, FileWriter}

// Register argument names (raw names from rvdecoderdb ArgLUT) that should use Register enum type
val registerArgNames: Set[String] = Set(
  "rd",
  "rs1",
  "rs2",
  "rs3",
  "rt",
  "vd",
  "vs1",
  "vs2",
  "vs3",
  "rd_p",
  "rs1_p",
  "rs2_p",
  "rd_rs1",
  "rd_rs1_p",
  "rd_rs1_n0",
  "rd_n0",
  "rd_n2",
  "rs1_n0",
  "c_rs1_n0",
  "c_rs2_n0",
  "c_rs2",
  "c_sreg1",
  "c_sreg2"
)

// Run with: mill rvprobe.runMain me.jiuyang.rvprobe.scripts.UpdateAsmApi rvprobe/src/AsmApi.scala
// make sure git repo is clear before running this script

// Instructions that should NOT generate label-based overloads
// (because rvdecoderdb defines them as pseudo-instructions with wrong args)
val skipLabelOverload: Set[String] = Set("jalr", "jr", "c.jalr", "c.jr")

// Immediate merge rules: when an instruction has both hiField and loField,
// they are merged into a single semantic parameter in the generated API.
// The constraint body splits the merged value back into hi/lo parts.
case class ImmMergeRule(hiField: String, loField: String, mergedName: String, hiWidth: Int, loWidth: Int)

val immMergeRules: Seq[ImmMergeRule] = Seq(
  ImmMergeRule(hiField = "imm12hi",  loField = "imm12lo",  mergedName = "offset",  hiWidth = 7, loWidth = 5),
  ImmMergeRule(hiField = "bimm12hi", loField = "bimm12lo", mergedName = "offset",  hiWidth = 7, loWidth = 5)
)

// Find applicable merge rule for an instruction's arg set
def findMergeRule(argNames: Set[String]): Option[ImmMergeRule] =
  immMergeRules.find(r => argNames.contains(r.hiField) && argNames.contains(r.loField))

@main def UpdateAsmApi(outputPath: String): Unit =
  val writer = new FileWriter(new File(outputPath))

  writer.write(
    """// SPDX-License-Identifier: Apache-2.0
      |// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
      |package me.jiuyang.rvprobe
      |
      |import me.jiuyang.rvprobe.Register
      |import me.jiuyang.rvprobe.constraints.*
      |
      |import me.jiuyang.smtlib.default.{*, given}
      |import me.jiuyang.smtlib.tpe.*
      |
      |import org.llvm.mlir.scalalib.capi.ir.{Block, Context, given}
      |
      |import java.lang.foreign.Arena
      |
      |// format: off
      |// ================= AUTO GENERATED BY UpdateAsmApi.scala =======================
      |//
      |//  Assembly-like API for writing fixed-value constraints.
      |//
      |//  The instruction index is auto-incremented via Recipe.nextIdx().
      |//  Split immediates (imm12hi/lo, bimm12hi/lo) are merged into a single
      |//  semantic parameter (offset) matching GAS syntax conventions.
      |//  Zero-arg instructions (ecall, mret, etc.) are also generated.
      |// =============================================================================
      |
""".stripMargin
  )

  // For each instruction, generate an assembly-like convenience function:
  //   def instrName(arg1: Int, arg2: Int, ...)(using Arena, Context, Block, Recipe): Unit =
  //     instruction(summon[Recipe].nextIdx(), isInstrName()) { arg1Equal(v1) & arg2Equal(v2) & ... }
  //   For zero-arg instructions (ecall, mret, etc.):
  //   def ecall()(using Arena, Context, Block, Recipe): Unit =
  //     instruction(summon[Recipe].nextIdx(), isEcall()) { ArgConstraint(true.B) }
  getInstructions().foreach { instruction =>
    val name = translateToCamelCase(instruction.name)

    val funcName = name.head.toLower + name.tail
    val isFunc   = s"is${name}"

    val argNames  = instruction.args.map(_.name).toSet
    val mergeRule = findMergeRule(argNames)
    val hasBimm   = argNames.contains("bimm12hi") && argNames.contains("bimm12lo")
    val hasJimm   = argNames.contains("jimm20")

    if (instruction.args.nonEmpty) {
      // Filter out fields that will be merged, collect non-merged args
      val mergedFields = mergeRule.map(r => Set(r.hiField, r.loField)).getOrElse(Set.empty)
      val nonMergedArgs = instruction.args.filterNot(a => mergedFields.contains(a.name))

      // Build parameter list: non-merged args + merged parameter (if any)
      val nonMergedParams = nonMergedArgs.map { arg =>
        val argName        = translateToCamelCase(arg.name)
        val argNameLowered = argName.head.toLower + argName.tail
        val tpe            = if registerArgNames.contains(arg.name) then "Register" else "Int"
        s"$argNameLowered: $tpe"
      }
      val params = mergeRule match {
        case Some(rule) => (nonMergedParams :+ s"${rule.mergedName}: Int").mkString(", ")
        case None       => nonMergedParams.mkString(", ")
      }

      // Build constraint body: non-merged arg constraints + split constraints for merged imm
      val nonMergedConstraints = nonMergedArgs.map { arg =>
        val argName        = translateToCamelCase(arg.name)
        val argNameLowered = argName.head.toLower + argName.tail
        val value          = if registerArgNames.contains(arg.name) then s"$argNameLowered.ordinal" else argNameLowered
        s"${argNameLowered}Equal($value) & has${argName}()"
      }
      val constraints = mergeRule match {
        case Some(rule) =>
          val hiCamel    = translateToCamelCase(rule.hiField)
          val hiLowered  = hiCamel.head.toLower + hiCamel.tail
          val loCamel    = translateToCamelCase(rule.loField)
          val loLowered  = loCamel.head.toLower + loCamel.tail
          val loMask     = (1 << rule.loWidth) - 1
          val splitParts = Seq(
            s"${hiLowered}Equal(${rule.mergedName} >> ${rule.loWidth}) & has${hiCamel}()",
            s"${loLowered}Equal(${rule.mergedName} & $loMask) & has${loCamel}()"
          )
          (nonMergedConstraints ++ splitParts).mkString(" & ")
        case None =>
          nonMergedConstraints.mkString(" & ")
      }

      writer.write(
        s"def $funcName($params)(using Arena, Context, Block, Recipe): Unit = instruction(summon[Recipe].nextIdx(), $isFunc()) { $constraints }\n"
      )

      // Generate label-based overload for branch instructions (bimm12hi/bimm12lo)
      if (hasBimm && !skipLabelOverload.contains(instruction.name)) {
        // With merged imm, non-imm args are already in nonMergedArgs (since bimm fields are merged)
        val labelNonImmArgs = nonMergedArgs
        val nonImmParams = labelNonImmArgs.map { arg =>
          val argName        = translateToCamelCase(arg.name)
          val argNameLowered = argName.head.toLower + argName.tail
          val tpe            = if registerArgNames.contains(arg.name) then "Register" else "Int"
          s"$argNameLowered: $tpe"
        }.mkString(", ")
        val labelParams = if (nonImmParams.isEmpty) "target: String" else s"$nonImmParams, target: String"

        val labelConstraints = labelNonImmArgs.map { arg =>
          val argName        = translateToCamelCase(arg.name)
          val argNameLowered = argName.head.toLower + argName.tail
          val value          = if registerArgNames.contains(arg.name) then s"$argNameLowered.ordinal" else argNameLowered
          s"${argNameLowered}Equal($value)"
        }.mkString(" & ")
        val fullConstraints = if (labelConstraints.isEmpty) "bimm12hiEqual(0) & bimm12loEqual(0)" else s"$labelConstraints & bimm12hiEqual(0) & bimm12loEqual(0)"

        writer.write(
          s"def $funcName($labelParams)(using Arena, Context, Block, Recipe): Unit = {\n"
        )
        writer.write(
          s"  val idx = summon[Recipe].nextIdx()\n"
        )
        writer.write(
          s"  instruction(idx, $isFunc()) { $fullConstraints }\n"
        )
        writer.write(
          s"  labelRef(idx, target)\n"
        )
        writer.write(
          s"}\n"
        )
      }

      // Generate label-based overload for jump instructions (jimm20)
      if (hasJimm) {
        val nonImmArgs = instruction.args.filter(arg => arg.name != "jimm20")
        val nonImmParams = nonImmArgs.map { arg =>
          val argName        = translateToCamelCase(arg.name)
          val argNameLowered = argName.head.toLower + argName.tail
          val tpe            = if registerArgNames.contains(arg.name) then "Register" else "Int"
          s"$argNameLowered: $tpe"
        }.mkString(", ")
        val labelParams = if (nonImmParams.isEmpty) "target: String" else s"$nonImmParams, target: String"

        val labelConstraints = nonImmArgs.map { arg =>
          val argName        = translateToCamelCase(arg.name)
          val argNameLowered = argName.head.toLower + argName.tail
          val value          = if registerArgNames.contains(arg.name) then s"$argNameLowered.ordinal" else argNameLowered
          s"${argNameLowered}Equal($value)"
        }.mkString(" & ")
        val fullConstraints = if (labelConstraints.isEmpty) "jimm20Equal(0)" else s"$labelConstraints & jimm20Equal(0)"

        writer.write(
          s"def $funcName($labelParams)(using Arena, Context, Block, Recipe): Unit = {\n"
        )
        writer.write(
          s"  val idx = summon[Recipe].nextIdx()\n"
        )
        writer.write(
          s"  instruction(idx, $isFunc()) { $fullConstraints }\n"
        )
        writer.write(
          s"  labelRef(idx, target)\n"
        )
        writer.write(
          s"}\n"
        )
      }
    } else {
      // Zero-arg instructions (ecall, ebreak, mret, etc.)
      writer.write(
        s"def $funcName()(using Arena, Context, Block, Recipe): Unit = instruction(summon[Recipe].nextIdx(), $isFunc()) { ArgConstraint.noArgs }\n"
      )
    }
  }

  writer.write("\n// format: on\n")
  writer.close()
