// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.rvprobe.scripts

import me.jiuyang.rvprobe.*
import me.jiuyang.rvprobe.scripts.registerArgNames
import org.chipsalliance.rvdecoderdb.{Encoding, Instruction, InstructionSet}
import os.Path
import java.io.{File, FileWriter}

// Run with: mill rvprobe.runMain me.jiuyang.rvprobe.scripts.UpdateRVConstraints rvprobe/src/constraints
// make sure git repo is clear before running this script
//
// Generates a single file:
//   RVConstraints.scala — Recipe, Index, arg constraints, set constraints, opcode constraints

// Opaque types to keep for SpecFor type class instances.
// All other instruction types use InstConstraint directly.
val keepOpaqueTypes: Set[String] = Set(
  "IsFence",
  "IsCAddi4spn",
  "IsCLui",
  "IsCAddi",
  "IsCAddiw",
  "IsCAddi16sp",
  "IsCSlli",
  "IsCLdsp",
  "IsCLwsp"
)

val header: String =
  """// SPDX-License-Identifier: Apache-2.0
    |// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
    |package me.jiuyang.rvprobe.constraints
    |
    |import me.jiuyang.rvprobe.{InstructionArgsCache, Statement}
    |
    |import me.jiuyang.smtlib.default.{*, given}
    |import me.jiuyang.smtlib.tpe.*
    |
    |import org.llvm.mlir.scalalib.capi.ir.{Block, Context, Location, LocationApi, Operation, Type, Value, given}
    |
    |import java.lang.foreign.Arena
    |
    |// format: off
    |// ================= AUTO GENERATED BY UpdateRVConstraints.scala =======================
    |""".stripMargin

def constraintsArgIdent(name: String): String =
  val argName        = translateToCamelCase(name)
  val argNameLowered = argName.head.toLower + argName.tail
  if (argNameLowered == "opcode") "opcodeBits" else argNameLowered

def constraintsArgSmtName(name: String): String =
  if (constraintsArgIdent(name) == "opcodeBits") "opcode_bits" else name.replace(".", "_")

@main def UpdateRVConstraints(outputDir: String): Unit =
  val dir = new File(outputDir)
  if (!dir.isDirectory) throw new RuntimeException(s"$outputDir is not a directory")

  val w = new FileWriter(new File(dir, "RVConstraints.scala"))
  w.write(header)

  // ==================== Recipe class ====================
  w.write("""case class Recipe(val name: String)(using Arena, Context, Block) {
  private val _indices = scala.collection.mutable.Map[Int, Index]()
  private val _sets = scala.collection.mutable.ListBuffer[Recipe => Ref[Bool]]()
  private val _crossIndexConstraints = scala.collection.mutable.ListBuffer[() => Unit]()
  private val _statements = scala.collection.mutable.ArrayBuffer[Statement]()

  // Auto-incrementing instruction index for assembly-like API
  private var _nextIdx: Int = 0
  def nextIdx(): Int = { val idx = _nextIdx; _nextIdx += 1; idx }
  def peekNextIdx(): Int = _nextIdx

  // Symbolic register variables created by freshReg(). Auto-distinct in Stage 2.
  private var _freshRegCounter: Int = 0
  private val _freshRegs = scala.collection.mutable.ListBuffer[Referable[SInt]]()
  def nextFreshRegId(): Int = { val id = _freshRegCounter; _freshRegCounter += 1; id }
  def registerFreshReg(v: Referable[SInt]): Unit = _freshRegs += v
  def freshRegs(): Seq[Referable[SInt]] = _freshRegs.toSeq

  // Fixed registers declared by fragments via useFixed(). freshRegs must avoid these.
  private val _fixedRegs = scala.collection.mutable.Set[Int]()
  def recordFixedReg(ordinal: Int): Unit = _fixedRegs += ordinal
  def fixedRegs(): Set[Int] = _fixedRegs.toSet

  def addStatement(s: Statement): Unit = _statements += s
  def allStatements(): Seq[Statement] = _statements.toSeq

  def addIndex(idx: Index): Index = {
    // Keep _nextIdx above any manually-added index to avoid collisions
    if (idx.idx >= _nextIdx) _nextIdx = idx.idx + 1
    _indices.getOrElseUpdate(idx.idx, idx)
  }
  def getIndex(idx: Int): Index = _indices(idx)

  def addSetConstraint(c: Recipe => Ref[Bool]): Unit = _sets += c
  def getSetConstraints(): Seq[Recipe => Ref[Bool]] = _sets.toSeq

  // Cross-index constraints (e.g., cover constraints) - executed in Stage 2
  def addCrossIndexConstraint(c: () => Unit): Unit = _crossIndexConstraints += c
  def executeCrossIndexConstraints(): Unit = _crossIndexConstraints.foreach(_())

  def allIndices(): Seq[Int] = _indices.keys.toSeq.sorted

  // Using lazy val so set variables are only created when accessed (Stage 1 only)
""")

  getExtensions().foreach { ext =>
    w.write(s"  lazy val $ext = smtValue(\"$ext\", Bool)\n")
  }

  w.write(s"  lazy val allSets: List[Ref[Bool]] = List(${getExtensions().mkString(", ")})\n}\n")

  // ==================== Index class ====================
  w.write("""case class Index(val idx: Int)(using Arena, Context, Block) {
  // Opcode ID solved in Stage 1
  private var _opcodeId: Option[Int] = None
  def opcodeId: Int = _opcodeId.getOrElse(
    throw new RuntimeException(s"Opcode not yet solved for index $idx. Call this after Stage 1 solving.")
  )
  def setOpcodeId(id: Int): Unit = _opcodeId = Some(id)
  def hasOpcodeId: Boolean = _opcodeId.isDefined

  // Constraints stored in Index
  private val _opcodeConstraints = scala.collection.mutable.ListBuffer[Index => Ref[Bool]]()
  private val _argConstraints = scala.collection.mutable.ListBuffer[Index => Ref[Bool]]()

  def addOpcodeConstraint(c: Index => Ref[Bool]): Unit = _opcodeConstraints += c
  def addArgConstraint(c: Index => Ref[Bool]): Unit = _argConstraints += c
  def getOpcodeConstraints(): Seq[Index => Ref[Bool]] = _opcodeConstraints.toSeq
  def getArgConstraints(): Seq[Index => Ref[Bool]] = _argConstraints.toSeq

  // Convenience methods to check instruction args (requires opcodeId to be set)
  // Uses cached lookup table for performance optimization
  def hasArg(argName: String): Boolean = InstructionArgsCache.hasArg(opcodeId, argName)
  def hasRd: Boolean = InstructionArgsCache.hasRd(opcodeId)
  def hasRs1: Boolean = InstructionArgsCache.hasRs1(opcodeId)
  def hasRs2: Boolean = InstructionArgsCache.hasRs2(opcodeId)

  // Solved opcode selector cache
  var solvedOpcode: Option[Int] = None
  // Using lazy val so variables are only created when accessed
  lazy val opcode = smtValue(s"opcode_${idx}", SInt)
""")

  getArgLut().foreach { case (name, arg) =>
    val argNameLowered = constraintsArgIdent(name)
    w.write(s"  lazy val ${argNameLowered} = smtValue(s\"${constraintsArgSmtName(name)}_$${idx}\", SInt)\n")
  }

  w.write("}\n")

  // ==================== Set constraints ====================
  w.write(
    "def opcodeId(idx: Int)(using Arena, Context, Block, Index): OpcodeConstraint = OpcodeConstraint(summon[Index].opcode === idx.S)\n"
  )

  getExtensions().foreach { ext =>
    val extName = ext.replace("_", "").toUpperCase()
    w.write(
      s"def is$extName()(using Recipe): SetConstraint = SetConstraint(summon[Recipe].$ext)\n"
    )
  }

  // ==================== Arg constraints ====================
  // xxxRange functions
  getArgLut().foreach { case (name, arg) =>
    val argName: String = translateToCamelCase(name)
    val argNameLowered = constraintsArgIdent(name)
    w.write(
      s"def ${argNameLowered}Range(start: Int, end: Int)(using Arena, Context, Block, Index): ArgConstraint = ArgConstraint(summon[Index].${argNameLowered} >= start.S & summon[Index].${argNameLowered} < end.S)\n"
    )
  }

  // xxxEqual functions
  getArgLut().foreach { case (name, arg) =>
    val argName: String = translateToCamelCase(name)
    val argNameLowered = constraintsArgIdent(name)
    if (registerArgNames.contains(name)) {
      w.write(
        s"def ${argNameLowered}Equal(ref: Referable[SInt])(using Arena, Context, Block, Index): ArgConstraint = ArgConstraint(summon[Index].${argNameLowered} === ref)\n"
      )
    } else {
      w.write(
        s"def ${argNameLowered}Equal(n: Int)(using Arena, Context, Block, Index): ArgConstraint = ArgConstraint(summon[Index].${argNameLowered} === n.S)\n"
      )
    }
  }

  // hasXxx functions
  getArgLut().foreach { case (name, arg) =>
    val argName: String = translateToCamelCase(name)
    val argNameLowered = constraintsArgIdent(name)
    val hasName = if (argNameLowered == "opcodeBits") "OpcodeBits" else argName

    val width = arg.msb - arg.lsb + 1
    val range = if (argName.toLowerCase.contains("imm") && !argName.contains("lo") && !argName.contains("hi")) {
      val min = -(1 << (width - 1))
      val max = (1 << (width - 1))
      s"($min, $max)"
    } else if (argName.endsWith("P")) {
      s"(8, ${8 + (1 << width) - 1})"
    } else if (argName.endsWith("N0")) {
      s"(1, ${1 << width})"
    } else {
      s"(0, ${1 << width})"
    }

    w.write(s"def has$hasName()(using Arena, Context, Block, Index): ArgConstraint = ${argNameLowered}Range$range")
    if (argName.endsWith("N2")) {
      w.write(s" & !${argNameLowered}Equal(2.S)")
    }
    w.write("\n")
  }

  // ==================== Opcode constraints ====================
  val merged = getMergedInstructions().zipWithIndex

  merged.foreach { case (variant, opcodeIdx) =>
    val name     = translateToCamelCase(variant.name)
    val typeName = s"Is$name"

    val setsExprParts = variant.sets.map(s => "is" + s.name.replace("_", "").toUpperCase() + "()")
    val setsExpr      =
      if (setsExprParts.length == 1) setsExprParts.head
      else setsExprParts.mkString("(", " | ", ")")

    val opcodeExpr = s"opcodeId($opcodeIdx)"

    if (keepOpaqueTypes.contains(typeName)) {
      w.write(s"opaque type $typeName <: OpcodeConstraint = OpcodeConstraint\n")
      w.write(s"object $typeName { def apply(r: OpcodeConstraint): $typeName = r }\n")
      w.write(
        s"def is${name}()(using Arena, Context, Block, Index, Recipe): $typeName = $typeName(OpcodeConstraint($opcodeExpr & ${setsExpr}))\n"
      )
    } else {
      w.write(
        s"def is${name}()(using Arena, Context, Block, Index, Recipe): OpcodeConstraint = OpcodeConstraint($opcodeExpr & ${setsExpr})\n"
      )
    }
  }

  w.write("\n// format: on\n")
  w.close()
