// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.rvprobe.scripts

import me.jiuyang.rvprobe.*
import org.chipsalliance.rvdecoderdb.{Encoding, Instruction, InstructionSet}
import os.Path
import java.io.{File, FileWriter}

// Run with: mill rvprobe.runMain me.jiuyang.rvprobe.scripts.UpdateAsmApi rvprobe/src/AsmApi.scala
// make sure git repo is clear before running this script
@main def UpdateAsmApi(outputPath: String): Unit =
  val writer = new FileWriter(new File(outputPath))

  writer.write(
    """// SPDX-License-Identifier: Apache-2.0
      |// SPDX-FileCopyrightText: 2025 Jianhao Ye <Clo91eaf@qq.com>
      |package me.jiuyang.rvprobe
      |
      |import me.jiuyang.rvprobe.constraints.*
      |
      |import me.jiuyang.smtlib.default.{*, given}
      |import me.jiuyang.smtlib.tpe.*
      |
      |import org.llvm.mlir.scalalib.capi.ir.{Block, Context, given}
      |
      |import java.lang.foreign.Arena
      |
      |// format: off
      |// ================= AUTO GENERATED BY UpdateAsmApi.scala =======================
      |//
      |//  Assembly-like API for writing fixed-value constraints.
      |//
      |//  Instead of:
      |//    instruction(0, isAddi()) { rdEqual(1) & rs1Equal(1) & imm12Equal(1) }
      |//  Write:
      |//    addi(1, 1, 1)   // → addi x1, x1, 1
      |//
      |//  The instruction index is auto-incremented via Recipe.nextIdx().
      |//  Parameters follow the rvdecoderdb argument order for each instruction.
      |//  Only instructions with at least one argument field are generated.
      |// =============================================================================
      |
""".stripMargin
  )

  // For each instruction, generate an assembly-like convenience function:
  //   def instrName(arg1: Int, arg2: Int, ...)(using Arena, Context, Block, Recipe): Unit =
  //     instruction(summon[Recipe].nextIdx(), isInstrName()) { arg1Equal(v1) & arg2Equal(v2) & ... }
  getInstructions().foreach { instruction =>
    // Skip instructions with no argument fields (e.g., ecall, ebreak)
    if (instruction.args.nonEmpty) {
      val name = translateToCamelCase(instruction.name)

      // Handle slli/srli/srai suffix disambiguation (same logic as UpdateRVConstraints.scala)
      val suffix = name match {
        case "Slli" => instruction.instructionSet.name.replace("_", "").toUpperCase()
        case "Srai" => instruction.instructionSet.name.replace("_", "").toUpperCase()
        case "Srli" => instruction.instructionSet.name.replace("_", "").toUpperCase()
        case _      => ""
      }

      val funcName = {
        val full = s"${name}${suffix}"
        full.head.toLower + full.tail
      }
      val isFunc   = s"is${name}${suffix}"

      // Build parameter list and constraint body from instruction args
      val params = instruction.args.map { arg =>
        val argName        = translateToCamelCase(arg.name)
        val argNameLowered = argName.head.toLower + argName.tail
        s"$argNameLowered: Int"
      }.mkString(", ")

      val constraints = instruction.args.map { arg =>
        val argName        = translateToCamelCase(arg.name)
        val argNameLowered = argName.head.toLower + argName.tail
        s"${argNameLowered}Equal($argNameLowered)"
      }.mkString(" & ")

      writer.write(
        s"def $funcName($params)(using Arena, Context, Block, Recipe): Unit = instruction(summon[Recipe].nextIdx(), $isFunc()) { $constraints }\n"
      )
    }
  }

  writer.write("\n// format: on\n")
  writer.close()
