// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 Jiuyang Liu <liu@jiuyang.me>
package me.jiuyang.zaozi

import scala.annotation.targetName
import scala.util.chaining.*

import me.jiuyang.zaozi.magic.macros.summonLayersImpl
import me.jiuyang.zaozi.ltltpe.*
import me.jiuyang.zaozi.reftpe.*
import me.jiuyang.zaozi.valuetpe.*

import org.llvm.circt.scalalib.dialect.firrtl.operation.{ExtModule as CirctExtModule, Module as CirctModule, When}
import org.llvm.mlir.scalalib.capi.ir.{Block, Context, Operation, Type, Value}

import java.lang.foreign.Arena

/** Rebuild the [[Layer]] with each [[Layer]] contains the entire tree. */
trait LayerTree:
  layer =>
  def name:      String
  def children:  Seq[LayerTree]
  def parent:    Option[LayerTree] = None
  def hierarchy: Seq[LayerTree]    =
    parent match
      case Some(p) => p.hierarchy :+ this
      case None    => Seq(this)
  def _dfs:      Seq[LayerTree]    =
    this +: children.flatMap(_._dfs)
  def _rebuild:  LayerTree         =
    def rebuildLayer(_oldLayer: LayerTree, _parent: Option[LayerTree]): LayerTree =
      new LayerTree:
        override def name:     String            = _oldLayer.name
        override def children: Seq[LayerTree]    =
          _oldLayer.children.map(child => rebuildLayer(child, Some(this)))
        override def parent:   Option[LayerTree] = _parent
    rebuildLayer(this, None)

/** Serializable Layer definition. */
case class Layer(name: String, children: Seq[Layer] = Seq.empty):
  layer =>
  def toLayerTree: LayerTree =
    new LayerTree:
      def name:     String         = layer.name
      def children: Seq[LayerTree] = layer.children.map(_.toLayerTree)
    ._rebuild
extension (layers: Seq[Layer]) def toLayerTrees: Seq[LayerTree]   = layers.map(_.toLayerTree)
extension (layer:  LayerTree) def nameHierarchy = layer.hierarchy.map(_.name)
extension (layers: Seq[LayerTree])
  def nameHierarchies:                           Seq[Seq[String]] =
    layers.flatMap(_._dfs).filter(_.children.isEmpty).map(_.nameHierarchy)

abstract class Parameter                                    extends Product
abstract class LayerInterface[P <: Parameter](parameter: P) extends Seq[LayerTree]:
  def layers: Seq[Layer]

  final override def apply(idx: Int) = layers.toLayerTrees(idx)
  final override def iterator        = layers.toLayerTrees.iterator
  final override def length          = layers.toLayerTrees.length

trait HWInterface[P <: Parameter](parameter: P)       extends Aggregate:
  this: Bundle | Record =>
abstract class HWBundle[P <: Parameter](parameter: P) extends HWInterface(parameter) with Bundle
abstract class HWRecord[P <: Parameter](parameter: P) extends HWInterface(parameter) with Record

trait DVInterface[P <: Parameter, L <: LayerInterface[P]](parameter: P) extends Aggregate:
  this: ProbeBundle | ProbeRecord =>
  private var _layersOpt:              Option[L]         = None
  transparent inline def summonLayers: LayerInterface[?] = ${ summonLayersImpl }
  transparent inline def layers:       L                 = _layersOpt.getOrElse:
    summonLayers.asInstanceOf[L].tap(l => _layersOpt = Some(l))
abstract class DVBundle[P <: Parameter, L <: LayerInterface[P]](parameter: P)
    extends DVInterface[P, L](parameter)
    with ProbeBundle
abstract class DVRecord[P <: Parameter, L <: LayerInterface[P]](parameter: P)
    extends DVInterface[P, L](parameter)
    with ProbeRecord
class InstanceContext:
  class AnonSignalCounter(private var _count: Int):
    def count = _count
    def inc() =
      val o = count
      _count += 1
      o

  val anonSignalCounter = new AnonSignalCounter(0)

trait Generator[PARAM <: Parameter, L <: LayerInterface[PARAM], I <: HWInterface[PARAM], P <: DVInterface[PARAM, L]]:
  /* For traits with self-type annotation that don't want type parameters
     e.g
      trait SomeGenerator:
        this: Generator[?, ?, ?] =>
        private val self = this.asInstanceOf[Generator[this.TPARAM, this.TINTF, this.TPROBE]]
   */
  type TPARAM = PARAM
  type TLAYER = L
  type TINTF  = I
  type TPROBE = P

  def moduleName(parameter: PARAM): String =
    s"${this.getClass.getSimpleName.stripSuffix("$")}_${parameter.hashCode.toHexString}"

  def architecture(parameter: PARAM): (
    Arena,
    Context,
    Block,
    Interface[I],
    Interface[P],
    L,
    InstanceContext
  ) ?=> Unit

  private[zaozi] val elaboratedModules = scala.collection.mutable.HashSet.empty[PARAM]

  // fields should be generated by macro automatically
  def layers(parameter:    PARAM): L
  def interface(parameter: PARAM): I
  def probe(parameter:     PARAM): P

  def parseParameter(args: Seq[String]): PARAM

  def main(args: Array[String]): Unit

abstract class VerilogParameter extends Product

trait VerilogWrapper[
  PARAM <: Parameter,
  L <: LayerInterface[PARAM],
  I <: HWInterface[PARAM],
  P <: DVInterface[PARAM, L],
  V <: VerilogParameter]:
  type TPARAM  = PARAM
  type TLAYER  = L
  type TINTF   = I
  type TPROBE  = P
  type TVPARAM = V

  def verilogModuleName(parameter: PARAM): String

  // ensure that the moduleName is unique for each verilog parameter
  def moduleName(parameter: PARAM): String =
    s"${verilogModuleName(parameter)}_${verilogParameter(parameter).hashCode.toHexString}"

  def verilogParameter(parameter: PARAM): V

  private[zaozi] val elaboratedModules = scala.collection.mutable.HashSet.empty[PARAM]

  // fields should be generated by macro automatically
  def layers(parameter:    PARAM): L
  def interface(parameter: PARAM): I
  def probe(parameter:     PARAM): P

  def parseParameter(args: Seq[String]): PARAM

  def main(args: Array[String]): Unit

// No type params in trait for easy exporting
trait GeneratorApi:
  extension [PARAM <: Parameter, L <: LayerInterface[PARAM], I <: HWInterface[PARAM], P <: DVInterface[PARAM, L]](
    generator: Generator[PARAM, L, I, P]
  )
    private[zaozi] def module(
      parameter: PARAM
    )(
      using Arena,
      Context
    ): CirctModule

    private[zaozi] def instance(
      parameter: PARAM
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Instance[I, P]

    def instantiate(
      parameter: PARAM
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Instance[I, P]

    def dumpMlirbc(
      parameter: PARAM
    )(
      using Arena,
      Context
    ): Unit

    def mainImpl(
      args: Array[String]
    )(
      using upickle.default.ReadWriter[PARAM]
    ): Unit

trait VerilogWrapperApi:
  extension [
    PARAM <: Parameter,
    L <: LayerInterface[PARAM],
    I <: HWInterface[PARAM],
    P <: DVInterface[PARAM, L],
    V <: VerilogParameter
  ](wrapper: VerilogWrapper[PARAM, L, I, P, V]
  )
    private[zaozi] def instance(
      parameter: PARAM
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Instance[I, P]

    def instantiate(
      parameter: PARAM
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Instance[I, P]

trait ConstructorApi:
  def Clock(): Clock

  def Reset(): Reset

  def AsyncReset(): Reset

  def UInt(width: Int): UInt

  def Bits(width: Int): Bits

  def SInt(width: Int): SInt

  def Bool(): Bool

  def Vec[T <: Data](size: Int, tpe: T): Vec[T]

  def when[COND <: Referable[Bool]](
    cond: COND
  )(body: (Arena, Context, Block) ?=> Unit
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line
  ): When

  extension (when: When)
    def otherwise(
      body: (Arena, Context, Block) ?=> Unit
    )(
      using Arena,
      Context
    ): Unit

  extension (layer: LayerTree) def apply(name: String): LayerTree

  extension (layers: Seq[LayerTree]) def apply(name: String): LayerTree

  def layer(
    layerName: String
  )(body:      (
      Arena,
      Context,
      Block,
      LayerTree,
      Seq[LayerTree],
      sourcecode.File,
      sourcecode.Line
    ) ?=> Unit
  )(
    using Arena,
    Context,
    Block,
    Seq[LayerTree],
    sourcecode.File,
    sourcecode.Line
  ): Unit

  def Wire[T <: Data](
    refType: T
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ):   Wire[T]
  def Reg[T <: Data](
    refType: T
  )(
    using Arena,
    Context,
    Block,
    Ref[Clock],
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ):   Reg[T]
  def RegInit[T <: Data](
    input: Const[T]
  )(
    using Arena,
    Context,
    Block,
    Ref[Clock],
    Ref[Reset],
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ):   Reg[T]
  def Node[T <: Data](
    ref: Referable[T]
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ):   Node[T]
  extension (bigInt: BigInt)
    def U(
      width: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line
    ): Const[UInt]
    def U(
      using Arena,
      Context,
      Block
    ): Const[UInt]
    def B(
      using Arena,
      Context,
      Block
    ): Const[Bits]
    def S(
      width: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line
    ): Const[SInt]
    def S(
      using Arena,
      Context,
      Block
    ): Const[SInt]
  extension (bool:   Boolean)
    def B(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line
    ): Const[Bool]
end ConstructorApi

trait AsBits[D <: Data]:
  extension [R <: Referable[D]](ref: R)
    def asBits(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Propagated[R, Bits]
trait AsBool[D <: Data]:
  extension [R <: Referable[D]](ref: R)
    def asBool(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Propagated[R, Bool]
trait AsSInt[D <: Data]:
  extension [R <: Referable[D]](ref: R)
    def asSInt(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Propagated[R, SInt]
trait AsUInt[D <: Data]:
  extension [R <: Referable[D]](ref: R)
    def asUInt(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Propagated[R, UInt]

trait AsBundle[D <: Data]:
  extension [R <: Referable[D]](ref: R)
    def asBundle[T <: Bundle](
      tpe: T
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Propagated[R, T]

trait AsRecord[D <: Data]:
  extension [R <: Referable[D]](ref: R)
    def asRecord[T <: Record](
      tpe: T
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Propagated[R, T]

trait AsVec[D <: Data]:
  extension [R <: Referable[D]](ref: R)
    def asVec[E <: Data](
      tpe: E
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Propagated[R, Vec[E]]

/** Zero-cost re-view of a [[Bundle]] as a string-keyed [[Record]] over the same value (no bitcast; cf. [[AsRecord]]).
  */
trait AsRecordView[D <: Bundle]:
  extension [R <: Referable[D] & HasOperation](ref: R) def asRecord: Propagated[R, Record]

trait AsProbeRecordView[D <: ProbeBundle]:
  extension [R <: Referable[D] & HasOperation](ref: R) def asRecord: Propagated[R, ProbeRecord]

trait ProbeConnect[D <: Data & CanProbe, P <: RWProbe[D] | RProbe[D], DATA <: Referable[D], PROBE <: Referable[P]]:
  extension (ref: PROBE)
    @targetName("send")
    def <==(
      that: DATA
    )(
      using Arena,
      Context,
      Block,
      LayerTree,
      sourcecode.File,
      sourcecode.Line
    ): Unit

    @targetName("define")
    def <==(
      that: PROBE
    )(
      using Arena,
      Context,
      Block,
      LayerTree,
      sourcecode.File,
      sourcecode.Line
    ): Unit

  extension (ref: DATA)
    @targetName("resolve")
    def <==(
      that: PROBE
    )(
      using Arena,
      Context,
      Block,
      LayerTree,
      sourcecode.File,
      sourcecode.Line
    ): Unit
trait MonoConnect[D <: Data, SRC <: Referable[D], SINK <: Writable[D]]:
  extension (ref: SINK)
    def :=(
      that: SRC
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line
    ): Unit
trait Cvt[D <: Data, RET <: Data]:
  extension [R <: Referable[D]](ref: R)
    def zext(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Neg[D <: Data, RET <: Data]:
  extension [R <: Referable[D]](ref: R)
    def unary_!(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Not[D <: Data, RET <: Data]:
  extension [R <: Referable[D]](ref: R)
    def unary_~(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait AndR[D <: Data, RET <: Data]:
  extension [R <: Referable[D]](ref: R)
    def andR(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait OrR[D <: Data, RET <: Data]:
  extension [R <: Referable[D]](ref: R)
    def orR(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait XorR[D <: Data, RET <: Data]:
  extension [R <: Referable[D]](ref: R)
    def xorR(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Add[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def +[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Sub[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def -[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Mul[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def *[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Div[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def /[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Rem[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def %[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Lt[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def <[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Leq[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def <=[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Gt[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def >[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Geq[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def >=[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Eq[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def ===[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Neq[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def =/=[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait And[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def &[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Or[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def |[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Xor[D <: Data, RET <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def ^[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[RET]
trait Cat[D <: Data]:
  extension [LHS <: Referable[D]](ref: LHS)
    def ##[RHS <: Referable[D]](
      that: RHS
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[D]

trait Shl[D <: Data, OUT <: Data]:
  extension [R <: Referable[D]](ref: R)
    def <<(
      that: Int | Referable[UInt]
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[OUT]
trait Shr[D <: Data, OUT <: Data]:
  extension [R <: Referable[D]](ref: R)
    def >>(
      that: Int | Referable[UInt]
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[D]
trait Head[D <: Data, OUT <: Data]:
  extension [R <: Referable[D]](ref: R)
    def head(
      that: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[OUT]
trait Tail[D <: Data, OUT <: Data]:
  extension [R <: Referable[D]](ref: R)
    def tail(
      that: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[OUT]
trait Pad[D <: Data, OUT <: Data]:
  extension [R <: Referable[D]](ref: R)
    def pad(
      that: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[OUT]
trait ExtractRange[D <: Data, E <: Data]:
  extension [R <: Referable[D]](ref: R)
    def bits(
      hi: Int,
      lo: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[E]
trait ExtractElement[D <: Data, E <: Data]:
  extension [R <: Referable[D]](ref: R)
    def bit(
      idx: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[E]
trait Mux[Cond <: Data]:
  extension [CondR <: Referable[Cond]](ref: CondR)
    def ?[Ret <: Data](
      con: Referable[Ret],
      alt: Referable[Ret]
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Node[Ret]
trait RefElement[D <: Data, E <: Data]:
  extension [R <: Referable[D]](ref: R)
    def ref(
      idx: Int | Referable[UInt]
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Ref[E]
trait GetLength[E <: Data, V <: Vec[E]]:
  extension [R <: Referable[V]](ref: R)
    def length(
      using Arena,
      Context
    ): Int

trait BitsApi
    extends AsSInt[Bits]
    with AsUInt[Bits]
    with AsBool[Bits]
    with AsBundle[Bits]
    with AsRecord[Bits]
    with AsVec[Bits]
    with Not[Bits, Bits]
    with AndR[Bits, Bool]
    with OrR[Bits, Bool]
    with XorR[Bits, Bool]
    with Eq[Bits, Bool]
    with Neq[Bits, Bool]
    with And[Bits, Bits]
    with Or[Bits, Bits]
    with Xor[Bits, Bits]
    with Cat[Bits]
    with Shl[Bits, Bits]
    with Shr[Bits, Bits]
    with Head[Bits, Bits]
    with Tail[Bits, Bits]
    with Pad[Bits, Bits]
    with ExtractElement[Bits, Bool]
    with ExtractRange[Bits, Bits]

trait BoolApi
    extends AsBits[Bool]
    with Neg[Bool, Bool]
    with Eq[Bool, Bool]
    with Neq[Bool, Bool]
    with And[Bool, Bool]
    with Or[Bool, Bool]
    with Xor[Bool, Bool]
    with Mux[Bool]
trait UIntApi
    extends AsBits[UInt]
    with Add[UInt, UInt]
    with Sub[UInt, UInt]
    with Mul[UInt, UInt]
    with Div[UInt, UInt]
    with Rem[UInt, UInt]
    with Lt[UInt, Bool]
    with Leq[UInt, Bool]
    with Gt[UInt, Bool]
    with Geq[UInt, Bool]
    with Eq[UInt, Bool]
    with Neq[UInt, Bool]
    with Shl[UInt, UInt]
    with Shr[UInt, UInt]
trait SIntApi
    extends AsBits[SInt]
    with Add[SInt, SInt]
    with Sub[SInt, SInt]
    with Mul[SInt, SInt]
    with Div[SInt, SInt]
    with Rem[SInt, SInt]
    with Lt[SInt, Bool]
    with Leq[SInt, Bool]
    with Gt[SInt, Bool]
    with Geq[SInt, Bool]
    with Neq[SInt, Bool]
    with Shl[SInt, SInt]
    with Shr[SInt, SInt]

trait BundleApi[T <: Bundle | ProbeBundle] extends AsBits[T]

trait RecordApi[T <: Record | ProbeRecord] extends AsBits[T]

trait VecApi[E <: Data, V <: Vec[E]] extends AsBits[V] with RefElement[V, E] with GetLength[E, V]

trait ClockApi

trait ResetApi extends AsBool[Reset]

type ContractTuple[A <: Tuple] <: Tuple = A match
  case EmptyTuple           => EmptyTuple
  case Referable[t] *: tail => (Referable[t] & HasOperation) *: ContractTuple[tail]

trait ContractTupleArgs[A <: Tuple]:
  def values(args:    A):                                        Seq[Referable[? <: Data] & HasOperation]
  def results(values: Seq[Referable[? <: Data] & HasOperation]): ContractTuple[A]

object ContractTupleArgs:
  given empty: ContractTupleArgs[EmptyTuple] with
    def values(args: EmptyTuple):                                  Seq[Referable[? <: Data] & HasOperation] = Seq.empty
    def results(values: Seq[Referable[? <: Data] & HasOperation]): EmptyTuple                               =
      EmptyTuple

  given cons[T <: Data, H <: Referable[T] & HasOperation, Tail <: Tuple](
    using tailArgs: ContractTupleArgs[Tail]
  ): ContractTupleArgs[H *: Tail] with
    def values(args: H *: Tail): Seq[Referable[? <: Data] & HasOperation] =
      args.head +: tailArgs.values(args.tail)

    def results(values: Seq[Referable[? <: Data] & HasOperation]): ContractTuple[H *: Tail] =
      (values.head *: tailArgs.results(values.tail)).asInstanceOf[ContractTuple[H *: Tail]]

trait ContractApi:
  def Contract(
    body: => Unit
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    TypeImpl
  ): Unit

  def Contract[T <: Data](
    arg:  Referable[T] & HasOperation
  )(body: (Referable[T] & HasOperation) => (Arena, Context, Block) ?=> Unit
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    TypeImpl
  ): Referable[T] & HasOperation

  def Contract[A <: Tuple](
    args: A
  )(body: ContractTuple[A] => (Arena, Context, Block) ?=> Unit
  )(
    using ContractTupleArgs[A]
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    TypeImpl
  ): ContractTuple[A]

  def Require(
    property: Immediate | Sequence | Property,
    label:    Option[String] = None
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    TypeImpl
  ): Unit

  def Ensure(
    property: Immediate | Sequence | Property,
    label:    Option[String] = None
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    TypeImpl
  ): Unit

trait SVAApi:
  def posedge(clock: Referable[Clock] & HasOperation): ClockEvent
  def negedge(clock: Referable[Clock] & HasOperation): ClockEvent
  def anyedge(clock: Referable[Clock] & HasOperation): ClockEvent

  /** SVA: always p
    */
  def always(
    property: Immediate | Sequence | Property
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ): Property

  /** SVA: s_eventually p
    */
  def eventually(
    property: Immediate | Sequence | Property
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ): Property

  extension [T <: Referable[Bool] & HasOperation](ref: T)
    def S(
      using ClockEvent
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    def I(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Immediate

    /** SVA: bool_expr throughout s
      */
    infix def throughout(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

  extension (ref: Immediate)
    /** SVA: not p
      *
      * This is property negation. CIRCT's `ltl.not` accepts any property-like operand and always produces
      * `!ltl.property`.
      */
    def unary_!(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 and p2
      */
    def &(
      that: Immediate
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Immediate
    def &(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence
    def &(
      that: Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s1 intersect s2
      */
    infix def intersect(
      that: Immediate
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Immediate
    infix def intersect(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence
    infix def intersect(
      that: Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s1 or s2
      */
    def |(
      that: Immediate
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Immediate
    def |(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence
    def |(
      that: Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s|->p
      */
    def |->(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s #-# p
      */
    def #-#(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 implies p2
      */
    infix def implies(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 iff p2
      */
    infix def iff(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 until p2
      */
    infix def until(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 until_with p2
      */
    infix def untilWith(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

  extension (ref: Sequence)
    /** SVA: not p
      *
      * This is property negation. CIRCT's `ltl.not` accepts any property-like operand and always produces
      * `!ltl.property`.
      */
    def unary_!(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: a ## b, shorthand for a ##0 b.
      */
    def ##(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: a ### b, shorthand for a ##1 b.
      */
    def ###(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: a ##n b
      */
    def ##(
      n:    Int
    )(that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: a ##[min:max] b
      */
    def ##(
      min:  Int,
      max:  Option[Int]
    )(that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: s [*n]
      */
    def *(
      n: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** Ranged Repeat
      * @param min
      *   for minimal
      * @param max
      *   is [[None]] for unbounded, otherwise for maximal
      *
      * SVA: s [*n:$] if `max` is [[None]], s [*n:m] if `max` is [[Some]]
      */
    def *(
      min: Int,
      max: Option[Int]
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: s [->n:m]
      */
    def *->(
      min: Int,
      max: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: s[=min:max]
      */
    def *=(
      min: Int,
      max: Int
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: s1 ##[+] s2
      */
    def ##+(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: s1 ##[*] s2
      */
    def ##*(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: s1 within s2
      */
    infix def within(
      that: Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence

    /** SVA: s|=>p
      */
    def |=>(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s #=# p
      */
    def #=#(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 and p2
      */
    def &(
      that: Immediate | Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence
    def &(
      that: Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s1 intersect s2
      */
    infix def intersect(
      that: Immediate | Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence
    infix def intersect(
      that: Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s1 or s2
      */
    def |(
      that: Immediate | Sequence
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Sequence
    def |(
      that: Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s|->p
      */
    def |->(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: s #-# p
      */
    def #-#(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 implies p2
      */
    infix def implies(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 iff p2
      */
    infix def iff(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 until p2
      */
    infix def until(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 until_with p2
      */
    infix def untilWith(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

  extension (ref: Property)
    /** SVA: not p
      *
      * This is property negation. CIRCT's `ltl.not` accepts any property-like operand and always produces
      * `!ltl.property`.
      */
    def unary_!(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 and p2
      */
    def &(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 intersect p2
      */
    infix def intersect(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 or p2
      */
    def |(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 implies p2
      */
    infix def implies(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 iff p2
      */
    infix def iff(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 until p2
      */
    infix def until(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

    /** SVA: p1 until_with p2
      */
    infix def untilWith(
      that: Immediate | Sequence | Property
    )(
      using Arena,
      Context,
      Block,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine,
      InstanceContext
    ): Property

  def Assert(
    property: Immediate | Sequence | Property
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ): Unit
  def Assume(
    property: Immediate | Sequence | Property
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ): Unit
  def Cover(
    property: Immediate | Sequence | Property
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ): Unit
  def Assert(
    property: Immediate | Sequence | Property,
    label:    String
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ): Unit
  def Assume(
    property: Immediate | Sequence | Property,
    label:    String
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ): Unit
  def Cover(
    property: Immediate | Sequence | Property,
    label:    String
  )(
    using Arena,
    Context,
    Block,
    sourcecode.File,
    sourcecode.Line,
    sourcecode.Name.Machine,
    InstanceContext
  ): Unit

trait TypeImpl:
  extension (ref: Interface[?])
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
  extension (ref: Wire[?])
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
  extension (ref: Reg[?])
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
  extension (ref: Node[?])
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
  extension (ref: Ref[?])
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
  extension (ref: Const[?])
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
  extension (ref: Instance[?, ?])
    private[zaozi] def operationImpl:        Operation
    private[zaozi] def ioImpl[T <: Data]:    Wire[T]
    private[zaozi] def probeImpl[T <: Data]: Wire[T]
  extension (ref: Sequence)
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):                                Type
  extension (ref: Property)
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):                                Type
  extension (ref: Immediate)
    private[zaozi] def operationImpl: Operation
    private[zaozi] def referImpl(
      using Arena
    ):                                Value
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):                                Type

  extension (ref:  Reset)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):  Type
  extension (ref:  Clock)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):  Type
  extension (ref:  UInt)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):  Type
  extension (ref:  SInt)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):  Type
  extension (ref:  Bits)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):  Type
  extension (ref:  Analog)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):  Type
  extension (ref:  Bool)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):  Type
  extension (ref:  ProbeBundle)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ): Type
    private[zaozi] def ReadProbeImpl[T <: Data & CanProbe](
      tpe:   T,
      layer: LayerTree
    )(
      using sourcecode.Name.Machine
    ): BundleField[RProbe[T]]
    private[zaozi] def ReadWriteProbeImpl[T <: Data & CanProbe](
      tpe:   T,
      layer: LayerTree
    )(
      using sourcecode.Name.Machine
    ): BundleField[RWProbe[T]]
  extension (ref:  Bundle)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ): Type
    private[zaozi] def FlippedImpl[T <: Data](
      tpe: T
    )(
      using sourcecode.Name.Machine
    ): BundleField[T]
    private[zaozi] def AlignedImpl[T <: Data](
      tpe: T
    )(
      using sourcecode.Name.Machine
    ): BundleField[T]
  extension (ref:  Aggregate)
    /** Declared fields of a materialized type, in declaration order, as a read-only snapshot. Type-level introspection
      * only: value-level dynamic access still goes through the `asRecord` view.
      */
    def elements: Seq[BundleField[?]]
  extension (ref:  ProbeRecord)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):            Type
    private[zaozi] def ReadProbeImpl[T <: Data & CanProbe](
      name:  String,
      tpe:   T,
      layer: LayerTree
    ):            BundleField[RProbe[T]]
    private[zaozi] def ReadWriteProbeImpl[T <: Data & CanProbe](
      name:  String,
      tpe:   T,
      layer: LayerTree
    ):            BundleField[RWProbe[T]]
  extension (ref:  Record)
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ):            Type
    private[zaozi] def FlippedImpl[T <: Data](
      name: String,
      tpe:  T
    ):            BundleField[T]
    private[zaozi] def AlignedImpl[T <: Data](
      name: String,
      tpe:  T
    ):            BundleField[T]
  extension (ref:  RProbe[?])
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context,
      TypeImpl
    ):  Type
  extension (ref:  RWProbe[?])
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context,
      TypeImpl
    ):  Type
  extension (data: Data)
    private[zaozi] def widthImpl(
      using Arena,
      Context
    ):  Int
  extension (ref:  Vec[?])
    private[zaozi] def countImpl(
      using Arena,
      Context
    ): Int
    private[zaozi] def toMlirTypeImpl(
      using Arena,
      Context
    ): Type
  extension (ref:  ProbeBundle)
    private[zaozi] def getRefViaFieldValNameImpl[E <: Data](
      refer:        Value,
      fieldValName: String
    )(
      using Arena,
      Block,
      Context,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine
    )(
      using TypeImpl
    ): Ref[E]
    private[zaozi] def getOptionRefViaFieldValNameImpl[E <: Data](
      refer:        Value,
      fieldValName: String
    )(
      using Arena,
      Block,
      Context,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine
    )(
      using TypeImpl
    ): Option[Ref[E]]
  extension (ref:  Bundle)
    private[zaozi] def getRefViaFieldValNameImpl[E <: Data](
      refer:        Value,
      fieldValName: String
    )(
      using Arena,
      Block,
      Context,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine
    )(
      using TypeImpl
    ): Ref[E]
    private[zaozi] def getOptionRefViaFieldValNameImpl[E <: Data](
      refer:        Value,
      fieldValName: String
    )(
      using Arena,
      Block,
      Context,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine
    )(
      using TypeImpl
    ): Option[Ref[E]]

  extension (ref: ProbeRecord)
    private[zaozi] def getUntypedRefViaFieldValNameImpl(
      refer:        Value,
      fieldValName: String
    )(
      using Arena,
      Block,
      Context,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine
    )(
      using TypeImpl
    ): Ref[Data]

  extension (ref: Record)
    private[zaozi] def getUntypedRefViaFieldValNameImpl(
      refer:        Value,
      fieldValName: String
    )(
      using Arena,
      Block,
      Context,
      sourcecode.File,
      sourcecode.Line,
      sourcecode.Name.Machine
    )(
      using TypeImpl
    ): Ref[Data]
