#!/usr/bin/env python3
"""
wrap_dsl.py — Wrap asm2dsl.py output into a runnable Scala main class.

Reads DSL lines from stdin, wraps them into an RVGenerator with @main entry point.

Usage:
    python3 asm2dsl.py < input.S | python3 wrap_dsl.py --name MyGen > MyGen.scala
"""

import sys
import argparse


TEMPLATE = '''\
// Auto-generated by wrap_dsl.py — do not edit
package me.jiuyang.rvprobe.cases.probes

import me.jiuyang.smtlib.default.{{*, given}}
import me.jiuyang.rvprobe.*
import me.jiuyang.rvprobe.Register.*
import me.jiuyang.rvprobe.constraints.{{*, given}}

@main def {name}(outputPath: String): Unit =
  object {name} extends RVGenerator:
    val sets = isRV64GC() ++ Seq(isRVFZFA(), isRVZICSR(), isRVSYSTEM(), isRVS())

    def constraints() =
{body}
  {name}.emit(outputPath)
'''


def main():
    parser = argparse.ArgumentParser(
        description="Wrap asm2dsl output into a runnable Scala main class"
    )
    parser.add_argument(
        "--name", required=True,
        help="Class/object name for the generated Scala file"
    )
    args = parser.parse_args()

    dsl_lines = sys.stdin.read().splitlines()

    # Indent each DSL line by 6 spaces (inside constraints() body)
    body_lines = []
    for line in dsl_lines:
        if line.strip():
            body_lines.append(f"      {line}")
        else:
            body_lines.append("")

    body = "\n".join(body_lines)
    output = TEMPLATE.format(name=args.name, body=body)
    sys.stdout.write(output)


if __name__ == "__main__":
    main()
