// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator. Do not edit by hand.
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** Aggregate registry of all RvvInsn declarations across all upstream extensions. */
object AllInsns:
  val all: List[RvvInsn] =
    V.all ++
    Zvbb.all ++
    Zvbc.all ++
    Zvfbfmin.all ++
    Zvfbfwma.all ++
    Zvfhmin.all ++
    Zvkg.all ++
    Zvkned.all ++
    Zvknha.all ++
    Zvksed.all ++
    Zvksh.all
