// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/v/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** Aggregator for extension `v` (7 chunks). */
object V:
  val all: List[RvvInsn] =
    V0.chunkAll ++
    V1.chunkAll ++
    V2.chunkAll ++
    V3.chunkAll ++
    V4.chunkAll ++
    V5.chunkAll ++
    V6.chunkAll
