// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/v/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.eew.OperandWidthProfile
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 100 RvvInsn declarations for `v` (chunk 0). */
object V0:
  // vaadd.vv  (format: vd,vs2,vs1,vm)
  val `vaadd_vv`: RvvInsn = RvvInsn(
    name       = "vaadd.vv",
    extension  = "v",
    sourceToml = "v/vaadd.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true)

  // vaadd.vx  (format: vd,vs2,rs1,vm)
  val `vaadd_vx`: RvvInsn = RvvInsn(
    name       = "vaadd.vx",
    extension  = "v",
    sourceToml = "v/vaadd.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true)

  // vaaddu.vv  (format: vd,vs2,vs1,vm)
  val `vaaddu_vv`: RvvInsn = RvvInsn(
    name       = "vaaddu.vv",
    extension  = "v",
    sourceToml = "v/vaaddu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true)

  // vaaddu.vx  (format: vd,vs2,rs1,vm)
  val `vaaddu_vx`: RvvInsn = RvvInsn(
    name       = "vaaddu.vx",
    extension  = "v",
    sourceToml = "v/vaaddu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true)

  // vadc.vim  (format: vd,vs2,imm,v0)
  val `vadc_vim`: RvvInsn = RvvInsn(
    name       = "vadc.vim",
    extension  = "v",
    sourceToml = "v/vadc.vim.toml",
    schema     = Schema.VdVs2ImmV0)

  // vadc.vvm  (format: vd,vs2,vs1,v0)
  val `vadc_vvm`: RvvInsn = RvvInsn(
    name       = "vadc.vvm",
    extension  = "v",
    sourceToml = "v/vadc.vvm.toml",
    schema     = Schema.VdVs2Vs1V0)

  // vadc.vxm  (format: vd,vs2,rs1,v0)
  val `vadc_vxm`: RvvInsn = RvvInsn(
    name       = "vadc.vxm",
    extension  = "v",
    sourceToml = "v/vadc.vxm.toml",
    schema     = Schema.VdVs2Rs1V0)

  // vadd.vi  (format: vd,vs2,imm,vm)
  val `vadd_vi`: RvvInsn = RvvInsn(
    name       = "vadd.vi",
    extension  = "v",
    sourceToml = "v/vadd.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vadd.vv  (format: vd,vs2,vs1,vm)
  val `vadd_vv`: RvvInsn = RvvInsn(
    name       = "vadd.vv",
    extension  = "v",
    sourceToml = "v/vadd.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vadd.vx  (format: vd,vs2,rs1,vm)
  val `vadd_vx`: RvvInsn = RvvInsn(
    name       = "vadd.vx",
    extension  = "v",
    sourceToml = "v/vadd.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vand.vi  (format: vd,vs2,imm,vm)
  val `vand_vi`: RvvInsn = RvvInsn(
    name       = "vand.vi",
    extension  = "v",
    sourceToml = "v/vand.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vand.vv  (format: vd,vs2,vs1,vm)
  val `vand_vv`: RvvInsn = RvvInsn(
    name       = "vand.vv",
    extension  = "v",
    sourceToml = "v/vand.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vand.vx  (format: vd,vs2,rs1,vm)
  val `vand_vx`: RvvInsn = RvvInsn(
    name       = "vand.vx",
    extension  = "v",
    sourceToml = "v/vand.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vasub.vv  (format: vd,vs2,vs1,vm)
  val `vasub_vv`: RvvInsn = RvvInsn(
    name       = "vasub.vv",
    extension  = "v",
    sourceToml = "v/vasub.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true)

  // vasub.vx  (format: vd,vs2,rs1,vm)
  val `vasub_vx`: RvvInsn = RvvInsn(
    name       = "vasub.vx",
    extension  = "v",
    sourceToml = "v/vasub.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true)

  // vasubu.vv  (format: vd,vs2,vs1,vm)
  val `vasubu_vv`: RvvInsn = RvvInsn(
    name       = "vasubu.vv",
    extension  = "v",
    sourceToml = "v/vasubu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true)

  // vasubu.vx  (format: vd,vs2,rs1,vm)
  val `vasubu_vx`: RvvInsn = RvvInsn(
    name       = "vasubu.vx",
    extension  = "v",
    sourceToml = "v/vasubu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true)

  // vcompress.vm  (format: vd,vs2,vs1)
  val `vcompress_vm`: RvvInsn = RvvInsn(
    name       = "vcompress.vm",
    extension  = "v",
    sourceToml = "v/vcompress.vm.toml",
    schema     = Schema.VdVs2Vs1)

  // vcpop.m  (format: rd,vs2,vm)
  val `vcpop_m`: RvvInsn = RvvInsn(
    name       = "vcpop.m",
    extension  = "v",
    sourceToml = "v/vcpop.m.toml",
    schema     = Schema.RdVs2Vm)

  // vdiv.vv  (format: vd,vs2,vs1,vm)
  val `vdiv_vv`: RvvInsn = RvvInsn(
    name       = "vdiv.vv",
    extension  = "v",
    sourceToml = "v/vdiv.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vdiv.vx  (format: vd,vs2,rs1,vm)
  val `vdiv_vx`: RvvInsn = RvvInsn(
    name       = "vdiv.vx",
    extension  = "v",
    sourceToml = "v/vdiv.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vdivu.vv  (format: vd,vs2,vs1,vm)
  val `vdivu_vv`: RvvInsn = RvvInsn(
    name       = "vdivu.vv",
    extension  = "v",
    sourceToml = "v/vdivu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vdivu.vx  (format: vd,vs2,rs1,vm)
  val `vdivu_vx`: RvvInsn = RvvInsn(
    name       = "vdivu.vx",
    extension  = "v",
    sourceToml = "v/vdivu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vfadd.vf  (format: vd,vs2,fs1,vm)
  val `vfadd_vf`: RvvInsn = RvvInsn(
    name       = "vfadd.vf",
    extension  = "v",
    sourceToml = "v/vfadd.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfadd.vv  (format: vd,vs2,vs1,vm)
  val `vfadd_vv`: RvvInsn = RvvInsn(
    name       = "vfadd.vv",
    extension  = "v",
    sourceToml = "v/vfadd.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfclass.v  (format: vd,vs2,vm)
  val `vfclass_v`: RvvInsn = RvvInsn(
    name       = "vfclass.v",
    extension  = "v",
    sourceToml = "v/vfclass.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfcvt.f.x.v  (format: vd,vs2,vm)
  val `vfcvt_f_x_v`: RvvInsn = RvvInsn(
    name       = "vfcvt.f.x.v",
    extension  = "v",
    sourceToml = "v/vfcvt.f.x.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfcvt.f.xu.v  (format: vd,vs2,vm)
  val `vfcvt_f_xu_v`: RvvInsn = RvvInsn(
    name       = "vfcvt.f.xu.v",
    extension  = "v",
    sourceToml = "v/vfcvt.f.xu.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfcvt.rtz.x.f.v  (format: vd,vs2,vm)
  val `vfcvt_rtz_x_f_v`: RvvInsn = RvvInsn(
    name       = "vfcvt.rtz.x.f.v",
    extension  = "v",
    sourceToml = "v/vfcvt.rtz.x.f.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfcvt.rtz.xu.f.v  (format: vd,vs2,vm)
  val `vfcvt_rtz_xu_f_v`: RvvInsn = RvvInsn(
    name       = "vfcvt.rtz.xu.f.v",
    extension  = "v",
    sourceToml = "v/vfcvt.rtz.xu.f.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfcvt.x.f.v  (format: vd,vs2,vm)
  val `vfcvt_x_f_v`: RvvInsn = RvvInsn(
    name       = "vfcvt.x.f.v",
    extension  = "v",
    sourceToml = "v/vfcvt.x.f.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfcvt.xu.f.v  (format: vd,vs2,vm)
  val `vfcvt_xu_f_v`: RvvInsn = RvvInsn(
    name       = "vfcvt.xu.f.v",
    extension  = "v",
    sourceToml = "v/vfcvt.xu.f.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfdiv.vf  (format: vd,vs2,fs1,vm)
  val `vfdiv_vf`: RvvInsn = RvvInsn(
    name       = "vfdiv.vf",
    extension  = "v",
    sourceToml = "v/vfdiv.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfdiv.vv  (format: vd,vs2,vs1,vm)
  val `vfdiv_vv`: RvvInsn = RvvInsn(
    name       = "vfdiv.vv",
    extension  = "v",
    sourceToml = "v/vfdiv.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfirst.m  (format: rd,vs2,vm)
  val `vfirst_m`: RvvInsn = RvvInsn(
    name       = "vfirst.m",
    extension  = "v",
    sourceToml = "v/vfirst.m.toml",
    schema     = Schema.RdVs2Vm)

  // vfmacc.vf  (format: vd,fs1,vs2,vm)
  val `vfmacc_vf`: RvvInsn = RvvInsn(
    name       = "vfmacc.vf",
    extension  = "v",
    sourceToml = "v/vfmacc.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfmacc.vv  (format: vd,vs1,vs2,vm)
  val `vfmacc_vv`: RvvInsn = RvvInsn(
    name       = "vfmacc.vv",
    extension  = "v",
    sourceToml = "v/vfmacc.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vfmadd.vf  (format: vd,fs1,vs2,vm)
  val `vfmadd_vf`: RvvInsn = RvvInsn(
    name       = "vfmadd.vf",
    extension  = "v",
    sourceToml = "v/vfmadd.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfmadd.vv  (format: vd,vs1,vs2,vm)
  val `vfmadd_vv`: RvvInsn = RvvInsn(
    name       = "vfmadd.vv",
    extension  = "v",
    sourceToml = "v/vfmadd.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vfmax.vf  (format: vd,vs2,fs1,vm)
  val `vfmax_vf`: RvvInsn = RvvInsn(
    name       = "vfmax.vf",
    extension  = "v",
    sourceToml = "v/vfmax.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfmax.vv  (format: vd,vs2,vs1,vm)
  val `vfmax_vv`: RvvInsn = RvvInsn(
    name       = "vfmax.vv",
    extension  = "v",
    sourceToml = "v/vfmax.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfmerge.vfm  (format: vd,vs2,fs1,v0)
  val `vfmerge_vfm`: RvvInsn = RvvInsn(
    name       = "vfmerge.vfm",
    extension  = "v",
    sourceToml = "v/vfmerge.vfm.toml",
    schema     = Schema.VdVs2Fs1V0)

  // vfmin.vf  (format: vd,vs2,fs1,vm)
  val `vfmin_vf`: RvvInsn = RvvInsn(
    name       = "vfmin.vf",
    extension  = "v",
    sourceToml = "v/vfmin.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfmin.vv  (format: vd,vs2,vs1,vm)
  val `vfmin_vv`: RvvInsn = RvvInsn(
    name       = "vfmin.vv",
    extension  = "v",
    sourceToml = "v/vfmin.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfmsac.vf  (format: vd,fs1,vs2,vm)
  val `vfmsac_vf`: RvvInsn = RvvInsn(
    name       = "vfmsac.vf",
    extension  = "v",
    sourceToml = "v/vfmsac.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfmsac.vv  (format: vd,vs1,vs2,vm)
  val `vfmsac_vv`: RvvInsn = RvvInsn(
    name       = "vfmsac.vv",
    extension  = "v",
    sourceToml = "v/vfmsac.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vfmsub.vf  (format: vd,fs1,vs2,vm)
  val `vfmsub_vf`: RvvInsn = RvvInsn(
    name       = "vfmsub.vf",
    extension  = "v",
    sourceToml = "v/vfmsub.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfmsub.vv  (format: vd,vs1,vs2,vm)
  val `vfmsub_vv`: RvvInsn = RvvInsn(
    name       = "vfmsub.vv",
    extension  = "v",
    sourceToml = "v/vfmsub.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vfmul.vf  (format: vd,vs2,fs1,vm)
  val `vfmul_vf`: RvvInsn = RvvInsn(
    name       = "vfmul.vf",
    extension  = "v",
    sourceToml = "v/vfmul.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfmul.vv  (format: vd,vs2,vs1,vm)
  val `vfmul_vv`: RvvInsn = RvvInsn(
    name       = "vfmul.vv",
    extension  = "v",
    sourceToml = "v/vfmul.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfmv.f.s  (format: fd,vs2)
  val `vfmv_f_s`: RvvInsn = RvvInsn(
    name       = "vfmv.f.s",
    extension  = "v",
    sourceToml = "v/vfmv.f.s.toml",
    schema     = Schema.FdVs2)

  // vfmv.s.f  (format: vd,fs1)
  val `vfmv_s_f`: RvvInsn = RvvInsn(
    name       = "vfmv.s.f",
    extension  = "v",
    sourceToml = "v/vfmv.s.f.toml",
    schema     = Schema.VdFs1)

  // vfmv.v.f  (format: vd,fs1)
  val `vfmv_v_f`: RvvInsn = RvvInsn(
    name       = "vfmv.v.f",
    extension  = "v",
    sourceToml = "v/vfmv.v.f.toml",
    schema     = Schema.VdFs1)

  // vfncvt.f.f.w  (format: vd,vs2,vm)
  val `vfncvt_f_f_w`: RvvInsn = RvvInsn(
    name       = "vfncvt.f.f.w",
    extension  = "v",
    sourceToml = "v/vfncvt.f.f.w.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfncvt.f.x.w  (format: vd,vs2,vm)
  val `vfncvt_f_x_w`: RvvInsn = RvvInsn(
    name       = "vfncvt.f.x.w",
    extension  = "v",
    sourceToml = "v/vfncvt.f.x.w.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfncvt.f.xu.w  (format: vd,vs2,vm)
  val `vfncvt_f_xu_w`: RvvInsn = RvvInsn(
    name       = "vfncvt.f.xu.w",
    extension  = "v",
    sourceToml = "v/vfncvt.f.xu.w.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfncvt.rod.f.f.w  (format: vd,vs2,vm)
  val `vfncvt_rod_f_f_w`: RvvInsn = RvvInsn(
    name       = "vfncvt.rod.f.f.w",
    extension  = "v",
    sourceToml = "v/vfncvt.rod.f.f.w.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfncvt.rtz.x.f.w  (format: vd,vs2,vm)
  val `vfncvt_rtz_x_f_w`: RvvInsn = RvvInsn(
    name       = "vfncvt.rtz.x.f.w",
    extension  = "v",
    sourceToml = "v/vfncvt.rtz.x.f.w.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfncvt.rtz.xu.f.w  (format: vd,vs2,vm)
  val `vfncvt_rtz_xu_f_w`: RvvInsn = RvvInsn(
    name       = "vfncvt.rtz.xu.f.w",
    extension  = "v",
    sourceToml = "v/vfncvt.rtz.xu.f.w.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfncvt.x.f.w  (format: vd,vs2,vm)
  val `vfncvt_x_f_w`: RvvInsn = RvvInsn(
    name       = "vfncvt.x.f.w",
    extension  = "v",
    sourceToml = "v/vfncvt.x.f.w.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfncvt.xu.f.w  (format: vd,vs2,vm)
  val `vfncvt_xu_f_w`: RvvInsn = RvvInsn(
    name       = "vfncvt.xu.f.w",
    extension  = "v",
    sourceToml = "v/vfncvt.xu.f.w.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfnmacc.vf  (format: vd,fs1,vs2,vm)
  val `vfnmacc_vf`: RvvInsn = RvvInsn(
    name       = "vfnmacc.vf",
    extension  = "v",
    sourceToml = "v/vfnmacc.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfnmacc.vv  (format: vd,vs1,vs2,vm)
  val `vfnmacc_vv`: RvvInsn = RvvInsn(
    name       = "vfnmacc.vv",
    extension  = "v",
    sourceToml = "v/vfnmacc.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vfnmadd.vf  (format: vd,fs1,vs2,vm)
  val `vfnmadd_vf`: RvvInsn = RvvInsn(
    name       = "vfnmadd.vf",
    extension  = "v",
    sourceToml = "v/vfnmadd.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfnmadd.vv  (format: vd,vs1,vs2,vm)
  val `vfnmadd_vv`: RvvInsn = RvvInsn(
    name       = "vfnmadd.vv",
    extension  = "v",
    sourceToml = "v/vfnmadd.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vfnmsac.vf  (format: vd,fs1,vs2,vm)
  val `vfnmsac_vf`: RvvInsn = RvvInsn(
    name       = "vfnmsac.vf",
    extension  = "v",
    sourceToml = "v/vfnmsac.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfnmsac.vv  (format: vd,vs1,vs2,vm)
  val `vfnmsac_vv`: RvvInsn = RvvInsn(
    name       = "vfnmsac.vv",
    extension  = "v",
    sourceToml = "v/vfnmsac.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vfnmsub.vf  (format: vd,fs1,vs2,vm)
  val `vfnmsub_vf`: RvvInsn = RvvInsn(
    name       = "vfnmsub.vf",
    extension  = "v",
    sourceToml = "v/vfnmsub.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfnmsub.vv  (format: vd,vs1,vs2,vm)
  val `vfnmsub_vv`: RvvInsn = RvvInsn(
    name       = "vfnmsub.vv",
    extension  = "v",
    sourceToml = "v/vfnmsub.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vfrdiv.vf  (format: vd,vs2,fs1,vm)
  val `vfrdiv_vf`: RvvInsn = RvvInsn(
    name       = "vfrdiv.vf",
    extension  = "v",
    sourceToml = "v/vfrdiv.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfrec7.v  (format: vd,vs2,vm)
  val `vfrec7_v`: RvvInsn = RvvInsn(
    name       = "vfrec7.v",
    extension  = "v",
    sourceToml = "v/vfrec7.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfredmax.vs  (format: vd,vs2,vs1,vm)
  val `vfredmax_vs`: RvvInsn = RvvInsn(
    name       = "vfredmax.vs",
    extension  = "v",
    sourceToml = "v/vfredmax.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfredmin.vs  (format: vd,vs2,vs1,vm)
  val `vfredmin_vs`: RvvInsn = RvvInsn(
    name       = "vfredmin.vs",
    extension  = "v",
    sourceToml = "v/vfredmin.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfredosum.vs  (format: vd,vs2,vs1,vm)
  val `vfredosum_vs`: RvvInsn = RvvInsn(
    name       = "vfredosum.vs",
    extension  = "v",
    sourceToml = "v/vfredosum.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfredusum.vs  (format: vd,vs2,vs1,vm)
  val `vfredusum_vs`: RvvInsn = RvvInsn(
    name       = "vfredusum.vs",
    extension  = "v",
    sourceToml = "v/vfredusum.vs.toml",
    schema     = Schema.VdVs2Vs1Vm,
    notestfloat3 = true)

  // vfrsqrt7.v  (format: vd,vs2,vm)
  val `vfrsqrt7_v`: RvvInsn = RvvInsn(
    name       = "vfrsqrt7.v",
    extension  = "v",
    sourceToml = "v/vfrsqrt7.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfrsub.vf  (format: vd,vs2,fs1,vm)
  val `vfrsub_vf`: RvvInsn = RvvInsn(
    name       = "vfrsub.vf",
    extension  = "v",
    sourceToml = "v/vfrsub.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfsgnj.vf  (format: vd,vs2,fs1,vm)
  val `vfsgnj_vf`: RvvInsn = RvvInsn(
    name       = "vfsgnj.vf",
    extension  = "v",
    sourceToml = "v/vfsgnj.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfsgnj.vv  (format: vd,vs2,vs1,vm)
  val `vfsgnj_vv`: RvvInsn = RvvInsn(
    name       = "vfsgnj.vv",
    extension  = "v",
    sourceToml = "v/vfsgnj.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfsgnjn.vf  (format: vd,vs2,fs1,vm)
  val `vfsgnjn_vf`: RvvInsn = RvvInsn(
    name       = "vfsgnjn.vf",
    extension  = "v",
    sourceToml = "v/vfsgnjn.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfsgnjn.vv  (format: vd,vs2,vs1,vm)
  val `vfsgnjn_vv`: RvvInsn = RvvInsn(
    name       = "vfsgnjn.vv",
    extension  = "v",
    sourceToml = "v/vfsgnjn.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfsgnjx.vf  (format: vd,vs2,fs1,vm)
  val `vfsgnjx_vf`: RvvInsn = RvvInsn(
    name       = "vfsgnjx.vf",
    extension  = "v",
    sourceToml = "v/vfsgnjx.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfsgnjx.vv  (format: vd,vs2,vs1,vm)
  val `vfsgnjx_vv`: RvvInsn = RvvInsn(
    name       = "vfsgnjx.vv",
    extension  = "v",
    sourceToml = "v/vfsgnjx.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfslide1down.vf  (format: vd,vs2,fs1,vm)
  val `vfslide1down_vf`: RvvInsn = RvvInsn(
    name       = "vfslide1down.vf",
    extension  = "v",
    sourceToml = "v/vfslide1down.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfslide1up.vf  (format: vd,vs2,fs1,vm)
  val `vfslide1up_vf`: RvvInsn = RvvInsn(
    name       = "vfslide1up.vf",
    extension  = "v",
    sourceToml = "v/vfslide1up.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfsqrt.v  (format: vd,vs2,vm)
  val `vfsqrt_v`: RvvInsn = RvvInsn(
    name       = "vfsqrt.v",
    extension  = "v",
    sourceToml = "v/vfsqrt.v.toml",
    schema     = Schema.VdVs2Vm)

  // vfsub.vf  (format: vd,vs2,fs1,vm)
  val `vfsub_vf`: RvvInsn = RvvInsn(
    name       = "vfsub.vf",
    extension  = "v",
    sourceToml = "v/vfsub.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vfsub.vv  (format: vd,vs2,vs1,vm)
  val `vfsub_vv`: RvvInsn = RvvInsn(
    name       = "vfsub.vv",
    extension  = "v",
    sourceToml = "v/vfsub.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfwadd.vf  (format: vd,vs2,fs1,vm)
  val `vfwadd_vf`: RvvInsn = RvvInsn(
    name       = "vfwadd.vf",
    extension  = "v",
    sourceToml = "v/vfwadd.vf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Fs1Vm)

  // vfwadd.vv  (format: vd,vs2,vs1,vm)
  val `vfwadd_vv`: RvvInsn = RvvInsn(
    name       = "vfwadd.vv",
    extension  = "v",
    sourceToml = "v/vfwadd.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vfwadd.wf  (format: vd,vs2,fs1,vm)
  val `vfwadd_wf`: RvvInsn = RvvInsn(
    name       = "vfwadd.wf",
    extension  = "v",
    sourceToml = "v/vfwadd.wf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Fs1Vm)

  // vfwadd.wv  (format: vd,vs2,vs1,vm)
  val `vfwadd_wv`: RvvInsn = RvvInsn(
    name       = "vfwadd.wv",
    extension  = "v",
    sourceToml = "v/vfwadd.wv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vfwcvt.f.f.v  (format: vd,vs2,vm)
  val `vfwcvt_f_f_v`: RvvInsn = RvvInsn(
    name       = "vfwcvt.f.f.v",
    extension  = "v",
    sourceToml = "v/vfwcvt.f.f.v.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfwcvt.f.x.v  (format: vd,vs2,vm)
  val `vfwcvt_f_x_v`: RvvInsn = RvvInsn(
    name       = "vfwcvt.f.x.v",
    extension  = "v",
    sourceToml = "v/vfwcvt.f.x.v.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfwcvt.f.xu.v  (format: vd,vs2,vm)
  val `vfwcvt_f_xu_v`: RvvInsn = RvvInsn(
    name       = "vfwcvt.f.xu.v",
    extension  = "v",
    sourceToml = "v/vfwcvt.f.xu.v.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfwcvt.rtz.x.f.v  (format: vd,vs2,vm)
  val `vfwcvt_rtz_x_f_v`: RvvInsn = RvvInsn(
    name       = "vfwcvt.rtz.x.f.v",
    extension  = "v",
    sourceToml = "v/vfwcvt.rtz.x.f.v.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfwcvt.rtz.xu.f.v  (format: vd,vs2,vm)
  val `vfwcvt_rtz_xu_f_v`: RvvInsn = RvvInsn(
    name       = "vfwcvt.rtz.xu.f.v",
    extension  = "v",
    sourceToml = "v/vfwcvt.rtz.xu.f.v.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfwcvt.x.f.v  (format: vd,vs2,vm)
  val `vfwcvt_x_f_v`: RvvInsn = RvvInsn(
    name       = "vfwcvt.x.f.v",
    extension  = "v",
    sourceToml = "v/vfwcvt.x.f.v.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfwcvt.xu.f.v  (format: vd,vs2,vm)
  val `vfwcvt_xu_f_v`: RvvInsn = RvvInsn(
    name       = "vfwcvt.xu.f.v",
    extension  = "v",
    sourceToml = "v/vfwcvt.xu.f.v.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vm)

  // vfwmacc.vf  (format: vd,fs1,vs2,vm)
  val `vfwmacc_vf`: RvvInsn = RvvInsn(
    name       = "vfwmacc.vf",
    extension  = "v",
    sourceToml = "v/vfwmacc.vf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdFs1Vs2Vm)

  val chunkAll: List[RvvInsn] = List(
    `vaadd_vv`,
    `vaadd_vx`,
    `vaaddu_vv`,
    `vaaddu_vx`,
    `vadc_vim`,
    `vadc_vvm`,
    `vadc_vxm`,
    `vadd_vi`,
    `vadd_vv`,
    `vadd_vx`,
    `vand_vi`,
    `vand_vv`,
    `vand_vx`,
    `vasub_vv`,
    `vasub_vx`,
    `vasubu_vv`,
    `vasubu_vx`,
    `vcompress_vm`,
    `vcpop_m`,
    `vdiv_vv`,
    `vdiv_vx`,
    `vdivu_vv`,
    `vdivu_vx`,
    `vfadd_vf`,
    `vfadd_vv`,
    `vfclass_v`,
    `vfcvt_f_x_v`,
    `vfcvt_f_xu_v`,
    `vfcvt_rtz_x_f_v`,
    `vfcvt_rtz_xu_f_v`,
    `vfcvt_x_f_v`,
    `vfcvt_xu_f_v`,
    `vfdiv_vf`,
    `vfdiv_vv`,
    `vfirst_m`,
    `vfmacc_vf`,
    `vfmacc_vv`,
    `vfmadd_vf`,
    `vfmadd_vv`,
    `vfmax_vf`,
    `vfmax_vv`,
    `vfmerge_vfm`,
    `vfmin_vf`,
    `vfmin_vv`,
    `vfmsac_vf`,
    `vfmsac_vv`,
    `vfmsub_vf`,
    `vfmsub_vv`,
    `vfmul_vf`,
    `vfmul_vv`,
    `vfmv_f_s`,
    `vfmv_s_f`,
    `vfmv_v_f`,
    `vfncvt_f_f_w`,
    `vfncvt_f_x_w`,
    `vfncvt_f_xu_w`,
    `vfncvt_rod_f_f_w`,
    `vfncvt_rtz_x_f_w`,
    `vfncvt_rtz_xu_f_w`,
    `vfncvt_x_f_w`,
    `vfncvt_xu_f_w`,
    `vfnmacc_vf`,
    `vfnmacc_vv`,
    `vfnmadd_vf`,
    `vfnmadd_vv`,
    `vfnmsac_vf`,
    `vfnmsac_vv`,
    `vfnmsub_vf`,
    `vfnmsub_vv`,
    `vfrdiv_vf`,
    `vfrec7_v`,
    `vfredmax_vs`,
    `vfredmin_vs`,
    `vfredosum_vs`,
    `vfredusum_vs`,
    `vfrsqrt7_v`,
    `vfrsub_vf`,
    `vfsgnj_vf`,
    `vfsgnj_vv`,
    `vfsgnjn_vf`,
    `vfsgnjn_vv`,
    `vfsgnjx_vf`,
    `vfsgnjx_vv`,
    `vfslide1down_vf`,
    `vfslide1up_vf`,
    `vfsqrt_v`,
    `vfsub_vf`,
    `vfsub_vv`,
    `vfwadd_vf`,
    `vfwadd_vv`,
    `vfwadd_wf`,
    `vfwadd_wv`,
    `vfwcvt_f_f_v`,
    `vfwcvt_f_x_v`,
    `vfwcvt_f_xu_v`,
    `vfwcvt_rtz_x_f_v`,
    `vfwcvt_rtz_xu_f_v`,
    `vfwcvt_x_f_v`,
    `vfwcvt_xu_f_v`,
    `vfwmacc_vf`
  )
