// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/v/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.eew.OperandWidthProfile
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 100 RvvInsn declarations for `v` (chunk 1). */
object V1:
  // vfwmacc.vv  (format: vd,vs1,vs2,vm)
  val `vfwmacc_vv`: RvvInsn = RvvInsn(
    name       = "vfwmacc.vv",
    extension  = "v",
    sourceToml = "v/vfwmacc.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs1Vs2Vm)

  // vfwmsac.vf  (format: vd,fs1,vs2,vm)
  val `vfwmsac_vf`: RvvInsn = RvvInsn(
    name       = "vfwmsac.vf",
    extension  = "v",
    sourceToml = "v/vfwmsac.vf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdFs1Vs2Vm)

  // vfwmsac.vv  (format: vd,vs1,vs2,vm)
  val `vfwmsac_vv`: RvvInsn = RvvInsn(
    name       = "vfwmsac.vv",
    extension  = "v",
    sourceToml = "v/vfwmsac.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs1Vs2Vm)

  // vfwmul.vf  (format: vd,vs2,fs1,vm)
  val `vfwmul_vf`: RvvInsn = RvvInsn(
    name       = "vfwmul.vf",
    extension  = "v",
    sourceToml = "v/vfwmul.vf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Fs1Vm)

  // vfwmul.vv  (format: vd,vs2,vs1,vm)
  val `vfwmul_vv`: RvvInsn = RvvInsn(
    name       = "vfwmul.vv",
    extension  = "v",
    sourceToml = "v/vfwmul.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vfwnmacc.vf  (format: vd,fs1,vs2,vm)
  val `vfwnmacc_vf`: RvvInsn = RvvInsn(
    name       = "vfwnmacc.vf",
    extension  = "v",
    sourceToml = "v/vfwnmacc.vf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdFs1Vs2Vm)

  // vfwnmacc.vv  (format: vd,vs1,vs2,vm)
  val `vfwnmacc_vv`: RvvInsn = RvvInsn(
    name       = "vfwnmacc.vv",
    extension  = "v",
    sourceToml = "v/vfwnmacc.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs1Vs2Vm)

  // vfwnmsac.vf  (format: vd,fs1,vs2,vm)
  val `vfwnmsac_vf`: RvvInsn = RvvInsn(
    name       = "vfwnmsac.vf",
    extension  = "v",
    sourceToml = "v/vfwnmsac.vf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdFs1Vs2Vm)

  // vfwnmsac.vv  (format: vd,vs1,vs2,vm)
  val `vfwnmsac_vv`: RvvInsn = RvvInsn(
    name       = "vfwnmsac.vv",
    extension  = "v",
    sourceToml = "v/vfwnmsac.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs1Vs2Vm)

  // vfwredosum.vs  (format: vd,vs2,vs1,vm)
  val `vfwredosum_vs`: RvvInsn = RvvInsn(
    name       = "vfwredosum.vs",
    extension  = "v",
    sourceToml = "v/vfwredosum.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vfwredusum.vs  (format: vd,vs2,vs1,vm)
  val `vfwredusum_vs`: RvvInsn = RvvInsn(
    name       = "vfwredusum.vs",
    extension  = "v",
    sourceToml = "v/vfwredusum.vs.toml",
    schema     = Schema.VdVs2Vs1Vm,
    notestfloat3 = true)

  // vfwsub.vf  (format: vd,vs2,fs1,vm)
  val `vfwsub_vf`: RvvInsn = RvvInsn(
    name       = "vfwsub.vf",
    extension  = "v",
    sourceToml = "v/vfwsub.vf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Fs1Vm)

  // vfwsub.vv  (format: vd,vs2,vs1,vm)
  val `vfwsub_vv`: RvvInsn = RvvInsn(
    name       = "vfwsub.vv",
    extension  = "v",
    sourceToml = "v/vfwsub.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vfwsub.wf  (format: vd,vs2,fs1,vm)
  val `vfwsub_wf`: RvvInsn = RvvInsn(
    name       = "vfwsub.wf",
    extension  = "v",
    sourceToml = "v/vfwsub.wf.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Fs1Vm)

  // vfwsub.wv  (format: vd,vs2,vs1,vm)
  val `vfwsub_wv`: RvvInsn = RvvInsn(
    name       = "vfwsub.wv",
    extension  = "v",
    sourceToml = "v/vfwsub.wv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vid.v  (format: vd,vm)
  val `vid_v`: RvvInsn = RvvInsn(
    name       = "vid.v",
    extension  = "v",
    sourceToml = "v/vid.v.toml",
    schema     = Schema.VdVm)

  // viota.m  (format: vd,vs2,vm/2)
  val `viota_m`: RvvInsn = RvvInsn(
    name       = "viota.m",
    extension  = "v",
    sourceToml = "v/viota.m.toml",
    schema     = Schema.VdVs2VmP2)

  // vl1re16.v  (format: vd,(rs1))
  val `vl1re16_v`: RvvInsn = RvvInsn(
    name       = "vl1re16.v",
    extension  = "v",
    sourceToml = "v/vl1re16.v.toml",
    schema     = Schema.VdRs1m)

  // vl1re32.v  (format: vd,(rs1))
  val `vl1re32_v`: RvvInsn = RvvInsn(
    name       = "vl1re32.v",
    extension  = "v",
    sourceToml = "v/vl1re32.v.toml",
    schema     = Schema.VdRs1m)

  // vl1re64.v  (format: vd,(rs1))
  val `vl1re64_v`: RvvInsn = RvvInsn(
    name       = "vl1re64.v",
    extension  = "v",
    sourceToml = "v/vl1re64.v.toml",
    schema     = Schema.VdRs1m)

  // vl1re8.v  (format: vd,(rs1))
  val `vl1re8_v`: RvvInsn = RvvInsn(
    name       = "vl1re8.v",
    extension  = "v",
    sourceToml = "v/vl1re8.v.toml",
    schema     = Schema.VdRs1m)

  // vl2re16.v  (format: vd,(rs1))
  val `vl2re16_v`: RvvInsn = RvvInsn(
    name       = "vl2re16.v",
    extension  = "v",
    sourceToml = "v/vl2re16.v.toml",
    schema     = Schema.VdRs1m)

  // vl2re32.v  (format: vd,(rs1))
  val `vl2re32_v`: RvvInsn = RvvInsn(
    name       = "vl2re32.v",
    extension  = "v",
    sourceToml = "v/vl2re32.v.toml",
    schema     = Schema.VdRs1m)

  // vl2re64.v  (format: vd,(rs1))
  val `vl2re64_v`: RvvInsn = RvvInsn(
    name       = "vl2re64.v",
    extension  = "v",
    sourceToml = "v/vl2re64.v.toml",
    schema     = Schema.VdRs1m)

  // vl2re8.v  (format: vd,(rs1))
  val `vl2re8_v`: RvvInsn = RvvInsn(
    name       = "vl2re8.v",
    extension  = "v",
    sourceToml = "v/vl2re8.v.toml",
    schema     = Schema.VdRs1m)

  // vl4re16.v  (format: vd,(rs1))
  val `vl4re16_v`: RvvInsn = RvvInsn(
    name       = "vl4re16.v",
    extension  = "v",
    sourceToml = "v/vl4re16.v.toml",
    schema     = Schema.VdRs1m)

  // vl4re32.v  (format: vd,(rs1))
  val `vl4re32_v`: RvvInsn = RvvInsn(
    name       = "vl4re32.v",
    extension  = "v",
    sourceToml = "v/vl4re32.v.toml",
    schema     = Schema.VdRs1m)

  // vl4re64.v  (format: vd,(rs1))
  val `vl4re64_v`: RvvInsn = RvvInsn(
    name       = "vl4re64.v",
    extension  = "v",
    sourceToml = "v/vl4re64.v.toml",
    schema     = Schema.VdRs1m)

  // vl4re8.v  (format: vd,(rs1))
  val `vl4re8_v`: RvvInsn = RvvInsn(
    name       = "vl4re8.v",
    extension  = "v",
    sourceToml = "v/vl4re8.v.toml",
    schema     = Schema.VdRs1m)

  // vl8re16.v  (format: vd,(rs1))
  val `vl8re16_v`: RvvInsn = RvvInsn(
    name       = "vl8re16.v",
    extension  = "v",
    sourceToml = "v/vl8re16.v.toml",
    schema     = Schema.VdRs1m)

  // vl8re32.v  (format: vd,(rs1))
  val `vl8re32_v`: RvvInsn = RvvInsn(
    name       = "vl8re32.v",
    extension  = "v",
    sourceToml = "v/vl8re32.v.toml",
    schema     = Schema.VdRs1m)

  // vl8re64.v  (format: vd,(rs1))
  val `vl8re64_v`: RvvInsn = RvvInsn(
    name       = "vl8re64.v",
    extension  = "v",
    sourceToml = "v/vl8re64.v.toml",
    schema     = Schema.VdRs1m)

  // vl8re8.v  (format: vd,(rs1))
  val `vl8re8_v`: RvvInsn = RvvInsn(
    name       = "vl8re8.v",
    extension  = "v",
    sourceToml = "v/vl8re8.v.toml",
    schema     = Schema.VdRs1m)

  // vle16.v  (format: vd,(rs1),vm)
  val `vle16_v`: RvvInsn = RvvInsn(
    name       = "vle16.v",
    extension  = "v",
    sourceToml = "v/vle16.v.toml",
    schema     = Schema.VdRs1mVm)

  // vle16ff.v  (format: vd,(rs1),vm)
  val `vle16ff_v`: RvvInsn = RvvInsn(
    name       = "vle16ff.v",
    extension  = "v",
    sourceToml = "v/vle16ff.v.toml",
    schema     = Schema.VdRs1mVm)

  // vle32.v  (format: vd,(rs1),vm)
  val `vle32_v`: RvvInsn = RvvInsn(
    name       = "vle32.v",
    extension  = "v",
    sourceToml = "v/vle32.v.toml",
    schema     = Schema.VdRs1mVm)

  // vle32ff.v  (format: vd,(rs1),vm)
  val `vle32ff_v`: RvvInsn = RvvInsn(
    name       = "vle32ff.v",
    extension  = "v",
    sourceToml = "v/vle32ff.v.toml",
    schema     = Schema.VdRs1mVm)

  // vle64.v  (format: vd,(rs1),vm)
  val `vle64_v`: RvvInsn = RvvInsn(
    name       = "vle64.v",
    extension  = "v",
    sourceToml = "v/vle64.v.toml",
    schema     = Schema.VdRs1mVm)

  // vle64ff.v  (format: vd,(rs1),vm)
  val `vle64ff_v`: RvvInsn = RvvInsn(
    name       = "vle64ff.v",
    extension  = "v",
    sourceToml = "v/vle64ff.v.toml",
    schema     = Schema.VdRs1mVm)

  // vle8.v  (format: vd,(rs1),vm)
  val `vle8_v`: RvvInsn = RvvInsn(
    name       = "vle8.v",
    extension  = "v",
    sourceToml = "v/vle8.v.toml",
    schema     = Schema.VdRs1mVm)

  // vle8ff.v  (format: vd,(rs1),vm)
  val `vle8ff_v`: RvvInsn = RvvInsn(
    name       = "vle8ff.v",
    extension  = "v",
    sourceToml = "v/vle8ff.v.toml",
    schema     = Schema.VdRs1mVm)

  // vlm.v  (format: vd,(rs1))
  val `vlm_v`: RvvInsn = RvvInsn(
    name       = "vlm.v",
    extension  = "v",
    sourceToml = "v/vlm.v.toml",
    schema     = Schema.VdRs1m)

  // vloxei16.v  (format: vd,(rs1),vs2,vm)
  val `vloxei16_v`: RvvInsn = RvvInsn(
    name       = "vloxei16.v",
    extension  = "v",
    sourceToml = "v/vloxei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm,
    indexedEew = Some(16))

  // vloxei32.v  (format: vd,(rs1),vs2,vm)
  val `vloxei32_v`: RvvInsn = RvvInsn(
    name       = "vloxei32.v",
    extension  = "v",
    sourceToml = "v/vloxei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm,
    indexedEew = Some(32))

  // vloxei64.v  (format: vd,(rs1),vs2,vm)
  val `vloxei64_v`: RvvInsn = RvvInsn(
    name       = "vloxei64.v",
    extension  = "v",
    sourceToml = "v/vloxei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm,
    indexedEew = Some(64))

  // vloxei8.v  (format: vd,(rs1),vs2,vm)
  val `vloxei8_v`: RvvInsn = RvvInsn(
    name       = "vloxei8.v",
    extension  = "v",
    sourceToml = "v/vloxei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm,
    indexedEew = Some(8))

  // vloxseg2ei16.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg2ei16_v`: RvvInsn = RvvInsn(
    name       = "vloxseg2ei16.v",
    extension  = "v",
    sourceToml = "v/vloxseg2ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg2ei32.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg2ei32_v`: RvvInsn = RvvInsn(
    name       = "vloxseg2ei32.v",
    extension  = "v",
    sourceToml = "v/vloxseg2ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg2ei64.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg2ei64_v`: RvvInsn = RvvInsn(
    name       = "vloxseg2ei64.v",
    extension  = "v",
    sourceToml = "v/vloxseg2ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg2ei8.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg2ei8_v`: RvvInsn = RvvInsn(
    name       = "vloxseg2ei8.v",
    extension  = "v",
    sourceToml = "v/vloxseg2ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg3ei16.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg3ei16_v`: RvvInsn = RvvInsn(
    name       = "vloxseg3ei16.v",
    extension  = "v",
    sourceToml = "v/vloxseg3ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg3ei32.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg3ei32_v`: RvvInsn = RvvInsn(
    name       = "vloxseg3ei32.v",
    extension  = "v",
    sourceToml = "v/vloxseg3ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg3ei64.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg3ei64_v`: RvvInsn = RvvInsn(
    name       = "vloxseg3ei64.v",
    extension  = "v",
    sourceToml = "v/vloxseg3ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg3ei8.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg3ei8_v`: RvvInsn = RvvInsn(
    name       = "vloxseg3ei8.v",
    extension  = "v",
    sourceToml = "v/vloxseg3ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg4ei16.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg4ei16_v`: RvvInsn = RvvInsn(
    name       = "vloxseg4ei16.v",
    extension  = "v",
    sourceToml = "v/vloxseg4ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg4ei32.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg4ei32_v`: RvvInsn = RvvInsn(
    name       = "vloxseg4ei32.v",
    extension  = "v",
    sourceToml = "v/vloxseg4ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg4ei64.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg4ei64_v`: RvvInsn = RvvInsn(
    name       = "vloxseg4ei64.v",
    extension  = "v",
    sourceToml = "v/vloxseg4ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg4ei8.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg4ei8_v`: RvvInsn = RvvInsn(
    name       = "vloxseg4ei8.v",
    extension  = "v",
    sourceToml = "v/vloxseg4ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg5ei16.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg5ei16_v`: RvvInsn = RvvInsn(
    name       = "vloxseg5ei16.v",
    extension  = "v",
    sourceToml = "v/vloxseg5ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg5ei32.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg5ei32_v`: RvvInsn = RvvInsn(
    name       = "vloxseg5ei32.v",
    extension  = "v",
    sourceToml = "v/vloxseg5ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg5ei64.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg5ei64_v`: RvvInsn = RvvInsn(
    name       = "vloxseg5ei64.v",
    extension  = "v",
    sourceToml = "v/vloxseg5ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg5ei8.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg5ei8_v`: RvvInsn = RvvInsn(
    name       = "vloxseg5ei8.v",
    extension  = "v",
    sourceToml = "v/vloxseg5ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg6ei16.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg6ei16_v`: RvvInsn = RvvInsn(
    name       = "vloxseg6ei16.v",
    extension  = "v",
    sourceToml = "v/vloxseg6ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg6ei32.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg6ei32_v`: RvvInsn = RvvInsn(
    name       = "vloxseg6ei32.v",
    extension  = "v",
    sourceToml = "v/vloxseg6ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg6ei64.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg6ei64_v`: RvvInsn = RvvInsn(
    name       = "vloxseg6ei64.v",
    extension  = "v",
    sourceToml = "v/vloxseg6ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg6ei8.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg6ei8_v`: RvvInsn = RvvInsn(
    name       = "vloxseg6ei8.v",
    extension  = "v",
    sourceToml = "v/vloxseg6ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg7ei16.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg7ei16_v`: RvvInsn = RvvInsn(
    name       = "vloxseg7ei16.v",
    extension  = "v",
    sourceToml = "v/vloxseg7ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg7ei32.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg7ei32_v`: RvvInsn = RvvInsn(
    name       = "vloxseg7ei32.v",
    extension  = "v",
    sourceToml = "v/vloxseg7ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg7ei64.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg7ei64_v`: RvvInsn = RvvInsn(
    name       = "vloxseg7ei64.v",
    extension  = "v",
    sourceToml = "v/vloxseg7ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg7ei8.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg7ei8_v`: RvvInsn = RvvInsn(
    name       = "vloxseg7ei8.v",
    extension  = "v",
    sourceToml = "v/vloxseg7ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg8ei16.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg8ei16_v`: RvvInsn = RvvInsn(
    name       = "vloxseg8ei16.v",
    extension  = "v",
    sourceToml = "v/vloxseg8ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg8ei32.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg8ei32_v`: RvvInsn = RvvInsn(
    name       = "vloxseg8ei32.v",
    extension  = "v",
    sourceToml = "v/vloxseg8ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg8ei64.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg8ei64_v`: RvvInsn = RvvInsn(
    name       = "vloxseg8ei64.v",
    extension  = "v",
    sourceToml = "v/vloxseg8ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vloxseg8ei8.v  (format: vd,(rs1),vs2,vm)
  val `vloxseg8ei8_v`: RvvInsn = RvvInsn(
    name       = "vloxseg8ei8.v",
    extension  = "v",
    sourceToml = "v/vloxseg8ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vlse16.v  (format: vd,(rs1),rs2,vm)
  val `vlse16_v`: RvvInsn = RvvInsn(
    name       = "vlse16.v",
    extension  = "v",
    sourceToml = "v/vlse16.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlse32.v  (format: vd,(rs1),rs2,vm)
  val `vlse32_v`: RvvInsn = RvvInsn(
    name       = "vlse32.v",
    extension  = "v",
    sourceToml = "v/vlse32.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlse64.v  (format: vd,(rs1),rs2,vm)
  val `vlse64_v`: RvvInsn = RvvInsn(
    name       = "vlse64.v",
    extension  = "v",
    sourceToml = "v/vlse64.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlse8.v  (format: vd,(rs1),rs2,vm)
  val `vlse8_v`: RvvInsn = RvvInsn(
    name       = "vlse8.v",
    extension  = "v",
    sourceToml = "v/vlse8.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlseg2e16.v  (format: vd,(rs1),vm)
  val `vlseg2e16_v`: RvvInsn = RvvInsn(
    name       = "vlseg2e16.v",
    extension  = "v",
    sourceToml = "v/vlseg2e16.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 2)

  // vlseg2e16ff.v  (format: vd,(rs1),vm)
  val `vlseg2e16ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg2e16ff.v",
    extension  = "v",
    sourceToml = "v/vlseg2e16ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 2)

  // vlseg2e32.v  (format: vd,(rs1),vm)
  val `vlseg2e32_v`: RvvInsn = RvvInsn(
    name       = "vlseg2e32.v",
    extension  = "v",
    sourceToml = "v/vlseg2e32.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 2)

  // vlseg2e32ff.v  (format: vd,(rs1),vm)
  val `vlseg2e32ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg2e32ff.v",
    extension  = "v",
    sourceToml = "v/vlseg2e32ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 2)

  // vlseg2e64.v  (format: vd,(rs1),vm)
  val `vlseg2e64_v`: RvvInsn = RvvInsn(
    name       = "vlseg2e64.v",
    extension  = "v",
    sourceToml = "v/vlseg2e64.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 2)

  // vlseg2e64ff.v  (format: vd,(rs1),vm)
  val `vlseg2e64ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg2e64ff.v",
    extension  = "v",
    sourceToml = "v/vlseg2e64ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 2)

  // vlseg2e8.v  (format: vd,(rs1),vm)
  val `vlseg2e8_v`: RvvInsn = RvvInsn(
    name       = "vlseg2e8.v",
    extension  = "v",
    sourceToml = "v/vlseg2e8.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 2)

  // vlseg2e8ff.v  (format: vd,(rs1),vm)
  val `vlseg2e8ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg2e8ff.v",
    extension  = "v",
    sourceToml = "v/vlseg2e8ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 2)

  // vlseg3e16.v  (format: vd,(rs1),vm)
  val `vlseg3e16_v`: RvvInsn = RvvInsn(
    name       = "vlseg3e16.v",
    extension  = "v",
    sourceToml = "v/vlseg3e16.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 3)

  // vlseg3e16ff.v  (format: vd,(rs1),vm)
  val `vlseg3e16ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg3e16ff.v",
    extension  = "v",
    sourceToml = "v/vlseg3e16ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 3)

  // vlseg3e32.v  (format: vd,(rs1),vm)
  val `vlseg3e32_v`: RvvInsn = RvvInsn(
    name       = "vlseg3e32.v",
    extension  = "v",
    sourceToml = "v/vlseg3e32.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 3)

  // vlseg3e32ff.v  (format: vd,(rs1),vm)
  val `vlseg3e32ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg3e32ff.v",
    extension  = "v",
    sourceToml = "v/vlseg3e32ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 3)

  // vlseg3e64.v  (format: vd,(rs1),vm)
  val `vlseg3e64_v`: RvvInsn = RvvInsn(
    name       = "vlseg3e64.v",
    extension  = "v",
    sourceToml = "v/vlseg3e64.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 3)

  // vlseg3e64ff.v  (format: vd,(rs1),vm)
  val `vlseg3e64ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg3e64ff.v",
    extension  = "v",
    sourceToml = "v/vlseg3e64ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 3)

  // vlseg3e8.v  (format: vd,(rs1),vm)
  val `vlseg3e8_v`: RvvInsn = RvvInsn(
    name       = "vlseg3e8.v",
    extension  = "v",
    sourceToml = "v/vlseg3e8.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 3)

  // vlseg3e8ff.v  (format: vd,(rs1),vm)
  val `vlseg3e8ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg3e8ff.v",
    extension  = "v",
    sourceToml = "v/vlseg3e8ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 3)

  // vlseg4e16.v  (format: vd,(rs1),vm)
  val `vlseg4e16_v`: RvvInsn = RvvInsn(
    name       = "vlseg4e16.v",
    extension  = "v",
    sourceToml = "v/vlseg4e16.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 4)

  // vlseg4e16ff.v  (format: vd,(rs1),vm)
  val `vlseg4e16ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg4e16ff.v",
    extension  = "v",
    sourceToml = "v/vlseg4e16ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 4)

  // vlseg4e32.v  (format: vd,(rs1),vm)
  val `vlseg4e32_v`: RvvInsn = RvvInsn(
    name       = "vlseg4e32.v",
    extension  = "v",
    sourceToml = "v/vlseg4e32.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 4)

  // vlseg4e32ff.v  (format: vd,(rs1),vm)
  val `vlseg4e32ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg4e32ff.v",
    extension  = "v",
    sourceToml = "v/vlseg4e32ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 4)

  // vlseg4e64.v  (format: vd,(rs1),vm)
  val `vlseg4e64_v`: RvvInsn = RvvInsn(
    name       = "vlseg4e64.v",
    extension  = "v",
    sourceToml = "v/vlseg4e64.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 4)

  // vlseg4e64ff.v  (format: vd,(rs1),vm)
  val `vlseg4e64ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg4e64ff.v",
    extension  = "v",
    sourceToml = "v/vlseg4e64ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 4)

  val chunkAll: List[RvvInsn] = List(
    `vfwmacc_vv`,
    `vfwmsac_vf`,
    `vfwmsac_vv`,
    `vfwmul_vf`,
    `vfwmul_vv`,
    `vfwnmacc_vf`,
    `vfwnmacc_vv`,
    `vfwnmsac_vf`,
    `vfwnmsac_vv`,
    `vfwredosum_vs`,
    `vfwredusum_vs`,
    `vfwsub_vf`,
    `vfwsub_vv`,
    `vfwsub_wf`,
    `vfwsub_wv`,
    `vid_v`,
    `viota_m`,
    `vl1re16_v`,
    `vl1re32_v`,
    `vl1re64_v`,
    `vl1re8_v`,
    `vl2re16_v`,
    `vl2re32_v`,
    `vl2re64_v`,
    `vl2re8_v`,
    `vl4re16_v`,
    `vl4re32_v`,
    `vl4re64_v`,
    `vl4re8_v`,
    `vl8re16_v`,
    `vl8re32_v`,
    `vl8re64_v`,
    `vl8re8_v`,
    `vle16_v`,
    `vle16ff_v`,
    `vle32_v`,
    `vle32ff_v`,
    `vle64_v`,
    `vle64ff_v`,
    `vle8_v`,
    `vle8ff_v`,
    `vlm_v`,
    `vloxei16_v`,
    `vloxei32_v`,
    `vloxei64_v`,
    `vloxei8_v`,
    `vloxseg2ei16_v`,
    `vloxseg2ei32_v`,
    `vloxseg2ei64_v`,
    `vloxseg2ei8_v`,
    `vloxseg3ei16_v`,
    `vloxseg3ei32_v`,
    `vloxseg3ei64_v`,
    `vloxseg3ei8_v`,
    `vloxseg4ei16_v`,
    `vloxseg4ei32_v`,
    `vloxseg4ei64_v`,
    `vloxseg4ei8_v`,
    `vloxseg5ei16_v`,
    `vloxseg5ei32_v`,
    `vloxseg5ei64_v`,
    `vloxseg5ei8_v`,
    `vloxseg6ei16_v`,
    `vloxseg6ei32_v`,
    `vloxseg6ei64_v`,
    `vloxseg6ei8_v`,
    `vloxseg7ei16_v`,
    `vloxseg7ei32_v`,
    `vloxseg7ei64_v`,
    `vloxseg7ei8_v`,
    `vloxseg8ei16_v`,
    `vloxseg8ei32_v`,
    `vloxseg8ei64_v`,
    `vloxseg8ei8_v`,
    `vlse16_v`,
    `vlse32_v`,
    `vlse64_v`,
    `vlse8_v`,
    `vlseg2e16_v`,
    `vlseg2e16ff_v`,
    `vlseg2e32_v`,
    `vlseg2e32ff_v`,
    `vlseg2e64_v`,
    `vlseg2e64ff_v`,
    `vlseg2e8_v`,
    `vlseg2e8ff_v`,
    `vlseg3e16_v`,
    `vlseg3e16ff_v`,
    `vlseg3e32_v`,
    `vlseg3e32ff_v`,
    `vlseg3e64_v`,
    `vlseg3e64ff_v`,
    `vlseg3e8_v`,
    `vlseg3e8ff_v`,
    `vlseg4e16_v`,
    `vlseg4e16ff_v`,
    `vlseg4e32_v`,
    `vlseg4e32ff_v`,
    `vlseg4e64_v`,
    `vlseg4e64ff_v`
  )
