// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/v/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.eew.OperandWidthProfile
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 100 RvvInsn declarations for `v` (chunk 2). */
object V2:
  // vlseg4e8.v  (format: vd,(rs1),vm)
  val `vlseg4e8_v`: RvvInsn = RvvInsn(
    name       = "vlseg4e8.v",
    extension  = "v",
    sourceToml = "v/vlseg4e8.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 4)

  // vlseg4e8ff.v  (format: vd,(rs1),vm)
  val `vlseg4e8ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg4e8ff.v",
    extension  = "v",
    sourceToml = "v/vlseg4e8ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 4)

  // vlseg5e16.v  (format: vd,(rs1),vm)
  val `vlseg5e16_v`: RvvInsn = RvvInsn(
    name       = "vlseg5e16.v",
    extension  = "v",
    sourceToml = "v/vlseg5e16.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 5)

  // vlseg5e16ff.v  (format: vd,(rs1),vm)
  val `vlseg5e16ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg5e16ff.v",
    extension  = "v",
    sourceToml = "v/vlseg5e16ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 5)

  // vlseg5e32.v  (format: vd,(rs1),vm)
  val `vlseg5e32_v`: RvvInsn = RvvInsn(
    name       = "vlseg5e32.v",
    extension  = "v",
    sourceToml = "v/vlseg5e32.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 5)

  // vlseg5e32ff.v  (format: vd,(rs1),vm)
  val `vlseg5e32ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg5e32ff.v",
    extension  = "v",
    sourceToml = "v/vlseg5e32ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 5)

  // vlseg5e64.v  (format: vd,(rs1),vm)
  val `vlseg5e64_v`: RvvInsn = RvvInsn(
    name       = "vlseg5e64.v",
    extension  = "v",
    sourceToml = "v/vlseg5e64.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 5)

  // vlseg5e64ff.v  (format: vd,(rs1),vm)
  val `vlseg5e64ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg5e64ff.v",
    extension  = "v",
    sourceToml = "v/vlseg5e64ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 5)

  // vlseg5e8.v  (format: vd,(rs1),vm)
  val `vlseg5e8_v`: RvvInsn = RvvInsn(
    name       = "vlseg5e8.v",
    extension  = "v",
    sourceToml = "v/vlseg5e8.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 5)

  // vlseg5e8ff.v  (format: vd,(rs1),vm)
  val `vlseg5e8ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg5e8ff.v",
    extension  = "v",
    sourceToml = "v/vlseg5e8ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 5)

  // vlseg6e16.v  (format: vd,(rs1),vm)
  val `vlseg6e16_v`: RvvInsn = RvvInsn(
    name       = "vlseg6e16.v",
    extension  = "v",
    sourceToml = "v/vlseg6e16.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 6)

  // vlseg6e16ff.v  (format: vd,(rs1),vm)
  val `vlseg6e16ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg6e16ff.v",
    extension  = "v",
    sourceToml = "v/vlseg6e16ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 6)

  // vlseg6e32.v  (format: vd,(rs1),vm)
  val `vlseg6e32_v`: RvvInsn = RvvInsn(
    name       = "vlseg6e32.v",
    extension  = "v",
    sourceToml = "v/vlseg6e32.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 6)

  // vlseg6e32ff.v  (format: vd,(rs1),vm)
  val `vlseg6e32ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg6e32ff.v",
    extension  = "v",
    sourceToml = "v/vlseg6e32ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 6)

  // vlseg6e64.v  (format: vd,(rs1),vm)
  val `vlseg6e64_v`: RvvInsn = RvvInsn(
    name       = "vlseg6e64.v",
    extension  = "v",
    sourceToml = "v/vlseg6e64.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 6)

  // vlseg6e64ff.v  (format: vd,(rs1),vm)
  val `vlseg6e64ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg6e64ff.v",
    extension  = "v",
    sourceToml = "v/vlseg6e64ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 6)

  // vlseg6e8.v  (format: vd,(rs1),vm)
  val `vlseg6e8_v`: RvvInsn = RvvInsn(
    name       = "vlseg6e8.v",
    extension  = "v",
    sourceToml = "v/vlseg6e8.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 6)

  // vlseg6e8ff.v  (format: vd,(rs1),vm)
  val `vlseg6e8ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg6e8ff.v",
    extension  = "v",
    sourceToml = "v/vlseg6e8ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 6)

  // vlseg7e16.v  (format: vd,(rs1),vm)
  val `vlseg7e16_v`: RvvInsn = RvvInsn(
    name       = "vlseg7e16.v",
    extension  = "v",
    sourceToml = "v/vlseg7e16.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 7)

  // vlseg7e16ff.v  (format: vd,(rs1),vm)
  val `vlseg7e16ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg7e16ff.v",
    extension  = "v",
    sourceToml = "v/vlseg7e16ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 7)

  // vlseg7e32.v  (format: vd,(rs1),vm)
  val `vlseg7e32_v`: RvvInsn = RvvInsn(
    name       = "vlseg7e32.v",
    extension  = "v",
    sourceToml = "v/vlseg7e32.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 7)

  // vlseg7e32ff.v  (format: vd,(rs1),vm)
  val `vlseg7e32ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg7e32ff.v",
    extension  = "v",
    sourceToml = "v/vlseg7e32ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 7)

  // vlseg7e64.v  (format: vd,(rs1),vm)
  val `vlseg7e64_v`: RvvInsn = RvvInsn(
    name       = "vlseg7e64.v",
    extension  = "v",
    sourceToml = "v/vlseg7e64.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 7)

  // vlseg7e64ff.v  (format: vd,(rs1),vm)
  val `vlseg7e64ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg7e64ff.v",
    extension  = "v",
    sourceToml = "v/vlseg7e64ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 7)

  // vlseg7e8.v  (format: vd,(rs1),vm)
  val `vlseg7e8_v`: RvvInsn = RvvInsn(
    name       = "vlseg7e8.v",
    extension  = "v",
    sourceToml = "v/vlseg7e8.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 7)

  // vlseg7e8ff.v  (format: vd,(rs1),vm)
  val `vlseg7e8ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg7e8ff.v",
    extension  = "v",
    sourceToml = "v/vlseg7e8ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 7)

  // vlseg8e16.v  (format: vd,(rs1),vm)
  val `vlseg8e16_v`: RvvInsn = RvvInsn(
    name       = "vlseg8e16.v",
    extension  = "v",
    sourceToml = "v/vlseg8e16.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 8)

  // vlseg8e16ff.v  (format: vd,(rs1),vm)
  val `vlseg8e16ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg8e16ff.v",
    extension  = "v",
    sourceToml = "v/vlseg8e16ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 8)

  // vlseg8e32.v  (format: vd,(rs1),vm)
  val `vlseg8e32_v`: RvvInsn = RvvInsn(
    name       = "vlseg8e32.v",
    extension  = "v",
    sourceToml = "v/vlseg8e32.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 8)

  // vlseg8e32ff.v  (format: vd,(rs1),vm)
  val `vlseg8e32ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg8e32ff.v",
    extension  = "v",
    sourceToml = "v/vlseg8e32ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 8)

  // vlseg8e64.v  (format: vd,(rs1),vm)
  val `vlseg8e64_v`: RvvInsn = RvvInsn(
    name       = "vlseg8e64.v",
    extension  = "v",
    sourceToml = "v/vlseg8e64.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 8)

  // vlseg8e64ff.v  (format: vd,(rs1),vm)
  val `vlseg8e64ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg8e64ff.v",
    extension  = "v",
    sourceToml = "v/vlseg8e64ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 8)

  // vlseg8e8.v  (format: vd,(rs1),vm)
  val `vlseg8e8_v`: RvvInsn = RvvInsn(
    name       = "vlseg8e8.v",
    extension  = "v",
    sourceToml = "v/vlseg8e8.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 8)

  // vlseg8e8ff.v  (format: vd,(rs1),vm)
  val `vlseg8e8ff_v`: RvvInsn = RvvInsn(
    name       = "vlseg8e8ff.v",
    extension  = "v",
    sourceToml = "v/vlseg8e8ff.v.toml",
    schema     = Schema.VdRs1mVm,
    nfields = 8)

  // vlsseg2e16.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg2e16_v`: RvvInsn = RvvInsn(
    name       = "vlsseg2e16.v",
    extension  = "v",
    sourceToml = "v/vlsseg2e16.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg2e32.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg2e32_v`: RvvInsn = RvvInsn(
    name       = "vlsseg2e32.v",
    extension  = "v",
    sourceToml = "v/vlsseg2e32.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg2e64.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg2e64_v`: RvvInsn = RvvInsn(
    name       = "vlsseg2e64.v",
    extension  = "v",
    sourceToml = "v/vlsseg2e64.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg2e8.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg2e8_v`: RvvInsn = RvvInsn(
    name       = "vlsseg2e8.v",
    extension  = "v",
    sourceToml = "v/vlsseg2e8.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg3e16.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg3e16_v`: RvvInsn = RvvInsn(
    name       = "vlsseg3e16.v",
    extension  = "v",
    sourceToml = "v/vlsseg3e16.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg3e32.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg3e32_v`: RvvInsn = RvvInsn(
    name       = "vlsseg3e32.v",
    extension  = "v",
    sourceToml = "v/vlsseg3e32.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg3e64.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg3e64_v`: RvvInsn = RvvInsn(
    name       = "vlsseg3e64.v",
    extension  = "v",
    sourceToml = "v/vlsseg3e64.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg3e8.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg3e8_v`: RvvInsn = RvvInsn(
    name       = "vlsseg3e8.v",
    extension  = "v",
    sourceToml = "v/vlsseg3e8.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg4e16.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg4e16_v`: RvvInsn = RvvInsn(
    name       = "vlsseg4e16.v",
    extension  = "v",
    sourceToml = "v/vlsseg4e16.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg4e32.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg4e32_v`: RvvInsn = RvvInsn(
    name       = "vlsseg4e32.v",
    extension  = "v",
    sourceToml = "v/vlsseg4e32.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg4e64.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg4e64_v`: RvvInsn = RvvInsn(
    name       = "vlsseg4e64.v",
    extension  = "v",
    sourceToml = "v/vlsseg4e64.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg4e8.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg4e8_v`: RvvInsn = RvvInsn(
    name       = "vlsseg4e8.v",
    extension  = "v",
    sourceToml = "v/vlsseg4e8.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg5e16.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg5e16_v`: RvvInsn = RvvInsn(
    name       = "vlsseg5e16.v",
    extension  = "v",
    sourceToml = "v/vlsseg5e16.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg5e32.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg5e32_v`: RvvInsn = RvvInsn(
    name       = "vlsseg5e32.v",
    extension  = "v",
    sourceToml = "v/vlsseg5e32.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg5e64.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg5e64_v`: RvvInsn = RvvInsn(
    name       = "vlsseg5e64.v",
    extension  = "v",
    sourceToml = "v/vlsseg5e64.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg5e8.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg5e8_v`: RvvInsn = RvvInsn(
    name       = "vlsseg5e8.v",
    extension  = "v",
    sourceToml = "v/vlsseg5e8.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg6e16.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg6e16_v`: RvvInsn = RvvInsn(
    name       = "vlsseg6e16.v",
    extension  = "v",
    sourceToml = "v/vlsseg6e16.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg6e32.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg6e32_v`: RvvInsn = RvvInsn(
    name       = "vlsseg6e32.v",
    extension  = "v",
    sourceToml = "v/vlsseg6e32.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg6e64.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg6e64_v`: RvvInsn = RvvInsn(
    name       = "vlsseg6e64.v",
    extension  = "v",
    sourceToml = "v/vlsseg6e64.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg6e8.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg6e8_v`: RvvInsn = RvvInsn(
    name       = "vlsseg6e8.v",
    extension  = "v",
    sourceToml = "v/vlsseg6e8.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg7e16.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg7e16_v`: RvvInsn = RvvInsn(
    name       = "vlsseg7e16.v",
    extension  = "v",
    sourceToml = "v/vlsseg7e16.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg7e32.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg7e32_v`: RvvInsn = RvvInsn(
    name       = "vlsseg7e32.v",
    extension  = "v",
    sourceToml = "v/vlsseg7e32.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg7e64.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg7e64_v`: RvvInsn = RvvInsn(
    name       = "vlsseg7e64.v",
    extension  = "v",
    sourceToml = "v/vlsseg7e64.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg7e8.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg7e8_v`: RvvInsn = RvvInsn(
    name       = "vlsseg7e8.v",
    extension  = "v",
    sourceToml = "v/vlsseg7e8.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg8e16.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg8e16_v`: RvvInsn = RvvInsn(
    name       = "vlsseg8e16.v",
    extension  = "v",
    sourceToml = "v/vlsseg8e16.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg8e32.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg8e32_v`: RvvInsn = RvvInsn(
    name       = "vlsseg8e32.v",
    extension  = "v",
    sourceToml = "v/vlsseg8e32.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg8e64.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg8e64_v`: RvvInsn = RvvInsn(
    name       = "vlsseg8e64.v",
    extension  = "v",
    sourceToml = "v/vlsseg8e64.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vlsseg8e8.v  (format: vd,(rs1),rs2,vm)
  val `vlsseg8e8_v`: RvvInsn = RvvInsn(
    name       = "vlsseg8e8.v",
    extension  = "v",
    sourceToml = "v/vlsseg8e8.v.toml",
    schema     = Schema.VdRs1mRs2Vm)

  // vluxei16.v  (format: vd,(rs1),vs2,vm)
  val `vluxei16_v`: RvvInsn = RvvInsn(
    name       = "vluxei16.v",
    extension  = "v",
    sourceToml = "v/vluxei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm,
    indexedEew = Some(16))

  // vluxei32.v  (format: vd,(rs1),vs2,vm)
  val `vluxei32_v`: RvvInsn = RvvInsn(
    name       = "vluxei32.v",
    extension  = "v",
    sourceToml = "v/vluxei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm,
    indexedEew = Some(32))

  // vluxei64.v  (format: vd,(rs1),vs2,vm)
  val `vluxei64_v`: RvvInsn = RvvInsn(
    name       = "vluxei64.v",
    extension  = "v",
    sourceToml = "v/vluxei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm,
    indexedEew = Some(64))

  // vluxei8.v  (format: vd,(rs1),vs2,vm)
  val `vluxei8_v`: RvvInsn = RvvInsn(
    name       = "vluxei8.v",
    extension  = "v",
    sourceToml = "v/vluxei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm,
    indexedEew = Some(8))

  // vluxseg2ei16.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg2ei16_v`: RvvInsn = RvvInsn(
    name       = "vluxseg2ei16.v",
    extension  = "v",
    sourceToml = "v/vluxseg2ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg2ei32.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg2ei32_v`: RvvInsn = RvvInsn(
    name       = "vluxseg2ei32.v",
    extension  = "v",
    sourceToml = "v/vluxseg2ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg2ei64.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg2ei64_v`: RvvInsn = RvvInsn(
    name       = "vluxseg2ei64.v",
    extension  = "v",
    sourceToml = "v/vluxseg2ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg2ei8.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg2ei8_v`: RvvInsn = RvvInsn(
    name       = "vluxseg2ei8.v",
    extension  = "v",
    sourceToml = "v/vluxseg2ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg3ei16.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg3ei16_v`: RvvInsn = RvvInsn(
    name       = "vluxseg3ei16.v",
    extension  = "v",
    sourceToml = "v/vluxseg3ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg3ei32.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg3ei32_v`: RvvInsn = RvvInsn(
    name       = "vluxseg3ei32.v",
    extension  = "v",
    sourceToml = "v/vluxseg3ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg3ei64.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg3ei64_v`: RvvInsn = RvvInsn(
    name       = "vluxseg3ei64.v",
    extension  = "v",
    sourceToml = "v/vluxseg3ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg3ei8.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg3ei8_v`: RvvInsn = RvvInsn(
    name       = "vluxseg3ei8.v",
    extension  = "v",
    sourceToml = "v/vluxseg3ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg4ei16.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg4ei16_v`: RvvInsn = RvvInsn(
    name       = "vluxseg4ei16.v",
    extension  = "v",
    sourceToml = "v/vluxseg4ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg4ei32.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg4ei32_v`: RvvInsn = RvvInsn(
    name       = "vluxseg4ei32.v",
    extension  = "v",
    sourceToml = "v/vluxseg4ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg4ei64.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg4ei64_v`: RvvInsn = RvvInsn(
    name       = "vluxseg4ei64.v",
    extension  = "v",
    sourceToml = "v/vluxseg4ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg4ei8.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg4ei8_v`: RvvInsn = RvvInsn(
    name       = "vluxseg4ei8.v",
    extension  = "v",
    sourceToml = "v/vluxseg4ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg5ei16.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg5ei16_v`: RvvInsn = RvvInsn(
    name       = "vluxseg5ei16.v",
    extension  = "v",
    sourceToml = "v/vluxseg5ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg5ei32.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg5ei32_v`: RvvInsn = RvvInsn(
    name       = "vluxseg5ei32.v",
    extension  = "v",
    sourceToml = "v/vluxseg5ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg5ei64.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg5ei64_v`: RvvInsn = RvvInsn(
    name       = "vluxseg5ei64.v",
    extension  = "v",
    sourceToml = "v/vluxseg5ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg5ei8.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg5ei8_v`: RvvInsn = RvvInsn(
    name       = "vluxseg5ei8.v",
    extension  = "v",
    sourceToml = "v/vluxseg5ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg6ei16.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg6ei16_v`: RvvInsn = RvvInsn(
    name       = "vluxseg6ei16.v",
    extension  = "v",
    sourceToml = "v/vluxseg6ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg6ei32.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg6ei32_v`: RvvInsn = RvvInsn(
    name       = "vluxseg6ei32.v",
    extension  = "v",
    sourceToml = "v/vluxseg6ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg6ei64.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg6ei64_v`: RvvInsn = RvvInsn(
    name       = "vluxseg6ei64.v",
    extension  = "v",
    sourceToml = "v/vluxseg6ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg6ei8.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg6ei8_v`: RvvInsn = RvvInsn(
    name       = "vluxseg6ei8.v",
    extension  = "v",
    sourceToml = "v/vluxseg6ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg7ei16.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg7ei16_v`: RvvInsn = RvvInsn(
    name       = "vluxseg7ei16.v",
    extension  = "v",
    sourceToml = "v/vluxseg7ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg7ei32.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg7ei32_v`: RvvInsn = RvvInsn(
    name       = "vluxseg7ei32.v",
    extension  = "v",
    sourceToml = "v/vluxseg7ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg7ei64.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg7ei64_v`: RvvInsn = RvvInsn(
    name       = "vluxseg7ei64.v",
    extension  = "v",
    sourceToml = "v/vluxseg7ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg7ei8.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg7ei8_v`: RvvInsn = RvvInsn(
    name       = "vluxseg7ei8.v",
    extension  = "v",
    sourceToml = "v/vluxseg7ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg8ei16.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg8ei16_v`: RvvInsn = RvvInsn(
    name       = "vluxseg8ei16.v",
    extension  = "v",
    sourceToml = "v/vluxseg8ei16.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg8ei32.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg8ei32_v`: RvvInsn = RvvInsn(
    name       = "vluxseg8ei32.v",
    extension  = "v",
    sourceToml = "v/vluxseg8ei32.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg8ei64.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg8ei64_v`: RvvInsn = RvvInsn(
    name       = "vluxseg8ei64.v",
    extension  = "v",
    sourceToml = "v/vluxseg8ei64.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vluxseg8ei8.v  (format: vd,(rs1),vs2,vm)
  val `vluxseg8ei8_v`: RvvInsn = RvvInsn(
    name       = "vluxseg8ei8.v",
    extension  = "v",
    sourceToml = "v/vluxseg8ei8.v.toml",
    schema     = Schema.VdRs1mVs2Vm)

  // vmacc.vv  (format: vd,vs1,vs2,vm)
  val `vmacc_vv`: RvvInsn = RvvInsn(
    name       = "vmacc.vv",
    extension  = "v",
    sourceToml = "v/vmacc.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vmacc.vx  (format: vd,rs1,vs2,vm)
  val `vmacc_vx`: RvvInsn = RvvInsn(
    name       = "vmacc.vx",
    extension  = "v",
    sourceToml = "v/vmacc.vx.toml",
    schema     = Schema.VdRs1Vs2Vm)

  // vmadc.vi  (format: vd,vs2,imm)
  val `vmadc_vi`: RvvInsn = RvvInsn(
    name       = "vmadc.vi",
    extension  = "v",
    sourceToml = "v/vmadc.vi.toml",
    widthProfile = OperandWidthProfile.maskDestination(),
    schema     = Schema.VdVs2Imm)

  // vmadc.vim  (format: vd,vs2,imm,v0)
  val `vmadc_vim`: RvvInsn = RvvInsn(
    name       = "vmadc.vim",
    extension  = "v",
    sourceToml = "v/vmadc.vim.toml",
    widthProfile = OperandWidthProfile.maskDestination(),
    schema     = Schema.VdVs2ImmV0)

  // vmadc.vv  (format: vd,vs2,vs1)
  val `vmadc_vv`: RvvInsn = RvvInsn(
    name       = "vmadc.vv",
    extension  = "v",
    sourceToml = "v/vmadc.vv.toml",
    widthProfile = OperandWidthProfile.maskDestination(),
    schema     = Schema.VdVs2Vs1)

  // vmadc.vvm  (format: vd,vs2,vs1,v0)
  val `vmadc_vvm`: RvvInsn = RvvInsn(
    name       = "vmadc.vvm",
    extension  = "v",
    sourceToml = "v/vmadc.vvm.toml",
    widthProfile = OperandWidthProfile.maskDestination(),
    schema     = Schema.VdVs2Vs1V0)

  val chunkAll: List[RvvInsn] = List(
    `vlseg4e8_v`,
    `vlseg4e8ff_v`,
    `vlseg5e16_v`,
    `vlseg5e16ff_v`,
    `vlseg5e32_v`,
    `vlseg5e32ff_v`,
    `vlseg5e64_v`,
    `vlseg5e64ff_v`,
    `vlseg5e8_v`,
    `vlseg5e8ff_v`,
    `vlseg6e16_v`,
    `vlseg6e16ff_v`,
    `vlseg6e32_v`,
    `vlseg6e32ff_v`,
    `vlseg6e64_v`,
    `vlseg6e64ff_v`,
    `vlseg6e8_v`,
    `vlseg6e8ff_v`,
    `vlseg7e16_v`,
    `vlseg7e16ff_v`,
    `vlseg7e32_v`,
    `vlseg7e32ff_v`,
    `vlseg7e64_v`,
    `vlseg7e64ff_v`,
    `vlseg7e8_v`,
    `vlseg7e8ff_v`,
    `vlseg8e16_v`,
    `vlseg8e16ff_v`,
    `vlseg8e32_v`,
    `vlseg8e32ff_v`,
    `vlseg8e64_v`,
    `vlseg8e64ff_v`,
    `vlseg8e8_v`,
    `vlseg8e8ff_v`,
    `vlsseg2e16_v`,
    `vlsseg2e32_v`,
    `vlsseg2e64_v`,
    `vlsseg2e8_v`,
    `vlsseg3e16_v`,
    `vlsseg3e32_v`,
    `vlsseg3e64_v`,
    `vlsseg3e8_v`,
    `vlsseg4e16_v`,
    `vlsseg4e32_v`,
    `vlsseg4e64_v`,
    `vlsseg4e8_v`,
    `vlsseg5e16_v`,
    `vlsseg5e32_v`,
    `vlsseg5e64_v`,
    `vlsseg5e8_v`,
    `vlsseg6e16_v`,
    `vlsseg6e32_v`,
    `vlsseg6e64_v`,
    `vlsseg6e8_v`,
    `vlsseg7e16_v`,
    `vlsseg7e32_v`,
    `vlsseg7e64_v`,
    `vlsseg7e8_v`,
    `vlsseg8e16_v`,
    `vlsseg8e32_v`,
    `vlsseg8e64_v`,
    `vlsseg8e8_v`,
    `vluxei16_v`,
    `vluxei32_v`,
    `vluxei64_v`,
    `vluxei8_v`,
    `vluxseg2ei16_v`,
    `vluxseg2ei32_v`,
    `vluxseg2ei64_v`,
    `vluxseg2ei8_v`,
    `vluxseg3ei16_v`,
    `vluxseg3ei32_v`,
    `vluxseg3ei64_v`,
    `vluxseg3ei8_v`,
    `vluxseg4ei16_v`,
    `vluxseg4ei32_v`,
    `vluxseg4ei64_v`,
    `vluxseg4ei8_v`,
    `vluxseg5ei16_v`,
    `vluxseg5ei32_v`,
    `vluxseg5ei64_v`,
    `vluxseg5ei8_v`,
    `vluxseg6ei16_v`,
    `vluxseg6ei32_v`,
    `vluxseg6ei64_v`,
    `vluxseg6ei8_v`,
    `vluxseg7ei16_v`,
    `vluxseg7ei32_v`,
    `vluxseg7ei64_v`,
    `vluxseg7ei8_v`,
    `vluxseg8ei16_v`,
    `vluxseg8ei32_v`,
    `vluxseg8ei64_v`,
    `vluxseg8ei8_v`,
    `vmacc_vv`,
    `vmacc_vx`,
    `vmadc_vi`,
    `vmadc_vim`,
    `vmadc_vv`,
    `vmadc_vvm`
  )
