// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/v/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 100 RvvInsn declarations for `v` (chunk 3). */
object V3:
  // vmadc.vx  (format: vd,vs2,rs1)
  val `vmadc_vx`: RvvInsn = RvvInsn(
    name       = "vmadc.vx",
    extension  = "v",
    sourceToml = "v/vmadc.vx.toml",
    schema     = Schema.VdVs2Rs1)

  // vmadc.vxm  (format: vd,vs2,rs1,v0)
  val `vmadc_vxm`: RvvInsn = RvvInsn(
    name       = "vmadc.vxm",
    extension  = "v",
    sourceToml = "v/vmadc.vxm.toml",
    schema     = Schema.VdVs2Rs1V0)

  // vmadd.vv  (format: vd,vs1,vs2,vm)
  val `vmadd_vv`: RvvInsn = RvvInsn(
    name       = "vmadd.vv",
    extension  = "v",
    sourceToml = "v/vmadd.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vmadd.vx  (format: vd,rs1,vs2,vm)
  val `vmadd_vx`: RvvInsn = RvvInsn(
    name       = "vmadd.vx",
    extension  = "v",
    sourceToml = "v/vmadd.vx.toml",
    schema     = Schema.VdRs1Vs2Vm)

  // vmand.mm  (format: vd,vs2,vs1)
  val `vmand_mm`: RvvInsn = RvvInsn(
    name       = "vmand.mm",
    extension  = "v",
    sourceToml = "v/vmand.mm.toml",
    schema     = Schema.VdVs2Vs1)

  // vmandn.mm  (format: vd,vs2,vs1)
  val `vmandn_mm`: RvvInsn = RvvInsn(
    name       = "vmandn.mm",
    extension  = "v",
    sourceToml = "v/vmandn.mm.toml",
    schema     = Schema.VdVs2Vs1)

  // vmax.vv  (format: vd,vs2,vs1,vm)
  val `vmax_vv`: RvvInsn = RvvInsn(
    name       = "vmax.vv",
    extension  = "v",
    sourceToml = "v/vmax.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmax.vx  (format: vd,vs2,rs1,vm)
  val `vmax_vx`: RvvInsn = RvvInsn(
    name       = "vmax.vx",
    extension  = "v",
    sourceToml = "v/vmax.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmaxu.vv  (format: vd,vs2,vs1,vm)
  val `vmaxu_vv`: RvvInsn = RvvInsn(
    name       = "vmaxu.vv",
    extension  = "v",
    sourceToml = "v/vmaxu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmaxu.vx  (format: vd,vs2,rs1,vm)
  val `vmaxu_vx`: RvvInsn = RvvInsn(
    name       = "vmaxu.vx",
    extension  = "v",
    sourceToml = "v/vmaxu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmerge.vim  (format: vd,vs2,imm,v0)
  val `vmerge_vim`: RvvInsn = RvvInsn(
    name       = "vmerge.vim",
    extension  = "v",
    sourceToml = "v/vmerge.vim.toml",
    schema     = Schema.VdVs2ImmV0)

  // vmerge.vvm  (format: vd,vs2,vs1,v0)
  val `vmerge_vvm`: RvvInsn = RvvInsn(
    name       = "vmerge.vvm",
    extension  = "v",
    sourceToml = "v/vmerge.vvm.toml",
    schema     = Schema.VdVs2Vs1V0)

  // vmerge.vxm  (format: vd,vs2,rs1,v0)
  val `vmerge_vxm`: RvvInsn = RvvInsn(
    name       = "vmerge.vxm",
    extension  = "v",
    sourceToml = "v/vmerge.vxm.toml",
    schema     = Schema.VdVs2Rs1V0)

  // vmfeq.vf  (format: vd,vs2,fs1,vm)
  val `vmfeq_vf`: RvvInsn = RvvInsn(
    name       = "vmfeq.vf",
    extension  = "v",
    sourceToml = "v/vmfeq.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vmfeq.vv  (format: vd,vs2,vs1,vm)
  val `vmfeq_vv`: RvvInsn = RvvInsn(
    name       = "vmfeq.vv",
    extension  = "v",
    sourceToml = "v/vmfeq.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmfge.vf  (format: vd,vs2,fs1,vm)
  val `vmfge_vf`: RvvInsn = RvvInsn(
    name       = "vmfge.vf",
    extension  = "v",
    sourceToml = "v/vmfge.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vmfgt.vf  (format: vd,vs2,fs1,vm)
  val `vmfgt_vf`: RvvInsn = RvvInsn(
    name       = "vmfgt.vf",
    extension  = "v",
    sourceToml = "v/vmfgt.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vmfle.vf  (format: vd,vs2,fs1,vm)
  val `vmfle_vf`: RvvInsn = RvvInsn(
    name       = "vmfle.vf",
    extension  = "v",
    sourceToml = "v/vmfle.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vmfle.vv  (format: vd,vs2,vs1,vm)
  val `vmfle_vv`: RvvInsn = RvvInsn(
    name       = "vmfle.vv",
    extension  = "v",
    sourceToml = "v/vmfle.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmflt.vf  (format: vd,vs2,fs1,vm)
  val `vmflt_vf`: RvvInsn = RvvInsn(
    name       = "vmflt.vf",
    extension  = "v",
    sourceToml = "v/vmflt.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vmflt.vv  (format: vd,vs2,vs1,vm)
  val `vmflt_vv`: RvvInsn = RvvInsn(
    name       = "vmflt.vv",
    extension  = "v",
    sourceToml = "v/vmflt.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmfne.vf  (format: vd,vs2,fs1,vm)
  val `vmfne_vf`: RvvInsn = RvvInsn(
    name       = "vmfne.vf",
    extension  = "v",
    sourceToml = "v/vmfne.vf.toml",
    schema     = Schema.VdVs2Fs1Vm)

  // vmfne.vv  (format: vd,vs2,vs1,vm)
  val `vmfne_vv`: RvvInsn = RvvInsn(
    name       = "vmfne.vv",
    extension  = "v",
    sourceToml = "v/vmfne.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmin.vv  (format: vd,vs2,vs1,vm)
  val `vmin_vv`: RvvInsn = RvvInsn(
    name       = "vmin.vv",
    extension  = "v",
    sourceToml = "v/vmin.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmin.vx  (format: vd,vs2,rs1,vm)
  val `vmin_vx`: RvvInsn = RvvInsn(
    name       = "vmin.vx",
    extension  = "v",
    sourceToml = "v/vmin.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vminu.vv  (format: vd,vs2,vs1,vm)
  val `vminu_vv`: RvvInsn = RvvInsn(
    name       = "vminu.vv",
    extension  = "v",
    sourceToml = "v/vminu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vminu.vx  (format: vd,vs2,rs1,vm)
  val `vminu_vx`: RvvInsn = RvvInsn(
    name       = "vminu.vx",
    extension  = "v",
    sourceToml = "v/vminu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmnand.mm  (format: vd,vs2,vs1)
  val `vmnand_mm`: RvvInsn = RvvInsn(
    name       = "vmnand.mm",
    extension  = "v",
    sourceToml = "v/vmnand.mm.toml",
    schema     = Schema.VdVs2Vs1)

  // vmnor.mm  (format: vd,vs2,vs1)
  val `vmnor_mm`: RvvInsn = RvvInsn(
    name       = "vmnor.mm",
    extension  = "v",
    sourceToml = "v/vmnor.mm.toml",
    schema     = Schema.VdVs2Vs1)

  // vmor.mm  (format: vd,vs2,vs1)
  val `vmor_mm`: RvvInsn = RvvInsn(
    name       = "vmor.mm",
    extension  = "v",
    sourceToml = "v/vmor.mm.toml",
    schema     = Schema.VdVs2Vs1)

  // vmorn.mm  (format: vd,vs2,vs1)
  val `vmorn_mm`: RvvInsn = RvvInsn(
    name       = "vmorn.mm",
    extension  = "v",
    sourceToml = "v/vmorn.mm.toml",
    schema     = Schema.VdVs2Vs1)

  // vmsbc.vv  (format: vd,vs2,vs1)
  val `vmsbc_vv`: RvvInsn = RvvInsn(
    name       = "vmsbc.vv",
    extension  = "v",
    sourceToml = "v/vmsbc.vv.toml",
    schema     = Schema.VdVs2Vs1)

  // vmsbc.vvm  (format: vd,vs2,vs1,v0)
  val `vmsbc_vvm`: RvvInsn = RvvInsn(
    name       = "vmsbc.vvm",
    extension  = "v",
    sourceToml = "v/vmsbc.vvm.toml",
    schema     = Schema.VdVs2Vs1V0)

  // vmsbc.vx  (format: vd,vs2,rs1)
  val `vmsbc_vx`: RvvInsn = RvvInsn(
    name       = "vmsbc.vx",
    extension  = "v",
    sourceToml = "v/vmsbc.vx.toml",
    schema     = Schema.VdVs2Rs1)

  // vmsbc.vxm  (format: vd,vs2,rs1,v0)
  val `vmsbc_vxm`: RvvInsn = RvvInsn(
    name       = "vmsbc.vxm",
    extension  = "v",
    sourceToml = "v/vmsbc.vxm.toml",
    schema     = Schema.VdVs2Rs1V0)

  // vmsbf.m  (format: vd,vs2,vm/2)
  val `vmsbf_m`: RvvInsn = RvvInsn(
    name       = "vmsbf.m",
    extension  = "v",
    sourceToml = "v/vmsbf.m.toml",
    schema     = Schema.VdVs2VmP2)

  // vmseq.vi  (format: vd,vs2,imm,vm)
  val `vmseq_vi`: RvvInsn = RvvInsn(
    name       = "vmseq.vi",
    extension  = "v",
    sourceToml = "v/vmseq.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vmseq.vv  (format: vd,vs2,vs1,vm)
  val `vmseq_vv`: RvvInsn = RvvInsn(
    name       = "vmseq.vv",
    extension  = "v",
    sourceToml = "v/vmseq.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmseq.vx  (format: vd,vs2,rs1,vm)
  val `vmseq_vx`: RvvInsn = RvvInsn(
    name       = "vmseq.vx",
    extension  = "v",
    sourceToml = "v/vmseq.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmsgt.vi  (format: vd,vs2,imm,vm)
  val `vmsgt_vi`: RvvInsn = RvvInsn(
    name       = "vmsgt.vi",
    extension  = "v",
    sourceToml = "v/vmsgt.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vmsgt.vv  (format: vd,vs2,vs1,vm)
  val `vmsgt_vv`: RvvInsn = RvvInsn(
    name       = "vmsgt.vv",
    extension  = "v",
    sourceToml = "v/vmsgt.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmsgt.vx  (format: vd,vs2,rs1,vm)
  val `vmsgt_vx`: RvvInsn = RvvInsn(
    name       = "vmsgt.vx",
    extension  = "v",
    sourceToml = "v/vmsgt.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmsgtu.vi  (format: vd,vs2,imm,vm)
  val `vmsgtu_vi`: RvvInsn = RvvInsn(
    name       = "vmsgtu.vi",
    extension  = "v",
    sourceToml = "v/vmsgtu.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vmsgtu.vv  (format: vd,vs2,vs1,vm)
  val `vmsgtu_vv`: RvvInsn = RvvInsn(
    name       = "vmsgtu.vv",
    extension  = "v",
    sourceToml = "v/vmsgtu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmsgtu.vx  (format: vd,vs2,rs1,vm)
  val `vmsgtu_vx`: RvvInsn = RvvInsn(
    name       = "vmsgtu.vx",
    extension  = "v",
    sourceToml = "v/vmsgtu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmsif.m  (format: vd,vs2,vm/2)
  val `vmsif_m`: RvvInsn = RvvInsn(
    name       = "vmsif.m",
    extension  = "v",
    sourceToml = "v/vmsif.m.toml",
    schema     = Schema.VdVs2VmP2)

  // vmsle.vi  (format: vd,vs2,imm,vm)
  val `vmsle_vi`: RvvInsn = RvvInsn(
    name       = "vmsle.vi",
    extension  = "v",
    sourceToml = "v/vmsle.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vmsle.vv  (format: vd,vs2,vs1,vm)
  val `vmsle_vv`: RvvInsn = RvvInsn(
    name       = "vmsle.vv",
    extension  = "v",
    sourceToml = "v/vmsle.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmsle.vx  (format: vd,vs2,rs1,vm)
  val `vmsle_vx`: RvvInsn = RvvInsn(
    name       = "vmsle.vx",
    extension  = "v",
    sourceToml = "v/vmsle.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmsleu.vi  (format: vd,vs2,imm,vm)
  val `vmsleu_vi`: RvvInsn = RvvInsn(
    name       = "vmsleu.vi",
    extension  = "v",
    sourceToml = "v/vmsleu.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vmsleu.vv  (format: vd,vs2,vs1,vm)
  val `vmsleu_vv`: RvvInsn = RvvInsn(
    name       = "vmsleu.vv",
    extension  = "v",
    sourceToml = "v/vmsleu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmsleu.vx  (format: vd,vs2,rs1,vm)
  val `vmsleu_vx`: RvvInsn = RvvInsn(
    name       = "vmsleu.vx",
    extension  = "v",
    sourceToml = "v/vmsleu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmslt.vv  (format: vd,vs2,vs1,vm)
  val `vmslt_vv`: RvvInsn = RvvInsn(
    name       = "vmslt.vv",
    extension  = "v",
    sourceToml = "v/vmslt.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmslt.vx  (format: vd,vs2,rs1,vm)
  val `vmslt_vx`: RvvInsn = RvvInsn(
    name       = "vmslt.vx",
    extension  = "v",
    sourceToml = "v/vmslt.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmsltu.vv  (format: vd,vs2,vs1,vm)
  val `vmsltu_vv`: RvvInsn = RvvInsn(
    name       = "vmsltu.vv",
    extension  = "v",
    sourceToml = "v/vmsltu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmsltu.vx  (format: vd,vs2,rs1,vm)
  val `vmsltu_vx`: RvvInsn = RvvInsn(
    name       = "vmsltu.vx",
    extension  = "v",
    sourceToml = "v/vmsltu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmsne.vi  (format: vd,vs2,imm,vm)
  val `vmsne_vi`: RvvInsn = RvvInsn(
    name       = "vmsne.vi",
    extension  = "v",
    sourceToml = "v/vmsne.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vmsne.vv  (format: vd,vs2,vs1,vm)
  val `vmsne_vv`: RvvInsn = RvvInsn(
    name       = "vmsne.vv",
    extension  = "v",
    sourceToml = "v/vmsne.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmsne.vx  (format: vd,vs2,rs1,vm)
  val `vmsne_vx`: RvvInsn = RvvInsn(
    name       = "vmsne.vx",
    extension  = "v",
    sourceToml = "v/vmsne.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmsof.m  (format: vd,vs2,vm/2)
  val `vmsof_m`: RvvInsn = RvvInsn(
    name       = "vmsof.m",
    extension  = "v",
    sourceToml = "v/vmsof.m.toml",
    schema     = Schema.VdVs2VmP2)

  // vmul.vv  (format: vd,vs2,vs1,vm)
  val `vmul_vv`: RvvInsn = RvvInsn(
    name       = "vmul.vv",
    extension  = "v",
    sourceToml = "v/vmul.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmul.vx  (format: vd,vs2,rs1,vm)
  val `vmul_vx`: RvvInsn = RvvInsn(
    name       = "vmul.vx",
    extension  = "v",
    sourceToml = "v/vmul.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmulh.vv  (format: vd,vs2,vs1,vm)
  val `vmulh_vv`: RvvInsn = RvvInsn(
    name       = "vmulh.vv",
    extension  = "v",
    sourceToml = "v/vmulh.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmulh.vx  (format: vd,vs2,rs1,vm)
  val `vmulh_vx`: RvvInsn = RvvInsn(
    name       = "vmulh.vx",
    extension  = "v",
    sourceToml = "v/vmulh.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmulhsu.vv  (format: vd,vs2,vs1,vm)
  val `vmulhsu_vv`: RvvInsn = RvvInsn(
    name       = "vmulhsu.vv",
    extension  = "v",
    sourceToml = "v/vmulhsu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmulhsu.vx  (format: vd,vs2,rs1,vm)
  val `vmulhsu_vx`: RvvInsn = RvvInsn(
    name       = "vmulhsu.vx",
    extension  = "v",
    sourceToml = "v/vmulhsu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmulhu.vv  (format: vd,vs2,vs1,vm)
  val `vmulhu_vv`: RvvInsn = RvvInsn(
    name       = "vmulhu.vv",
    extension  = "v",
    sourceToml = "v/vmulhu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vmulhu.vx  (format: vd,vs2,rs1,vm)
  val `vmulhu_vx`: RvvInsn = RvvInsn(
    name       = "vmulhu.vx",
    extension  = "v",
    sourceToml = "v/vmulhu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vmv.s.x  (format: vd,rs1)
  val `vmv_s_x`: RvvInsn = RvvInsn(
    name       = "vmv.s.x",
    extension  = "v",
    sourceToml = "v/vmv.s.x.toml",
    schema     = Schema.VdRs1)

  // vmv.v.i  (format: vd,imm)
  val `vmv_v_i`: RvvInsn = RvvInsn(
    name       = "vmv.v.i",
    extension  = "v",
    sourceToml = "v/vmv.v.i.toml",
    schema     = Schema.VdImm)

  // vmv.v.v  (format: vd,vs1)
  val `vmv_v_v`: RvvInsn = RvvInsn(
    name       = "vmv.v.v",
    extension  = "v",
    sourceToml = "v/vmv.v.v.toml",
    schema     = Schema.VdVs1)

  // vmv.v.x  (format: vd,rs1)
  val `vmv_v_x`: RvvInsn = RvvInsn(
    name       = "vmv.v.x",
    extension  = "v",
    sourceToml = "v/vmv.v.x.toml",
    schema     = Schema.VdRs1)

  // vmv.x.s  (format: rd,vs2)
  val `vmv_x_s`: RvvInsn = RvvInsn(
    name       = "vmv.x.s",
    extension  = "v",
    sourceToml = "v/vmv.x.s.toml",
    schema     = Schema.RdVs2)

  // vmv1r.v  (format: vd,vs2)
  val `vmv1r_v`: RvvInsn = RvvInsn(
    name       = "vmv1r.v",
    extension  = "v",
    sourceToml = "v/vmv1r.v.toml",
    schema     = Schema.VdVs2)

  // vmv2r.v  (format: vd,vs2)
  val `vmv2r_v`: RvvInsn = RvvInsn(
    name       = "vmv2r.v",
    extension  = "v",
    sourceToml = "v/vmv2r.v.toml",
    schema     = Schema.VdVs2)

  // vmv4r.v  (format: vd,vs2)
  val `vmv4r_v`: RvvInsn = RvvInsn(
    name       = "vmv4r.v",
    extension  = "v",
    sourceToml = "v/vmv4r.v.toml",
    schema     = Schema.VdVs2)

  // vmv8r.v  (format: vd,vs2)
  val `vmv8r_v`: RvvInsn = RvvInsn(
    name       = "vmv8r.v",
    extension  = "v",
    sourceToml = "v/vmv8r.v.toml",
    schema     = Schema.VdVs2)

  // vmxnor.mm  (format: vd,vs2,vs1)
  val `vmxnor_mm`: RvvInsn = RvvInsn(
    name       = "vmxnor.mm",
    extension  = "v",
    sourceToml = "v/vmxnor.mm.toml",
    schema     = Schema.VdVs2Vs1)

  // vmxor.mm  (format: vd,vs2,vs1)
  val `vmxor_mm`: RvvInsn = RvvInsn(
    name       = "vmxor.mm",
    extension  = "v",
    sourceToml = "v/vmxor.mm.toml",
    schema     = Schema.VdVs2Vs1)

  // vnclip.wi  (format: vd,vs2,uimm,vm)
  val `vnclip_wi`: RvvInsn = RvvInsn(
    name       = "vnclip.wi",
    extension  = "v",
    sourceToml = "v/vnclip.wi.toml",
    schema     = Schema.VdVs2UimmVm,
    vxrm = true,
    vxsat = true)

  // vnclip.wv  (format: vd,vs2,vs1,vm)
  val `vnclip_wv`: RvvInsn = RvvInsn(
    name       = "vnclip.wv",
    extension  = "v",
    sourceToml = "v/vnclip.wv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true,
    vxsat = true)

  // vnclip.wx  (format: vd,vs2,rs1,vm)
  val `vnclip_wx`: RvvInsn = RvvInsn(
    name       = "vnclip.wx",
    extension  = "v",
    sourceToml = "v/vnclip.wx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true,
    vxsat = true)

  // vnclipu.wi  (format: vd,vs2,uimm,vm)
  val `vnclipu_wi`: RvvInsn = RvvInsn(
    name       = "vnclipu.wi",
    extension  = "v",
    sourceToml = "v/vnclipu.wi.toml",
    schema     = Schema.VdVs2UimmVm,
    vxrm = true,
    vxsat = true)

  // vnclipu.wv  (format: vd,vs2,vs1,vm)
  val `vnclipu_wv`: RvvInsn = RvvInsn(
    name       = "vnclipu.wv",
    extension  = "v",
    sourceToml = "v/vnclipu.wv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true,
    vxsat = true)

  // vnclipu.wx  (format: vd,vs2,rs1,vm)
  val `vnclipu_wx`: RvvInsn = RvvInsn(
    name       = "vnclipu.wx",
    extension  = "v",
    sourceToml = "v/vnclipu.wx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true,
    vxsat = true)

  // vnmsac.vv  (format: vd,vs1,vs2,vm)
  val `vnmsac_vv`: RvvInsn = RvvInsn(
    name       = "vnmsac.vv",
    extension  = "v",
    sourceToml = "v/vnmsac.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vnmsac.vx  (format: vd,rs1,vs2,vm)
  val `vnmsac_vx`: RvvInsn = RvvInsn(
    name       = "vnmsac.vx",
    extension  = "v",
    sourceToml = "v/vnmsac.vx.toml",
    schema     = Schema.VdRs1Vs2Vm)

  // vnmsub.vv  (format: vd,vs1,vs2,vm)
  val `vnmsub_vv`: RvvInsn = RvvInsn(
    name       = "vnmsub.vv",
    extension  = "v",
    sourceToml = "v/vnmsub.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  // vnmsub.vx  (format: vd,rs1,vs2,vm)
  val `vnmsub_vx`: RvvInsn = RvvInsn(
    name       = "vnmsub.vx",
    extension  = "v",
    sourceToml = "v/vnmsub.vx.toml",
    schema     = Schema.VdRs1Vs2Vm)

  // vnsra.wi  (format: vd,vs2,uimm,vm)
  val `vnsra_wi`: RvvInsn = RvvInsn(
    name       = "vnsra.wi",
    extension  = "v",
    sourceToml = "v/vnsra.wi.toml",
    schema     = Schema.VdVs2UimmVm)

  // vnsra.wv  (format: vd,vs2,vs1,vm)
  val `vnsra_wv`: RvvInsn = RvvInsn(
    name       = "vnsra.wv",
    extension  = "v",
    sourceToml = "v/vnsra.wv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vnsra.wx  (format: vd,vs2,rs1,vm)
  val `vnsra_wx`: RvvInsn = RvvInsn(
    name       = "vnsra.wx",
    extension  = "v",
    sourceToml = "v/vnsra.wx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vnsrl.wi  (format: vd,vs2,uimm,vm)
  val `vnsrl_wi`: RvvInsn = RvvInsn(
    name       = "vnsrl.wi",
    extension  = "v",
    sourceToml = "v/vnsrl.wi.toml",
    schema     = Schema.VdVs2UimmVm)

  // vnsrl.wv  (format: vd,vs2,vs1,vm)
  val `vnsrl_wv`: RvvInsn = RvvInsn(
    name       = "vnsrl.wv",
    extension  = "v",
    sourceToml = "v/vnsrl.wv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vnsrl.wx  (format: vd,vs2,rs1,vm)
  val `vnsrl_wx`: RvvInsn = RvvInsn(
    name       = "vnsrl.wx",
    extension  = "v",
    sourceToml = "v/vnsrl.wx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vor.vi  (format: vd,vs2,imm,vm)
  val `vor_vi`: RvvInsn = RvvInsn(
    name       = "vor.vi",
    extension  = "v",
    sourceToml = "v/vor.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vor.vv  (format: vd,vs2,vs1,vm)
  val `vor_vv`: RvvInsn = RvvInsn(
    name       = "vor.vv",
    extension  = "v",
    sourceToml = "v/vor.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vor.vx  (format: vd,vs2,rs1,vm)
  val `vor_vx`: RvvInsn = RvvInsn(
    name       = "vor.vx",
    extension  = "v",
    sourceToml = "v/vor.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vredand.vs  (format: vd,vs2,vs1,vm)
  val `vredand_vs`: RvvInsn = RvvInsn(
    name       = "vredand.vs",
    extension  = "v",
    sourceToml = "v/vredand.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vredmax.vs  (format: vd,vs2,vs1,vm)
  val `vredmax_vs`: RvvInsn = RvvInsn(
    name       = "vredmax.vs",
    extension  = "v",
    sourceToml = "v/vredmax.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  val chunkAll: List[RvvInsn] = List(
    `vmadc_vx`,
    `vmadc_vxm`,
    `vmadd_vv`,
    `vmadd_vx`,
    `vmand_mm`,
    `vmandn_mm`,
    `vmax_vv`,
    `vmax_vx`,
    `vmaxu_vv`,
    `vmaxu_vx`,
    `vmerge_vim`,
    `vmerge_vvm`,
    `vmerge_vxm`,
    `vmfeq_vf`,
    `vmfeq_vv`,
    `vmfge_vf`,
    `vmfgt_vf`,
    `vmfle_vf`,
    `vmfle_vv`,
    `vmflt_vf`,
    `vmflt_vv`,
    `vmfne_vf`,
    `vmfne_vv`,
    `vmin_vv`,
    `vmin_vx`,
    `vminu_vv`,
    `vminu_vx`,
    `vmnand_mm`,
    `vmnor_mm`,
    `vmor_mm`,
    `vmorn_mm`,
    `vmsbc_vv`,
    `vmsbc_vvm`,
    `vmsbc_vx`,
    `vmsbc_vxm`,
    `vmsbf_m`,
    `vmseq_vi`,
    `vmseq_vv`,
    `vmseq_vx`,
    `vmsgt_vi`,
    `vmsgt_vv`,
    `vmsgt_vx`,
    `vmsgtu_vi`,
    `vmsgtu_vv`,
    `vmsgtu_vx`,
    `vmsif_m`,
    `vmsle_vi`,
    `vmsle_vv`,
    `vmsle_vx`,
    `vmsleu_vi`,
    `vmsleu_vv`,
    `vmsleu_vx`,
    `vmslt_vv`,
    `vmslt_vx`,
    `vmsltu_vv`,
    `vmsltu_vx`,
    `vmsne_vi`,
    `vmsne_vv`,
    `vmsne_vx`,
    `vmsof_m`,
    `vmul_vv`,
    `vmul_vx`,
    `vmulh_vv`,
    `vmulh_vx`,
    `vmulhsu_vv`,
    `vmulhsu_vx`,
    `vmulhu_vv`,
    `vmulhu_vx`,
    `vmv_s_x`,
    `vmv_v_i`,
    `vmv_v_v`,
    `vmv_v_x`,
    `vmv_x_s`,
    `vmv1r_v`,
    `vmv2r_v`,
    `vmv4r_v`,
    `vmv8r_v`,
    `vmxnor_mm`,
    `vmxor_mm`,
    `vnclip_wi`,
    `vnclip_wv`,
    `vnclip_wx`,
    `vnclipu_wi`,
    `vnclipu_wv`,
    `vnclipu_wx`,
    `vnmsac_vv`,
    `vnmsac_vx`,
    `vnmsub_vv`,
    `vnmsub_vx`,
    `vnsra_wi`,
    `vnsra_wv`,
    `vnsra_wx`,
    `vnsrl_wi`,
    `vnsrl_wv`,
    `vnsrl_wx`,
    `vor_vi`,
    `vor_vv`,
    `vor_vx`,
    `vredand_vs`,
    `vredmax_vs`
  )
