// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/v/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 100 RvvInsn declarations for `v` (chunk 4). */
object V4:
  // vredmaxu.vs  (format: vd,vs2,vs1,vm)
  val `vredmaxu_vs`: RvvInsn = RvvInsn(
    name       = "vredmaxu.vs",
    extension  = "v",
    sourceToml = "v/vredmaxu.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vredmin.vs  (format: vd,vs2,vs1,vm)
  val `vredmin_vs`: RvvInsn = RvvInsn(
    name       = "vredmin.vs",
    extension  = "v",
    sourceToml = "v/vredmin.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vredminu.vs  (format: vd,vs2,vs1,vm)
  val `vredminu_vs`: RvvInsn = RvvInsn(
    name       = "vredminu.vs",
    extension  = "v",
    sourceToml = "v/vredminu.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vredor.vs  (format: vd,vs2,vs1,vm)
  val `vredor_vs`: RvvInsn = RvvInsn(
    name       = "vredor.vs",
    extension  = "v",
    sourceToml = "v/vredor.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vredsum.vs  (format: vd,vs2,vs1,vm)
  val `vredsum_vs`: RvvInsn = RvvInsn(
    name       = "vredsum.vs",
    extension  = "v",
    sourceToml = "v/vredsum.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vredxor.vs  (format: vd,vs2,vs1,vm)
  val `vredxor_vs`: RvvInsn = RvvInsn(
    name       = "vredxor.vs",
    extension  = "v",
    sourceToml = "v/vredxor.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vrem.vv  (format: vd,vs2,vs1,vm)
  val `vrem_vv`: RvvInsn = RvvInsn(
    name       = "vrem.vv",
    extension  = "v",
    sourceToml = "v/vrem.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vrem.vx  (format: vd,vs2,rs1,vm)
  val `vrem_vx`: RvvInsn = RvvInsn(
    name       = "vrem.vx",
    extension  = "v",
    sourceToml = "v/vrem.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vremu.vv  (format: vd,vs2,vs1,vm)
  val `vremu_vv`: RvvInsn = RvvInsn(
    name       = "vremu.vv",
    extension  = "v",
    sourceToml = "v/vremu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vremu.vx  (format: vd,vs2,rs1,vm)
  val `vremu_vx`: RvvInsn = RvvInsn(
    name       = "vremu.vx",
    extension  = "v",
    sourceToml = "v/vremu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vrgather.vi  (format: vd,vs2,uimm,vm)
  val `vrgather_vi`: RvvInsn = RvvInsn(
    name       = "vrgather.vi",
    extension  = "v",
    sourceToml = "v/vrgather.vi.toml",
    schema     = Schema.VdVs2UimmVm)

  // vrgather.vv  (format: vd,vs2,vs1,vm)
  val `vrgather_vv`: RvvInsn = RvvInsn(
    name       = "vrgather.vv",
    extension  = "v",
    sourceToml = "v/vrgather.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vrgather.vx  (format: vd,vs2,rs1,vm)
  val `vrgather_vx`: RvvInsn = RvvInsn(
    name       = "vrgather.vx",
    extension  = "v",
    sourceToml = "v/vrgather.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vrgatherei16.vv  (format: vd,vs2,vs1,vm)
  val `vrgatherei16_vv`: RvvInsn = RvvInsn(
    name       = "vrgatherei16.vv",
    extension  = "v",
    sourceToml = "v/vrgatherei16.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vrsub.vi  (format: vd,vs2,imm,vm)
  val `vrsub_vi`: RvvInsn = RvvInsn(
    name       = "vrsub.vi",
    extension  = "v",
    sourceToml = "v/vrsub.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vrsub.vx  (format: vd,vs2,rs1,vm)
  val `vrsub_vx`: RvvInsn = RvvInsn(
    name       = "vrsub.vx",
    extension  = "v",
    sourceToml = "v/vrsub.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vs1r.v  (format: vs3,(rs1))
  val `vs1r_v`: RvvInsn = RvvInsn(
    name       = "vs1r.v",
    extension  = "v",
    sourceToml = "v/vs1r.v.toml",
    schema     = Schema.Vs3Rs1m)

  // vs2r.v  (format: vs3,(rs1))
  val `vs2r_v`: RvvInsn = RvvInsn(
    name       = "vs2r.v",
    extension  = "v",
    sourceToml = "v/vs2r.v.toml",
    schema     = Schema.Vs3Rs1m)

  // vs4r.v  (format: vs3,(rs1))
  val `vs4r_v`: RvvInsn = RvvInsn(
    name       = "vs4r.v",
    extension  = "v",
    sourceToml = "v/vs4r.v.toml",
    schema     = Schema.Vs3Rs1m)

  // vs8r.v  (format: vs3,(rs1))
  val `vs8r_v`: RvvInsn = RvvInsn(
    name       = "vs8r.v",
    extension  = "v",
    sourceToml = "v/vs8r.v.toml",
    schema     = Schema.Vs3Rs1m)

  // vsadd.vi  (format: vd,vs2,imm,vm)
  val `vsadd_vi`: RvvInsn = RvvInsn(
    name       = "vsadd.vi",
    extension  = "v",
    sourceToml = "v/vsadd.vi.toml",
    schema     = Schema.VdVs2ImmVm,
    vxsat = true)

  // vsadd.vv  (format: vd,vs2,vs1,vm)
  val `vsadd_vv`: RvvInsn = RvvInsn(
    name       = "vsadd.vv",
    extension  = "v",
    sourceToml = "v/vsadd.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxsat = true)

  // vsadd.vx  (format: vd,vs2,rs1,vm)
  val `vsadd_vx`: RvvInsn = RvvInsn(
    name       = "vsadd.vx",
    extension  = "v",
    sourceToml = "v/vsadd.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxsat = true)

  // vsaddu.vi  (format: vd,vs2,imm,vm)
  val `vsaddu_vi`: RvvInsn = RvvInsn(
    name       = "vsaddu.vi",
    extension  = "v",
    sourceToml = "v/vsaddu.vi.toml",
    schema     = Schema.VdVs2ImmVm,
    vxsat = true)

  // vsaddu.vv  (format: vd,vs2,vs1,vm)
  val `vsaddu_vv`: RvvInsn = RvvInsn(
    name       = "vsaddu.vv",
    extension  = "v",
    sourceToml = "v/vsaddu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxsat = true)

  // vsaddu.vx  (format: vd,vs2,rs1,vm)
  val `vsaddu_vx`: RvvInsn = RvvInsn(
    name       = "vsaddu.vx",
    extension  = "v",
    sourceToml = "v/vsaddu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxsat = true)

  // vsbc.vvm  (format: vd,vs2,vs1,v0)
  val `vsbc_vvm`: RvvInsn = RvvInsn(
    name       = "vsbc.vvm",
    extension  = "v",
    sourceToml = "v/vsbc.vvm.toml",
    schema     = Schema.VdVs2Vs1V0)

  // vsbc.vxm  (format: vd,vs2,rs1,v0)
  val `vsbc_vxm`: RvvInsn = RvvInsn(
    name       = "vsbc.vxm",
    extension  = "v",
    sourceToml = "v/vsbc.vxm.toml",
    schema     = Schema.VdVs2Rs1V0)

  // vse16.v  (format: vs3,(rs1),vm)
  val `vse16_v`: RvvInsn = RvvInsn(
    name       = "vse16.v",
    extension  = "v",
    sourceToml = "v/vse16.v.toml",
    schema     = Schema.Vs3Rs1mVm)

  // vse32.v  (format: vs3,(rs1),vm)
  val `vse32_v`: RvvInsn = RvvInsn(
    name       = "vse32.v",
    extension  = "v",
    sourceToml = "v/vse32.v.toml",
    schema     = Schema.Vs3Rs1mVm)

  // vse64.v  (format: vs3,(rs1),vm)
  val `vse64_v`: RvvInsn = RvvInsn(
    name       = "vse64.v",
    extension  = "v",
    sourceToml = "v/vse64.v.toml",
    schema     = Schema.Vs3Rs1mVm)

  // vse8.v  (format: vs3,(rs1),vm)
  val `vse8_v`: RvvInsn = RvvInsn(
    name       = "vse8.v",
    extension  = "v",
    sourceToml = "v/vse8.v.toml",
    schema     = Schema.Vs3Rs1mVm)

  // vsetivli  (format: vsetivli)
  val `vsetivli`: RvvInsn = RvvInsn(
    name       = "vsetivli",
    extension  = "v",
    sourceToml = "v/vsetivli.toml",
    schema     = Schema.Vsetivli)

  // vsetvl  (format: vsetvl)
  val `vsetvl`: RvvInsn = RvvInsn(
    name       = "vsetvl",
    extension  = "v",
    sourceToml = "v/vsetvl.toml",
    schema     = Schema.Vsetvl)

  // vsetvli  (format: vsetvli)
  val `vsetvli`: RvvInsn = RvvInsn(
    name       = "vsetvli",
    extension  = "v",
    sourceToml = "v/vsetvli.toml",
    schema     = Schema.Vsetvli)

  // vsext.vf2  (format: vd,vs2,vm/3)
  val `vsext_vf2`: RvvInsn = RvvInsn(
    name       = "vsext.vf2",
    extension  = "v",
    sourceToml = "v/vsext.vf2.toml",
    schema     = Schema.VdVs2VmP3)

  // vsext.vf4  (format: vd,vs2,vm/3)
  val `vsext_vf4`: RvvInsn = RvvInsn(
    name       = "vsext.vf4",
    extension  = "v",
    sourceToml = "v/vsext.vf4.toml",
    schema     = Schema.VdVs2VmP3)

  // vsext.vf8  (format: vd,vs2,vm/3)
  val `vsext_vf8`: RvvInsn = RvvInsn(
    name       = "vsext.vf8",
    extension  = "v",
    sourceToml = "v/vsext.vf8.toml",
    schema     = Schema.VdVs2VmP3)

  // vslide1down.vx  (format: vd,vs2,rs1,vm)
  val `vslide1down_vx`: RvvInsn = RvvInsn(
    name       = "vslide1down.vx",
    extension  = "v",
    sourceToml = "v/vslide1down.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vslide1up.vx  (format: vd,vs2,rs1,vm)
  val `vslide1up_vx`: RvvInsn = RvvInsn(
    name       = "vslide1up.vx",
    extension  = "v",
    sourceToml = "v/vslide1up.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vslidedown.vi  (format: vd,vs2,uimm,vm)
  val `vslidedown_vi`: RvvInsn = RvvInsn(
    name       = "vslidedown.vi",
    extension  = "v",
    sourceToml = "v/vslidedown.vi.toml",
    schema     = Schema.VdVs2UimmVm)

  // vslidedown.vx  (format: vd,vs2,rs1,vm)
  val `vslidedown_vx`: RvvInsn = RvvInsn(
    name       = "vslidedown.vx",
    extension  = "v",
    sourceToml = "v/vslidedown.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vslideup.vi  (format: vd,vs2,uimm,vm)
  val `vslideup_vi`: RvvInsn = RvvInsn(
    name       = "vslideup.vi",
    extension  = "v",
    sourceToml = "v/vslideup.vi.toml",
    schema     = Schema.VdVs2UimmVm)

  // vslideup.vx  (format: vd,vs2,rs1,vm)
  val `vslideup_vx`: RvvInsn = RvvInsn(
    name       = "vslideup.vx",
    extension  = "v",
    sourceToml = "v/vslideup.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vsll.vi  (format: vd,vs2,uimm,vm)
  val `vsll_vi`: RvvInsn = RvvInsn(
    name       = "vsll.vi",
    extension  = "v",
    sourceToml = "v/vsll.vi.toml",
    schema     = Schema.VdVs2UimmVm)

  // vsll.vv  (format: vd,vs2,vs1,vm)
  val `vsll_vv`: RvvInsn = RvvInsn(
    name       = "vsll.vv",
    extension  = "v",
    sourceToml = "v/vsll.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vsll.vx  (format: vd,vs2,rs1,vm)
  val `vsll_vx`: RvvInsn = RvvInsn(
    name       = "vsll.vx",
    extension  = "v",
    sourceToml = "v/vsll.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vsm.v  (format: vs3,(rs1))
  val `vsm_v`: RvvInsn = RvvInsn(
    name       = "vsm.v",
    extension  = "v",
    sourceToml = "v/vsm.v.toml",
    schema     = Schema.Vs3Rs1m)

  // vsmul.vv  (format: vd,vs2,vs1,vm)
  val `vsmul_vv`: RvvInsn = RvvInsn(
    name       = "vsmul.vv",
    extension  = "v",
    sourceToml = "v/vsmul.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true,
    vxsat = true)

  // vsmul.vx  (format: vd,vs2,rs1,vm)
  val `vsmul_vx`: RvvInsn = RvvInsn(
    name       = "vsmul.vx",
    extension  = "v",
    sourceToml = "v/vsmul.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true,
    vxsat = true)

  // vsoxei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxei16_v`: RvvInsn = RvvInsn(
    name       = "vsoxei16.v",
    extension  = "v",
    sourceToml = "v/vsoxei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16))

  // vsoxei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxei32_v`: RvvInsn = RvvInsn(
    name       = "vsoxei32.v",
    extension  = "v",
    sourceToml = "v/vsoxei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32))

  // vsoxei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxei64_v`: RvvInsn = RvvInsn(
    name       = "vsoxei64.v",
    extension  = "v",
    sourceToml = "v/vsoxei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64))

  // vsoxei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxei8_v`: RvvInsn = RvvInsn(
    name       = "vsoxei8.v",
    extension  = "v",
    sourceToml = "v/vsoxei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8))

  // vsoxseg2ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg2ei16_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg2ei16.v",
    extension  = "v",
    sourceToml = "v/vsoxseg2ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg2ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg2ei32_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg2ei32.v",
    extension  = "v",
    sourceToml = "v/vsoxseg2ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg2ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg2ei64_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg2ei64.v",
    extension  = "v",
    sourceToml = "v/vsoxseg2ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg2ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg2ei8_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg2ei8.v",
    extension  = "v",
    sourceToml = "v/vsoxseg2ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg3ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg3ei16_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg3ei16.v",
    extension  = "v",
    sourceToml = "v/vsoxseg3ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg3ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg3ei32_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg3ei32.v",
    extension  = "v",
    sourceToml = "v/vsoxseg3ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg3ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg3ei64_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg3ei64.v",
    extension  = "v",
    sourceToml = "v/vsoxseg3ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg3ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg3ei8_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg3ei8.v",
    extension  = "v",
    sourceToml = "v/vsoxseg3ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg4ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg4ei16_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg4ei16.v",
    extension  = "v",
    sourceToml = "v/vsoxseg4ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg4ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg4ei32_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg4ei32.v",
    extension  = "v",
    sourceToml = "v/vsoxseg4ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg4ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg4ei64_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg4ei64.v",
    extension  = "v",
    sourceToml = "v/vsoxseg4ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg4ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg4ei8_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg4ei8.v",
    extension  = "v",
    sourceToml = "v/vsoxseg4ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg5ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg5ei16_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg5ei16.v",
    extension  = "v",
    sourceToml = "v/vsoxseg5ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg5ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg5ei32_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg5ei32.v",
    extension  = "v",
    sourceToml = "v/vsoxseg5ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg5ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg5ei64_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg5ei64.v",
    extension  = "v",
    sourceToml = "v/vsoxseg5ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg5ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg5ei8_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg5ei8.v",
    extension  = "v",
    sourceToml = "v/vsoxseg5ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg6ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg6ei16_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg6ei16.v",
    extension  = "v",
    sourceToml = "v/vsoxseg6ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg6ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg6ei32_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg6ei32.v",
    extension  = "v",
    sourceToml = "v/vsoxseg6ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg6ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg6ei64_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg6ei64.v",
    extension  = "v",
    sourceToml = "v/vsoxseg6ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg6ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg6ei8_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg6ei8.v",
    extension  = "v",
    sourceToml = "v/vsoxseg6ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg7ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg7ei16_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg7ei16.v",
    extension  = "v",
    sourceToml = "v/vsoxseg7ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg7ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg7ei32_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg7ei32.v",
    extension  = "v",
    sourceToml = "v/vsoxseg7ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg7ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg7ei64_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg7ei64.v",
    extension  = "v",
    sourceToml = "v/vsoxseg7ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg7ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg7ei8_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg7ei8.v",
    extension  = "v",
    sourceToml = "v/vsoxseg7ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg8ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg8ei16_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg8ei16.v",
    extension  = "v",
    sourceToml = "v/vsoxseg8ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg8ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg8ei32_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg8ei32.v",
    extension  = "v",
    sourceToml = "v/vsoxseg8ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg8ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg8ei64_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg8ei64.v",
    extension  = "v",
    sourceToml = "v/vsoxseg8ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsoxseg8ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsoxseg8ei8_v`: RvvInsn = RvvInsn(
    name       = "vsoxseg8ei8.v",
    extension  = "v",
    sourceToml = "v/vsoxseg8ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm)

  // vsra.vi  (format: vd,vs2,uimm,vm)
  val `vsra_vi`: RvvInsn = RvvInsn(
    name       = "vsra.vi",
    extension  = "v",
    sourceToml = "v/vsra.vi.toml",
    schema     = Schema.VdVs2UimmVm)

  // vsra.vv  (format: vd,vs2,vs1,vm)
  val `vsra_vv`: RvvInsn = RvvInsn(
    name       = "vsra.vv",
    extension  = "v",
    sourceToml = "v/vsra.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vsra.vx  (format: vd,vs2,rs1,vm)
  val `vsra_vx`: RvvInsn = RvvInsn(
    name       = "vsra.vx",
    extension  = "v",
    sourceToml = "v/vsra.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vsrl.vi  (format: vd,vs2,uimm,vm)
  val `vsrl_vi`: RvvInsn = RvvInsn(
    name       = "vsrl.vi",
    extension  = "v",
    sourceToml = "v/vsrl.vi.toml",
    schema     = Schema.VdVs2UimmVm)

  // vsrl.vv  (format: vd,vs2,vs1,vm)
  val `vsrl_vv`: RvvInsn = RvvInsn(
    name       = "vsrl.vv",
    extension  = "v",
    sourceToml = "v/vsrl.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vsrl.vx  (format: vd,vs2,rs1,vm)
  val `vsrl_vx`: RvvInsn = RvvInsn(
    name       = "vsrl.vx",
    extension  = "v",
    sourceToml = "v/vsrl.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vsse16.v  (format: vs3,(rs1),rs2,vm)
  val `vsse16_v`: RvvInsn = RvvInsn(
    name       = "vsse16.v",
    extension  = "v",
    sourceToml = "v/vsse16.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm)

  // vsse32.v  (format: vs3,(rs1),rs2,vm)
  val `vsse32_v`: RvvInsn = RvvInsn(
    name       = "vsse32.v",
    extension  = "v",
    sourceToml = "v/vsse32.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm)

  // vsse64.v  (format: vs3,(rs1),rs2,vm)
  val `vsse64_v`: RvvInsn = RvvInsn(
    name       = "vsse64.v",
    extension  = "v",
    sourceToml = "v/vsse64.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm)

  // vsse8.v  (format: vs3,(rs1),rs2,vm)
  val `vsse8_v`: RvvInsn = RvvInsn(
    name       = "vsse8.v",
    extension  = "v",
    sourceToml = "v/vsse8.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm)

  // vsseg2e16.v  (format: vs3,(rs1),vm)
  val `vsseg2e16_v`: RvvInsn = RvvInsn(
    name       = "vsseg2e16.v",
    extension  = "v",
    sourceToml = "v/vsseg2e16.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 2)

  // vsseg2e32.v  (format: vs3,(rs1),vm)
  val `vsseg2e32_v`: RvvInsn = RvvInsn(
    name       = "vsseg2e32.v",
    extension  = "v",
    sourceToml = "v/vsseg2e32.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 2)

  // vsseg2e64.v  (format: vs3,(rs1),vm)
  val `vsseg2e64_v`: RvvInsn = RvvInsn(
    name       = "vsseg2e64.v",
    extension  = "v",
    sourceToml = "v/vsseg2e64.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 2)

  // vsseg2e8.v  (format: vs3,(rs1),vm)
  val `vsseg2e8_v`: RvvInsn = RvvInsn(
    name       = "vsseg2e8.v",
    extension  = "v",
    sourceToml = "v/vsseg2e8.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 2)

  // vsseg3e16.v  (format: vs3,(rs1),vm)
  val `vsseg3e16_v`: RvvInsn = RvvInsn(
    name       = "vsseg3e16.v",
    extension  = "v",
    sourceToml = "v/vsseg3e16.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 3)

  // vsseg3e32.v  (format: vs3,(rs1),vm)
  val `vsseg3e32_v`: RvvInsn = RvvInsn(
    name       = "vsseg3e32.v",
    extension  = "v",
    sourceToml = "v/vsseg3e32.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 3)

  // vsseg3e64.v  (format: vs3,(rs1),vm)
  val `vsseg3e64_v`: RvvInsn = RvvInsn(
    name       = "vsseg3e64.v",
    extension  = "v",
    sourceToml = "v/vsseg3e64.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 3)

  // vsseg3e8.v  (format: vs3,(rs1),vm)
  val `vsseg3e8_v`: RvvInsn = RvvInsn(
    name       = "vsseg3e8.v",
    extension  = "v",
    sourceToml = "v/vsseg3e8.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 3)

  val chunkAll: List[RvvInsn] = List(
    `vredmaxu_vs`,
    `vredmin_vs`,
    `vredminu_vs`,
    `vredor_vs`,
    `vredsum_vs`,
    `vredxor_vs`,
    `vrem_vv`,
    `vrem_vx`,
    `vremu_vv`,
    `vremu_vx`,
    `vrgather_vi`,
    `vrgather_vv`,
    `vrgather_vx`,
    `vrgatherei16_vv`,
    `vrsub_vi`,
    `vrsub_vx`,
    `vs1r_v`,
    `vs2r_v`,
    `vs4r_v`,
    `vs8r_v`,
    `vsadd_vi`,
    `vsadd_vv`,
    `vsadd_vx`,
    `vsaddu_vi`,
    `vsaddu_vv`,
    `vsaddu_vx`,
    `vsbc_vvm`,
    `vsbc_vxm`,
    `vse16_v`,
    `vse32_v`,
    `vse64_v`,
    `vse8_v`,
    `vsetivli`,
    `vsetvl`,
    `vsetvli`,
    `vsext_vf2`,
    `vsext_vf4`,
    `vsext_vf8`,
    `vslide1down_vx`,
    `vslide1up_vx`,
    `vslidedown_vi`,
    `vslidedown_vx`,
    `vslideup_vi`,
    `vslideup_vx`,
    `vsll_vi`,
    `vsll_vv`,
    `vsll_vx`,
    `vsm_v`,
    `vsmul_vv`,
    `vsmul_vx`,
    `vsoxei16_v`,
    `vsoxei32_v`,
    `vsoxei64_v`,
    `vsoxei8_v`,
    `vsoxseg2ei16_v`,
    `vsoxseg2ei32_v`,
    `vsoxseg2ei64_v`,
    `vsoxseg2ei8_v`,
    `vsoxseg3ei16_v`,
    `vsoxseg3ei32_v`,
    `vsoxseg3ei64_v`,
    `vsoxseg3ei8_v`,
    `vsoxseg4ei16_v`,
    `vsoxseg4ei32_v`,
    `vsoxseg4ei64_v`,
    `vsoxseg4ei8_v`,
    `vsoxseg5ei16_v`,
    `vsoxseg5ei32_v`,
    `vsoxseg5ei64_v`,
    `vsoxseg5ei8_v`,
    `vsoxseg6ei16_v`,
    `vsoxseg6ei32_v`,
    `vsoxseg6ei64_v`,
    `vsoxseg6ei8_v`,
    `vsoxseg7ei16_v`,
    `vsoxseg7ei32_v`,
    `vsoxseg7ei64_v`,
    `vsoxseg7ei8_v`,
    `vsoxseg8ei16_v`,
    `vsoxseg8ei32_v`,
    `vsoxseg8ei64_v`,
    `vsoxseg8ei8_v`,
    `vsra_vi`,
    `vsra_vv`,
    `vsra_vx`,
    `vsrl_vi`,
    `vsrl_vv`,
    `vsrl_vx`,
    `vsse16_v`,
    `vsse32_v`,
    `vsse64_v`,
    `vsse8_v`,
    `vsseg2e16_v`,
    `vsseg2e32_v`,
    `vsseg2e64_v`,
    `vsseg2e8_v`,
    `vsseg3e16_v`,
    `vsseg3e32_v`,
    `vsseg3e64_v`,
    `vsseg3e8_v`
  )
