// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/v/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.eew.OperandWidthProfile
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 100 RvvInsn declarations for `v` (chunk 5). */
object V5:
  // vsseg4e16.v  (format: vs3,(rs1),vm)
  val `vsseg4e16_v`: RvvInsn = RvvInsn(
    name       = "vsseg4e16.v",
    extension  = "v",
    sourceToml = "v/vsseg4e16.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 4)

  // vsseg4e32.v  (format: vs3,(rs1),vm)
  val `vsseg4e32_v`: RvvInsn = RvvInsn(
    name       = "vsseg4e32.v",
    extension  = "v",
    sourceToml = "v/vsseg4e32.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 4)

  // vsseg4e64.v  (format: vs3,(rs1),vm)
  val `vsseg4e64_v`: RvvInsn = RvvInsn(
    name       = "vsseg4e64.v",
    extension  = "v",
    sourceToml = "v/vsseg4e64.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 4)

  // vsseg4e8.v  (format: vs3,(rs1),vm)
  val `vsseg4e8_v`: RvvInsn = RvvInsn(
    name       = "vsseg4e8.v",
    extension  = "v",
    sourceToml = "v/vsseg4e8.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 4)

  // vsseg5e16.v  (format: vs3,(rs1),vm)
  val `vsseg5e16_v`: RvvInsn = RvvInsn(
    name       = "vsseg5e16.v",
    extension  = "v",
    sourceToml = "v/vsseg5e16.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 5)

  // vsseg5e32.v  (format: vs3,(rs1),vm)
  val `vsseg5e32_v`: RvvInsn = RvvInsn(
    name       = "vsseg5e32.v",
    extension  = "v",
    sourceToml = "v/vsseg5e32.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 5)

  // vsseg5e64.v  (format: vs3,(rs1),vm)
  val `vsseg5e64_v`: RvvInsn = RvvInsn(
    name       = "vsseg5e64.v",
    extension  = "v",
    sourceToml = "v/vsseg5e64.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 5)

  // vsseg5e8.v  (format: vs3,(rs1),vm)
  val `vsseg5e8_v`: RvvInsn = RvvInsn(
    name       = "vsseg5e8.v",
    extension  = "v",
    sourceToml = "v/vsseg5e8.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 5)

  // vsseg6e16.v  (format: vs3,(rs1),vm)
  val `vsseg6e16_v`: RvvInsn = RvvInsn(
    name       = "vsseg6e16.v",
    extension  = "v",
    sourceToml = "v/vsseg6e16.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 6)

  // vsseg6e32.v  (format: vs3,(rs1),vm)
  val `vsseg6e32_v`: RvvInsn = RvvInsn(
    name       = "vsseg6e32.v",
    extension  = "v",
    sourceToml = "v/vsseg6e32.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 6)

  // vsseg6e64.v  (format: vs3,(rs1),vm)
  val `vsseg6e64_v`: RvvInsn = RvvInsn(
    name       = "vsseg6e64.v",
    extension  = "v",
    sourceToml = "v/vsseg6e64.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 6)

  // vsseg6e8.v  (format: vs3,(rs1),vm)
  val `vsseg6e8_v`: RvvInsn = RvvInsn(
    name       = "vsseg6e8.v",
    extension  = "v",
    sourceToml = "v/vsseg6e8.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 6)

  // vsseg7e16.v  (format: vs3,(rs1),vm)
  val `vsseg7e16_v`: RvvInsn = RvvInsn(
    name       = "vsseg7e16.v",
    extension  = "v",
    sourceToml = "v/vsseg7e16.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 7)

  // vsseg7e32.v  (format: vs3,(rs1),vm)
  val `vsseg7e32_v`: RvvInsn = RvvInsn(
    name       = "vsseg7e32.v",
    extension  = "v",
    sourceToml = "v/vsseg7e32.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 7)

  // vsseg7e64.v  (format: vs3,(rs1),vm)
  val `vsseg7e64_v`: RvvInsn = RvvInsn(
    name       = "vsseg7e64.v",
    extension  = "v",
    sourceToml = "v/vsseg7e64.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 7)

  // vsseg7e8.v  (format: vs3,(rs1),vm)
  val `vsseg7e8_v`: RvvInsn = RvvInsn(
    name       = "vsseg7e8.v",
    extension  = "v",
    sourceToml = "v/vsseg7e8.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 7)

  // vsseg8e16.v  (format: vs3,(rs1),vm)
  val `vsseg8e16_v`: RvvInsn = RvvInsn(
    name       = "vsseg8e16.v",
    extension  = "v",
    sourceToml = "v/vsseg8e16.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 8)

  // vsseg8e32.v  (format: vs3,(rs1),vm)
  val `vsseg8e32_v`: RvvInsn = RvvInsn(
    name       = "vsseg8e32.v",
    extension  = "v",
    sourceToml = "v/vsseg8e32.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 8)

  // vsseg8e64.v  (format: vs3,(rs1),vm)
  val `vsseg8e64_v`: RvvInsn = RvvInsn(
    name       = "vsseg8e64.v",
    extension  = "v",
    sourceToml = "v/vsseg8e64.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 8)

  // vsseg8e8.v  (format: vs3,(rs1),vm)
  val `vsseg8e8_v`: RvvInsn = RvvInsn(
    name       = "vsseg8e8.v",
    extension  = "v",
    sourceToml = "v/vsseg8e8.v.toml",
    schema     = Schema.Vs3Rs1mVm,
    nfields = 8)

  // vssra.vi  (format: vd,vs2,uimm,vm)
  val `vssra_vi`: RvvInsn = RvvInsn(
    name       = "vssra.vi",
    extension  = "v",
    sourceToml = "v/vssra.vi.toml",
    schema     = Schema.VdVs2UimmVm,
    vxrm = true)

  // vssra.vv  (format: vd,vs2,vs1,vm)
  val `vssra_vv`: RvvInsn = RvvInsn(
    name       = "vssra.vv",
    extension  = "v",
    sourceToml = "v/vssra.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true)

  // vssra.vx  (format: vd,vs2,rs1,vm)
  val `vssra_vx`: RvvInsn = RvvInsn(
    name       = "vssra.vx",
    extension  = "v",
    sourceToml = "v/vssra.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true)

  // vssrl.vi  (format: vd,vs2,uimm,vm)
  val `vssrl_vi`: RvvInsn = RvvInsn(
    name       = "vssrl.vi",
    extension  = "v",
    sourceToml = "v/vssrl.vi.toml",
    schema     = Schema.VdVs2UimmVm,
    vxrm = true)

  // vssrl.vv  (format: vd,vs2,vs1,vm)
  val `vssrl_vv`: RvvInsn = RvvInsn(
    name       = "vssrl.vv",
    extension  = "v",
    sourceToml = "v/vssrl.vv.toml",
    schema     = Schema.VdVs2Vs1Vm,
    vxrm = true)

  // vssrl.vx  (format: vd,vs2,rs1,vm)
  val `vssrl_vx`: RvvInsn = RvvInsn(
    name       = "vssrl.vx",
    extension  = "v",
    sourceToml = "v/vssrl.vx.toml",
    schema     = Schema.VdVs2Rs1Vm,
    vxrm = true)

  // vssseg2e16.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg2e16_v`: RvvInsn = RvvInsn(
    name       = "vssseg2e16.v",
    extension  = "v",
    sourceToml = "v/vssseg2e16.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 2)

  // vssseg2e32.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg2e32_v`: RvvInsn = RvvInsn(
    name       = "vssseg2e32.v",
    extension  = "v",
    sourceToml = "v/vssseg2e32.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 2)

  // vssseg2e64.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg2e64_v`: RvvInsn = RvvInsn(
    name       = "vssseg2e64.v",
    extension  = "v",
    sourceToml = "v/vssseg2e64.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 2)

  // vssseg2e8.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg2e8_v`: RvvInsn = RvvInsn(
    name       = "vssseg2e8.v",
    extension  = "v",
    sourceToml = "v/vssseg2e8.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 2)

  // vssseg3e16.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg3e16_v`: RvvInsn = RvvInsn(
    name       = "vssseg3e16.v",
    extension  = "v",
    sourceToml = "v/vssseg3e16.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 3)

  // vssseg3e32.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg3e32_v`: RvvInsn = RvvInsn(
    name       = "vssseg3e32.v",
    extension  = "v",
    sourceToml = "v/vssseg3e32.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 3)

  // vssseg3e64.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg3e64_v`: RvvInsn = RvvInsn(
    name       = "vssseg3e64.v",
    extension  = "v",
    sourceToml = "v/vssseg3e64.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 3)

  // vssseg3e8.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg3e8_v`: RvvInsn = RvvInsn(
    name       = "vssseg3e8.v",
    extension  = "v",
    sourceToml = "v/vssseg3e8.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 3)

  // vssseg4e16.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg4e16_v`: RvvInsn = RvvInsn(
    name       = "vssseg4e16.v",
    extension  = "v",
    sourceToml = "v/vssseg4e16.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 4)

  // vssseg4e32.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg4e32_v`: RvvInsn = RvvInsn(
    name       = "vssseg4e32.v",
    extension  = "v",
    sourceToml = "v/vssseg4e32.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 4)

  // vssseg4e64.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg4e64_v`: RvvInsn = RvvInsn(
    name       = "vssseg4e64.v",
    extension  = "v",
    sourceToml = "v/vssseg4e64.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 4)

  // vssseg4e8.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg4e8_v`: RvvInsn = RvvInsn(
    name       = "vssseg4e8.v",
    extension  = "v",
    sourceToml = "v/vssseg4e8.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 4)

  // vssseg5e16.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg5e16_v`: RvvInsn = RvvInsn(
    name       = "vssseg5e16.v",
    extension  = "v",
    sourceToml = "v/vssseg5e16.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 5)

  // vssseg5e32.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg5e32_v`: RvvInsn = RvvInsn(
    name       = "vssseg5e32.v",
    extension  = "v",
    sourceToml = "v/vssseg5e32.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 5)

  // vssseg5e64.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg5e64_v`: RvvInsn = RvvInsn(
    name       = "vssseg5e64.v",
    extension  = "v",
    sourceToml = "v/vssseg5e64.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 5)

  // vssseg5e8.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg5e8_v`: RvvInsn = RvvInsn(
    name       = "vssseg5e8.v",
    extension  = "v",
    sourceToml = "v/vssseg5e8.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 5)

  // vssseg6e16.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg6e16_v`: RvvInsn = RvvInsn(
    name       = "vssseg6e16.v",
    extension  = "v",
    sourceToml = "v/vssseg6e16.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 6)

  // vssseg6e32.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg6e32_v`: RvvInsn = RvvInsn(
    name       = "vssseg6e32.v",
    extension  = "v",
    sourceToml = "v/vssseg6e32.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 6)

  // vssseg6e64.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg6e64_v`: RvvInsn = RvvInsn(
    name       = "vssseg6e64.v",
    extension  = "v",
    sourceToml = "v/vssseg6e64.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 6)

  // vssseg6e8.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg6e8_v`: RvvInsn = RvvInsn(
    name       = "vssseg6e8.v",
    extension  = "v",
    sourceToml = "v/vssseg6e8.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 6)

  // vssseg7e16.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg7e16_v`: RvvInsn = RvvInsn(
    name       = "vssseg7e16.v",
    extension  = "v",
    sourceToml = "v/vssseg7e16.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 7)

  // vssseg7e32.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg7e32_v`: RvvInsn = RvvInsn(
    name       = "vssseg7e32.v",
    extension  = "v",
    sourceToml = "v/vssseg7e32.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 7)

  // vssseg7e64.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg7e64_v`: RvvInsn = RvvInsn(
    name       = "vssseg7e64.v",
    extension  = "v",
    sourceToml = "v/vssseg7e64.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 7)

  // vssseg7e8.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg7e8_v`: RvvInsn = RvvInsn(
    name       = "vssseg7e8.v",
    extension  = "v",
    sourceToml = "v/vssseg7e8.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 7)

  // vssseg8e16.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg8e16_v`: RvvInsn = RvvInsn(
    name       = "vssseg8e16.v",
    extension  = "v",
    sourceToml = "v/vssseg8e16.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 8)

  // vssseg8e32.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg8e32_v`: RvvInsn = RvvInsn(
    name       = "vssseg8e32.v",
    extension  = "v",
    sourceToml = "v/vssseg8e32.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 8)

  // vssseg8e64.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg8e64_v`: RvvInsn = RvvInsn(
    name       = "vssseg8e64.v",
    extension  = "v",
    sourceToml = "v/vssseg8e64.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 8)

  // vssseg8e8.v  (format: vs3,(rs1),rs2,vm)
  val `vssseg8e8_v`: RvvInsn = RvvInsn(
    name       = "vssseg8e8.v",
    extension  = "v",
    sourceToml = "v/vssseg8e8.v.toml",
    schema     = Schema.Vs3Rs1mRs2Vm,
    nfields = 8)

  // vssub.vv  (format: vd,vs2,vs1,vm)
  val `vssub_vv`: RvvInsn = RvvInsn(
    name       = "vssub.vv",
    extension  = "v",
    sourceToml = "v/vssub.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vssub.vx  (format: vd,vs2,rs1,vm)
  val `vssub_vx`: RvvInsn = RvvInsn(
    name       = "vssub.vx",
    extension  = "v",
    sourceToml = "v/vssub.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vssubu.vv  (format: vd,vs2,vs1,vm)
  val `vssubu_vv`: RvvInsn = RvvInsn(
    name       = "vssubu.vv",
    extension  = "v",
    sourceToml = "v/vssubu.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vssubu.vx  (format: vd,vs2,rs1,vm)
  val `vssubu_vx`: RvvInsn = RvvInsn(
    name       = "vssubu.vx",
    extension  = "v",
    sourceToml = "v/vssubu.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vsub.vv  (format: vd,vs2,vs1,vm)
  val `vsub_vv`: RvvInsn = RvvInsn(
    name       = "vsub.vv",
    extension  = "v",
    sourceToml = "v/vsub.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vsub.vx  (format: vd,vs2,rs1,vm)
  val `vsub_vx`: RvvInsn = RvvInsn(
    name       = "vsub.vx",
    extension  = "v",
    sourceToml = "v/vsub.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vsuxei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxei16_v`: RvvInsn = RvvInsn(
    name       = "vsuxei16.v",
    extension  = "v",
    sourceToml = "v/vsuxei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16))

  // vsuxei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxei32_v`: RvvInsn = RvvInsn(
    name       = "vsuxei32.v",
    extension  = "v",
    sourceToml = "v/vsuxei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32))

  // vsuxei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxei64_v`: RvvInsn = RvvInsn(
    name       = "vsuxei64.v",
    extension  = "v",
    sourceToml = "v/vsuxei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64))

  // vsuxei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxei8_v`: RvvInsn = RvvInsn(
    name       = "vsuxei8.v",
    extension  = "v",
    sourceToml = "v/vsuxei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8))

  // vsuxseg2ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg2ei16_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg2ei16.v",
    extension  = "v",
    sourceToml = "v/vsuxseg2ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16),
    nfields = 2)

  // vsuxseg2ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg2ei32_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg2ei32.v",
    extension  = "v",
    sourceToml = "v/vsuxseg2ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32),
    nfields = 2)

  // vsuxseg2ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg2ei64_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg2ei64.v",
    extension  = "v",
    sourceToml = "v/vsuxseg2ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64),
    nfields = 2)

  // vsuxseg2ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg2ei8_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg2ei8.v",
    extension  = "v",
    sourceToml = "v/vsuxseg2ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8),
    nfields = 2)

  // vsuxseg3ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg3ei16_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg3ei16.v",
    extension  = "v",
    sourceToml = "v/vsuxseg3ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16),
    nfields = 3)

  // vsuxseg3ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg3ei32_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg3ei32.v",
    extension  = "v",
    sourceToml = "v/vsuxseg3ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32),
    nfields = 3)

  // vsuxseg3ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg3ei64_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg3ei64.v",
    extension  = "v",
    sourceToml = "v/vsuxseg3ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64),
    nfields = 3)

  // vsuxseg3ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg3ei8_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg3ei8.v",
    extension  = "v",
    sourceToml = "v/vsuxseg3ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8),
    nfields = 3)

  // vsuxseg4ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg4ei16_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg4ei16.v",
    extension  = "v",
    sourceToml = "v/vsuxseg4ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16),
    nfields = 4)

  // vsuxseg4ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg4ei32_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg4ei32.v",
    extension  = "v",
    sourceToml = "v/vsuxseg4ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32),
    nfields = 4)

  // vsuxseg4ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg4ei64_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg4ei64.v",
    extension  = "v",
    sourceToml = "v/vsuxseg4ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64),
    nfields = 4)

  // vsuxseg4ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg4ei8_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg4ei8.v",
    extension  = "v",
    sourceToml = "v/vsuxseg4ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8),
    nfields = 4)

  // vsuxseg5ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg5ei16_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg5ei16.v",
    extension  = "v",
    sourceToml = "v/vsuxseg5ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16),
    nfields = 5)

  // vsuxseg5ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg5ei32_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg5ei32.v",
    extension  = "v",
    sourceToml = "v/vsuxseg5ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32),
    nfields = 5)

  // vsuxseg5ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg5ei64_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg5ei64.v",
    extension  = "v",
    sourceToml = "v/vsuxseg5ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64),
    nfields = 5)

  // vsuxseg5ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg5ei8_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg5ei8.v",
    extension  = "v",
    sourceToml = "v/vsuxseg5ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8),
    nfields = 5)

  // vsuxseg6ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg6ei16_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg6ei16.v",
    extension  = "v",
    sourceToml = "v/vsuxseg6ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16),
    nfields = 6)

  // vsuxseg6ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg6ei32_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg6ei32.v",
    extension  = "v",
    sourceToml = "v/vsuxseg6ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32),
    nfields = 6)

  // vsuxseg6ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg6ei64_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg6ei64.v",
    extension  = "v",
    sourceToml = "v/vsuxseg6ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64),
    nfields = 6)

  // vsuxseg6ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg6ei8_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg6ei8.v",
    extension  = "v",
    sourceToml = "v/vsuxseg6ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8),
    nfields = 6)

  // vsuxseg7ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg7ei16_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg7ei16.v",
    extension  = "v",
    sourceToml = "v/vsuxseg7ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16),
    nfields = 7)

  // vsuxseg7ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg7ei32_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg7ei32.v",
    extension  = "v",
    sourceToml = "v/vsuxseg7ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32),
    nfields = 7)

  // vsuxseg7ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg7ei64_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg7ei64.v",
    extension  = "v",
    sourceToml = "v/vsuxseg7ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64),
    nfields = 7)

  // vsuxseg7ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg7ei8_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg7ei8.v",
    extension  = "v",
    sourceToml = "v/vsuxseg7ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8),
    nfields = 7)

  // vsuxseg8ei16.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg8ei16_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg8ei16.v",
    extension  = "v",
    sourceToml = "v/vsuxseg8ei16.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(16),
    nfields = 8)

  // vsuxseg8ei32.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg8ei32_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg8ei32.v",
    extension  = "v",
    sourceToml = "v/vsuxseg8ei32.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(32),
    nfields = 8)

  // vsuxseg8ei64.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg8ei64_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg8ei64.v",
    extension  = "v",
    sourceToml = "v/vsuxseg8ei64.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(64),
    nfields = 8)

  // vsuxseg8ei8.v  (format: vs3,(rs1),vs2,vm)
  val `vsuxseg8ei8_v`: RvvInsn = RvvInsn(
    name       = "vsuxseg8ei8.v",
    extension  = "v",
    sourceToml = "v/vsuxseg8ei8.v.toml",
    schema     = Schema.Vs3Rs1mVs2Vm,
    indexedEew = Some(8),
    nfields = 8)

  // vwadd.vv  (format: vd,vs2,vs1,vm)
  val `vwadd_vv`: RvvInsn = RvvInsn(
    name       = "vwadd.vv",
    extension  = "v",
    sourceToml = "v/vwadd.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwadd.vx  (format: vd,vs2,rs1,vm)
  val `vwadd_vx`: RvvInsn = RvvInsn(
    name       = "vwadd.vx",
    extension  = "v",
    sourceToml = "v/vwadd.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwadd.wv  (format: vd,vs2,vs1,vm)
  val `vwadd_wv`: RvvInsn = RvvInsn(
    name       = "vwadd.wv",
    extension  = "v",
    sourceToml = "v/vwadd.wv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwadd.wx  (format: vd,vs2,rs1,vm)
  val `vwadd_wx`: RvvInsn = RvvInsn(
    name       = "vwadd.wx",
    extension  = "v",
    sourceToml = "v/vwadd.wx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwaddu.vv  (format: vd,vs2,vs1,vm)
  val `vwaddu_vv`: RvvInsn = RvvInsn(
    name       = "vwaddu.vv",
    extension  = "v",
    sourceToml = "v/vwaddu.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwaddu.vx  (format: vd,vs2,rs1,vm)
  val `vwaddu_vx`: RvvInsn = RvvInsn(
    name       = "vwaddu.vx",
    extension  = "v",
    sourceToml = "v/vwaddu.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwaddu.wv  (format: vd,vs2,vs1,vm)
  val `vwaddu_wv`: RvvInsn = RvvInsn(
    name       = "vwaddu.wv",
    extension  = "v",
    sourceToml = "v/vwaddu.wv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwaddu.wx  (format: vd,vs2,rs1,vm)
  val `vwaddu_wx`: RvvInsn = RvvInsn(
    name       = "vwaddu.wx",
    extension  = "v",
    sourceToml = "v/vwaddu.wx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  val chunkAll: List[RvvInsn] = List(
    `vsseg4e16_v`,
    `vsseg4e32_v`,
    `vsseg4e64_v`,
    `vsseg4e8_v`,
    `vsseg5e16_v`,
    `vsseg5e32_v`,
    `vsseg5e64_v`,
    `vsseg5e8_v`,
    `vsseg6e16_v`,
    `vsseg6e32_v`,
    `vsseg6e64_v`,
    `vsseg6e8_v`,
    `vsseg7e16_v`,
    `vsseg7e32_v`,
    `vsseg7e64_v`,
    `vsseg7e8_v`,
    `vsseg8e16_v`,
    `vsseg8e32_v`,
    `vsseg8e64_v`,
    `vsseg8e8_v`,
    `vssra_vi`,
    `vssra_vv`,
    `vssra_vx`,
    `vssrl_vi`,
    `vssrl_vv`,
    `vssrl_vx`,
    `vssseg2e16_v`,
    `vssseg2e32_v`,
    `vssseg2e64_v`,
    `vssseg2e8_v`,
    `vssseg3e16_v`,
    `vssseg3e32_v`,
    `vssseg3e64_v`,
    `vssseg3e8_v`,
    `vssseg4e16_v`,
    `vssseg4e32_v`,
    `vssseg4e64_v`,
    `vssseg4e8_v`,
    `vssseg5e16_v`,
    `vssseg5e32_v`,
    `vssseg5e64_v`,
    `vssseg5e8_v`,
    `vssseg6e16_v`,
    `vssseg6e32_v`,
    `vssseg6e64_v`,
    `vssseg6e8_v`,
    `vssseg7e16_v`,
    `vssseg7e32_v`,
    `vssseg7e64_v`,
    `vssseg7e8_v`,
    `vssseg8e16_v`,
    `vssseg8e32_v`,
    `vssseg8e64_v`,
    `vssseg8e8_v`,
    `vssub_vv`,
    `vssub_vx`,
    `vssubu_vv`,
    `vssubu_vx`,
    `vsub_vv`,
    `vsub_vx`,
    `vsuxei16_v`,
    `vsuxei32_v`,
    `vsuxei64_v`,
    `vsuxei8_v`,
    `vsuxseg2ei16_v`,
    `vsuxseg2ei32_v`,
    `vsuxseg2ei64_v`,
    `vsuxseg2ei8_v`,
    `vsuxseg3ei16_v`,
    `vsuxseg3ei32_v`,
    `vsuxseg3ei64_v`,
    `vsuxseg3ei8_v`,
    `vsuxseg4ei16_v`,
    `vsuxseg4ei32_v`,
    `vsuxseg4ei64_v`,
    `vsuxseg4ei8_v`,
    `vsuxseg5ei16_v`,
    `vsuxseg5ei32_v`,
    `vsuxseg5ei64_v`,
    `vsuxseg5ei8_v`,
    `vsuxseg6ei16_v`,
    `vsuxseg6ei32_v`,
    `vsuxseg6ei64_v`,
    `vsuxseg6ei8_v`,
    `vsuxseg7ei16_v`,
    `vsuxseg7ei32_v`,
    `vsuxseg7ei64_v`,
    `vsuxseg7ei8_v`,
    `vsuxseg8ei16_v`,
    `vsuxseg8ei32_v`,
    `vsuxseg8ei64_v`,
    `vsuxseg8ei8_v`,
    `vwadd_vv`,
    `vwadd_vx`,
    `vwadd_wv`,
    `vwadd_wx`,
    `vwaddu_vv`,
    `vwaddu_vx`,
    `vwaddu_wv`,
    `vwaddu_wx`
  )
