// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/v/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.eew.OperandWidthProfile
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 29 RvvInsn declarations for `v` (chunk 6). */
object V6:
  // vwmacc.vv  (format: vd,vs1,vs2,vm)
  val `vwmacc_vv`: RvvInsn = RvvInsn(
    name       = "vwmacc.vv",
    extension  = "v",
    sourceToml = "v/vwmacc.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs1Vs2Vm)

  // vwmacc.vx  (format: vd,rs1,vs2,vm)
  val `vwmacc_vx`: RvvInsn = RvvInsn(
    name       = "vwmacc.vx",
    extension  = "v",
    sourceToml = "v/vwmacc.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdRs1Vs2Vm)

  // vwmaccsu.vv  (format: vd,vs1,vs2,vm)
  val `vwmaccsu_vv`: RvvInsn = RvvInsn(
    name       = "vwmaccsu.vv",
    extension  = "v",
    sourceToml = "v/vwmaccsu.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs1Vs2Vm)

  // vwmaccsu.vx  (format: vd,rs1,vs2,vm)
  val `vwmaccsu_vx`: RvvInsn = RvvInsn(
    name       = "vwmaccsu.vx",
    extension  = "v",
    sourceToml = "v/vwmaccsu.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdRs1Vs2Vm)

  // vwmaccu.vv  (format: vd,vs1,vs2,vm)
  val `vwmaccu_vv`: RvvInsn = RvvInsn(
    name       = "vwmaccu.vv",
    extension  = "v",
    sourceToml = "v/vwmaccu.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs1Vs2Vm)

  // vwmaccu.vx  (format: vd,rs1,vs2,vm)
  val `vwmaccu_vx`: RvvInsn = RvvInsn(
    name       = "vwmaccu.vx",
    extension  = "v",
    sourceToml = "v/vwmaccu.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdRs1Vs2Vm)

  // vwmaccus.vx  (format: vd,rs1,vs2,vm)
  val `vwmaccus_vx`: RvvInsn = RvvInsn(
    name       = "vwmaccus.vx",
    extension  = "v",
    sourceToml = "v/vwmaccus.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdRs1Vs2Vm)

  // vwmul.vv  (format: vd,vs2,vs1,vm)
  val `vwmul_vv`: RvvInsn = RvvInsn(
    name       = "vwmul.vv",
    extension  = "v",
    sourceToml = "v/vwmul.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwmul.vx  (format: vd,vs2,rs1,vm)
  val `vwmul_vx`: RvvInsn = RvvInsn(
    name       = "vwmul.vx",
    extension  = "v",
    sourceToml = "v/vwmul.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwmulsu.vv  (format: vd,vs2,vs1,vm)
  val `vwmulsu_vv`: RvvInsn = RvvInsn(
    name       = "vwmulsu.vv",
    extension  = "v",
    sourceToml = "v/vwmulsu.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwmulsu.vx  (format: vd,vs2,rs1,vm)
  val `vwmulsu_vx`: RvvInsn = RvvInsn(
    name       = "vwmulsu.vx",
    extension  = "v",
    sourceToml = "v/vwmulsu.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwmulu.vv  (format: vd,vs2,vs1,vm)
  val `vwmulu_vv`: RvvInsn = RvvInsn(
    name       = "vwmulu.vv",
    extension  = "v",
    sourceToml = "v/vwmulu.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwmulu.vx  (format: vd,vs2,rs1,vm)
  val `vwmulu_vx`: RvvInsn = RvvInsn(
    name       = "vwmulu.vx",
    extension  = "v",
    sourceToml = "v/vwmulu.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwredsum.vs  (format: vd,vs2,vs1,vm)
  val `vwredsum_vs`: RvvInsn = RvvInsn(
    name       = "vwredsum.vs",
    extension  = "v",
    sourceToml = "v/vwredsum.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vwredsumu.vs  (format: vd,vs2,vs1,vm)
  val `vwredsumu_vs`: RvvInsn = RvvInsn(
    name       = "vwredsumu.vs",
    extension  = "v",
    sourceToml = "v/vwredsumu.vs.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vwsub.vv  (format: vd,vs2,vs1,vm)
  val `vwsub_vv`: RvvInsn = RvvInsn(
    name       = "vwsub.vv",
    extension  = "v",
    sourceToml = "v/vwsub.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwsub.vx  (format: vd,vs2,rs1,vm)
  val `vwsub_vx`: RvvInsn = RvvInsn(
    name       = "vwsub.vx",
    extension  = "v",
    sourceToml = "v/vwsub.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwsub.wv  (format: vd,vs2,vs1,vm)
  val `vwsub_wv`: RvvInsn = RvvInsn(
    name       = "vwsub.wv",
    extension  = "v",
    sourceToml = "v/vwsub.wv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwsub.wx  (format: vd,vs2,rs1,vm)
  val `vwsub_wx`: RvvInsn = RvvInsn(
    name       = "vwsub.wx",
    extension  = "v",
    sourceToml = "v/vwsub.wx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwsubu.vv  (format: vd,vs2,vs1,vm)
  val `vwsubu_vv`: RvvInsn = RvvInsn(
    name       = "vwsubu.vv",
    extension  = "v",
    sourceToml = "v/vwsubu.vv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwsubu.vx  (format: vd,vs2,rs1,vm)
  val `vwsubu_vx`: RvvInsn = RvvInsn(
    name       = "vwsubu.vx",
    extension  = "v",
    sourceToml = "v/vwsubu.vx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vwsubu.wv  (format: vd,vs2,vs1,vm)
  val `vwsubu_wv`: RvvInsn = RvvInsn(
    name       = "vwsubu.wv",
    extension  = "v",
    sourceToml = "v/vwsubu.wv.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Vs1Vm)

  // vwsubu.wx  (format: vd,vs2,rs1,vm)
  val `vwsubu_wx`: RvvInsn = RvvInsn(
    name       = "vwsubu.wx",
    extension  = "v",
    sourceToml = "v/vwsubu.wx.toml",
    widthProfile = OperandWidthProfile(Map(me.jiuyang.rvprobe.rvv.OperandRole.Vd -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2, me.jiuyang.rvprobe.rvv.OperandRole.Vs2 -> me.jiuyang.rvprobe.rvv.eew.WidthScale.By2)),
    schema     = Schema.VdVs2Rs1Vm)

  // vxor.vi  (format: vd,vs2,imm,vm)
  val `vxor_vi`: RvvInsn = RvvInsn(
    name       = "vxor.vi",
    extension  = "v",
    sourceToml = "v/vxor.vi.toml",
    schema     = Schema.VdVs2ImmVm)

  // vxor.vv  (format: vd,vs2,vs1,vm)
  val `vxor_vv`: RvvInsn = RvvInsn(
    name       = "vxor.vv",
    extension  = "v",
    sourceToml = "v/vxor.vv.toml",
    schema     = Schema.VdVs2Vs1Vm)

  // vxor.vx  (format: vd,vs2,rs1,vm)
  val `vxor_vx`: RvvInsn = RvvInsn(
    name       = "vxor.vx",
    extension  = "v",
    sourceToml = "v/vxor.vx.toml",
    schema     = Schema.VdVs2Rs1Vm)

  // vzext.vf2  (format: vd,vs2,vm/3)
  val `vzext_vf2`: RvvInsn = RvvInsn(
    name       = "vzext.vf2",
    extension  = "v",
    sourceToml = "v/vzext.vf2.toml",
    schema     = Schema.VdVs2VmP3)

  // vzext.vf4  (format: vd,vs2,vm/3)
  val `vzext_vf4`: RvvInsn = RvvInsn(
    name       = "vzext.vf4",
    extension  = "v",
    sourceToml = "v/vzext.vf4.toml",
    schema     = Schema.VdVs2VmP3)

  // vzext.vf8  (format: vd,vs2,vm/3)
  val `vzext_vf8`: RvvInsn = RvvInsn(
    name       = "vzext.vf8",
    extension  = "v",
    sourceToml = "v/vzext.vf8.toml",
    schema     = Schema.VdVs2VmP3)

  val chunkAll: List[RvvInsn] = List(
    `vwmacc_vv`,
    `vwmacc_vx`,
    `vwmaccsu_vv`,
    `vwmaccsu_vx`,
    `vwmaccu_vv`,
    `vwmaccu_vx`,
    `vwmaccus_vx`,
    `vwmul_vv`,
    `vwmul_vx`,
    `vwmulsu_vv`,
    `vwmulsu_vx`,
    `vwmulu_vv`,
    `vwmulu_vx`,
    `vwredsum_vs`,
    `vwredsumu_vs`,
    `vwsub_vv`,
    `vwsub_vx`,
    `vwsub_wv`,
    `vwsub_wx`,
    `vwsubu_vv`,
    `vwsubu_vx`,
    `vwsubu_wv`,
    `vwsubu_wx`,
    `vxor_vi`,
    `vxor_vv`,
    `vxor_vx`,
    `vzext_vf2`,
    `vzext_vf4`,
    `vzext_vf8`
  )
