// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/zvfbfmin/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 2 RvvInsn declarations for upstream extension `zvfbfmin`. */
object Zvfbfmin:
  // vfncvtbf16.f.f.w  (format: vd,vs2,vm)
  val `vfncvtbf16_f_f_w`: RvvInsn = RvvInsn(
    name      = "vfncvtbf16.f.f.w",
    extension = "zvfbfmin",
    schema    = Schema.VdVs2Vm)

  // vfwcvtbf16.f.f.v  (format: vd,vs2,vm)
  val `vfwcvtbf16_f_f_v`: RvvInsn = RvvInsn(
    name      = "vfwcvtbf16.f.f.v",
    extension = "zvfbfmin",
    schema    = Schema.VdVs2Vm)

  val all: List[RvvInsn] = List(
    `vfncvtbf16_f_f_w`,
    `vfwcvtbf16_f_f_v`
  )
