// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/zvfbfwma/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 2 RvvInsn declarations for `zvfbfwma` (chunk). */
object Zvfbfwma:
  // vfwmaccbf16.vf  (format: vd,fs1,vs2,vm)
  val `vfwmaccbf16_vf`: RvvInsn = RvvInsn(
    name       = "vfwmaccbf16.vf",
    extension  = "zvfbfwma",
    sourceToml = "zvfbfwma/vfwmaccbf16.vf.toml",
    schema     = Schema.VdFs1Vs2Vm)

  // vfwmaccbf16.vv  (format: vd,vs1,vs2,vm)
  val `vfwmaccbf16_vv`: RvvInsn = RvvInsn(
    name       = "vfwmaccbf16.vv",
    extension  = "zvfbfwma",
    sourceToml = "zvfbfwma/vfwmaccbf16.vv.toml",
    schema     = Schema.VdVs1Vs2Vm)

  val all: List[RvvInsn] = List(
    `vfwmaccbf16_vf`,
    `vfwmaccbf16_vv`
  )
