// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/zvfhmin/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 2 RvvInsn declarations for upstream extension `zvfhmin`. */
object Zvfhmin:
  // vfncvt.f.f.w  (format: vd,vs2,vm)
  val `vfncvt_f_f_w`: RvvInsn = RvvInsn(
    name      = "vfncvt.f.f.w",
    extension = "zvfhmin",
    schema    = Schema.VdVs2Vm)

  // vfwcvt.f.f.v  (format: vd,vs2,vm)
  val `vfwcvt_f_f_v`: RvvInsn = RvvInsn(
    name      = "vfwcvt.f.f.v",
    extension = "zvfhmin",
    schema    = Schema.VdVs2Vm)

  val all: List[RvvInsn] = List(
    `vfncvt_f_f_w`,
    `vfwcvt_f_f_v`
  )
