// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/zvkg/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 2 RvvInsn declarations for `zvkg` (chunk). */
object Zvkg:
  // vghsh.vv  (format: vd,vs2,vs1)
  val `vghsh_vv`: RvvInsn = RvvInsn(
    name       = "vghsh.vv",
    extension  = "zvkg",
    sourceToml = "zvkg/vghsh.vv.toml",
    schema     = Schema.VdVs2Vs1)

  // vgmul.vv  (format: vd,vs2)
  val `vgmul_vv`: RvvInsn = RvvInsn(
    name       = "vgmul.vv",
    extension  = "zvkg",
    sourceToml = "zvkg/vgmul.vv.toml",
    schema     = Schema.VdVs2)

  val all: List[RvvInsn] = List(
    `vghsh_vv`,
    `vgmul_vv`
  )
