// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/zvknha/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 3 RvvInsn declarations for upstream extension `zvknha`. */
object Zvknha:
  // vsha2ch.vv  (format: vd,vs2,vs1)
  val `vsha2ch_vv`: RvvInsn = RvvInsn(
    name      = "vsha2ch.vv",
    extension = "zvknha",
    schema    = Schema.VdVs2Vs1)

  // vsha2cl.vv  (format: vd,vs2,vs1)
  val `vsha2cl_vv`: RvvInsn = RvvInsn(
    name      = "vsha2cl.vv",
    extension = "zvknha",
    schema    = Schema.VdVs2Vs1)

  // vsha2ms.vv  (format: vd,vs2,vs1)
  val `vsha2ms_vv`: RvvInsn = RvvInsn(
    name      = "vsha2ms.vv",
    extension = "zvknha",
    schema    = Schema.VdVs2Vs1)

  val all: List[RvvInsn] = List(
    `vsha2ch_vv`,
    `vsha2cl_vv`,
    `vsha2ms_vv`
  )
