// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/zvksed/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 3 RvvInsn declarations for `zvksed` (chunk). */
object Zvksed:
  // vsm4k.vi  (format: vd,vs2,uimm)
  val `vsm4k_vi`: RvvInsn = RvvInsn(
    name       = "vsm4k.vi",
    extension  = "zvksed",
    sourceToml = "zvksed/vsm4k.vi.toml",
    schema     = Schema.VdVs2Uimm)

  // vsm4r.vs  (format: vd,vs2)
  val `vsm4r_vs`: RvvInsn = RvvInsn(
    name       = "vsm4r.vs",
    extension  = "zvksed",
    sourceToml = "zvksed/vsm4r.vs.toml",
    schema     = Schema.VdVs2)

  // vsm4r.vv  (format: vd,vs2)
  val `vsm4r_vv`: RvvInsn = RvvInsn(
    name       = "vsm4r.vv",
    extension  = "zvksed",
    sourceToml = "zvksed/vsm4r.vv.toml",
    schema     = Schema.VdVs2)

  val all: List[RvvInsn] = List(
    `vsm4k_vi`,
    `vsm4r_vs`,
    `vsm4r_vv`
  )
