// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
//
// Auto-generated by InsnsGenerator from audit/snapshots/zvksh/.
// Do not edit by hand. Regenerate via:
//   mill rvprobe.runMain me.jiuyang.rvprobe.rvv.audit.regenerateInsns
package me.jiuyang.rvprobe.rvv.insns

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.unittest.RvvInsn

/** 2 RvvInsn declarations for upstream extension `zvksh`. */
object Zvksh:
  // vsm3c.vi  (format: vd,vs2,uimm)
  val `vsm3c_vi`: RvvInsn = RvvInsn(
    name      = "vsm3c.vi",
    extension = "zvksh",
    schema    = Schema.VdVs2Uimm)

  // vsm3me.vv  (format: vd,vs2,vs1)
  val `vsm3me_vv`: RvvInsn = RvvInsn(
    name      = "vsm3me.vv",
    extension = "zvksh",
    schema    = Schema.VdVs2Vs1)

  val all: List[RvvInsn] = List(
    `vsm3c_vi`,
    `vsm3me_vv`
  )
