// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.rvprobe.rvv.notestfloat3

import me.jiuyang.rvprobe.rvv.Schema
import me.jiuyang.rvprobe.rvv.vtype.Sew

/** Scala source-of-truth for `vfredusum.vs`'s test case set. Ported from
 *  `riscv-vector-tests/configs/v/vfredusum.vs.toml` (upstream commit
 *  pinned via `audit/snapshots/v/vfredusum.vs.json`'s contentHash).
 *
 *  The upstream curator marks this instruction `notestfloat3 = true`,
 *  which means the FP operand set is hand-written (not generated by
 *  testfloat3). Per AC-10, we mirror the upstream cases here as Scala
 *  data so the rvprobe driver consumes them without a runtime toml
 *  read (AC-12).
 *
 *  Each case is a 2-tuple `(scalar_init, vector_element)` for the
 *  reduction: vs1 carries the scalar accumulator init, vs2 is the
 *  vector filled with the second token, vd captures the reduced sum.
 *  All 5 FRM modes are exercised at the test-emission layer (task13);
 *  here we just record the input pairs.
 */
object Vfredusum extends NotestFloat3InsnSource:
  val name:   String = "vfredusum.vs"
  val schema: Schema = Schema.VdVs2Vs1Vm

  val cases: List[FpCase] = List(
    // ---- fsew16 ----
    FpCase(Sew.Sew16, List("2.5", "1.0"),                                 "common positive >1 with .5 fraction + unity"),
    FpCase(Sew.Sew16, List("-1235.1", "1.1"),                             "arbitrary negative magnitude + non-terminating-fraction positive"),
    FpCase(Sew.Sew16, List("1.1", "-1235.1"),                             "swap-order of the above"),
    FpCase(Sew.Sew16, List("-1.0", "-2.0"),                               "both negatives"),
    FpCase(Sew.Sew16, List("nan", "-nan"),                                "NaN-pair propagation"),
    FpCase(Sew.Sew16, List("inf", "-inf"),                                "inf-pair (overflow-arithmetic edge)"),
    FpCase(Sew.Sew16, List("quiet_nan", "signaling_nan"),                 "quiet vs signaling NaN coexistence"),
    FpCase(Sew.Sew16, List("smallest_nonzero_float", "largest_subnormal_float"), "subnormal range boundary"),
    FpCase(Sew.Sew16, List("-smallest_nonzero_float", "-largest_subnormal_float"), "negated subnormal range boundary"),
    // ---- fsew32 ----
    FpCase(Sew.Sew32, List("2.5", "1.0"),                                 "common positive >1 with .5 fraction + unity"),
    FpCase(Sew.Sew32, List("-1235.5", "1.5"),                             "arbitrary negative magnitude + .5-fraction positive"),
    FpCase(Sew.Sew32, List("1.5", "-1235.5"),                             "swap-order of the above"),
    FpCase(Sew.Sew32, List("-1.0", "-2.0"),                               "both negatives"),
    FpCase(Sew.Sew32, List("nan", "-nan"),                                "NaN-pair propagation"),
    FpCase(Sew.Sew32, List("inf", "-inf"),                                "inf-pair"),
    FpCase(Sew.Sew32, List("quiet_nan", "signaling_nan"),                 "quiet vs signaling NaN coexistence"),
    FpCase(Sew.Sew32, List("smallest_nonzero_float", "largest_subnormal_float"), "subnormal range boundary"),
    FpCase(Sew.Sew32, List("-smallest_nonzero_float", "-largest_subnormal_float"), "negated subnormal range boundary"),
    // ---- fsew64 ----
    FpCase(Sew.Sew64, List("2.5", "1.0"),                                 "common positive >1 with .5 fraction + unity"),
    FpCase(Sew.Sew64, List("-1235.5", "1.5"),                             "arbitrary negative magnitude + .5-fraction positive"),
    FpCase(Sew.Sew64, List("1.5", "-1235.5"),                             "swap-order of the above"),
    FpCase(Sew.Sew64, List("-1.0", "-2.0"),                               "both negatives"),
    FpCase(Sew.Sew64, List("nan", "-nan"),                                "NaN-pair propagation"),
    FpCase(Sew.Sew64, List("inf", "-inf"),                                "inf-pair"),
    FpCase(Sew.Sew64, List("quiet_nan", "signaling_nan"),                 "quiet vs signaling NaN coexistence"),
    FpCase(Sew.Sew64, List("smallest_nonzero_float", "largest_subnormal_float"), "subnormal range boundary"),
    FpCase(Sew.Sew64, List("-smallest_nonzero_float", "-largest_subnormal_float"), "negated subnormal range boundary"))
