// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.rvprobe.rvv.unittest

import me.jiuyang.rvprobe.rvv.vtype.{Lmul, Sew, VTypeEnvelope}

/** Renders the complete `.S` file for a single per-instruction test.
 *  Matches the upstream macros/general/test_macros.h contract: include
 *  the RVTEST headers, set up vector mode via vsetvli, zero-init the
 *  result register groups (v0/v8/v16/v24), emit one per-iteration block
 *  per (predicate × SEW) cell with a magic word, terminate with
 *  TEST_CASE(2, x0, 0x0) + TEST_PASSFAIL, then RVTEST_DATA section
 *  with `resultdata` (.zero) + `testdata` (input bytes).
 *
 *  The downstream pspike + merger pipeline consumes the magic words to
 *  inject expected `TEST_CASE` rows in stage 2; merger.go interleaves
 *  the patch output. This emitter never invokes spike; it just
 *  produces the input `.S`.
 */
object TestSEmit:

  /** A single (predicate × SEW × LMUL) iteration in the per-instruction
   *  test sequence. Caller computes the operand witness vectors via
   *  ElemValueLowering and passes them here.
   */
  final case class TestBlock(
    envelope:    VTypeEnvelope,
    vectorGroup: Int,
    vxsat:       Boolean,
    insnAsm:     String,                    // e.g., "vadd.vv v8, v16, v24"
    setupAsm:    List[String] = Nil,        // any pre-instruction setup (li, vmv.v.x, etc)
    dataLabel:   Option[String] = None      // memory label for load/store
  )

  /** Render the full `.S` file as a String. `envName` chooses the
   *  RVTEST_*UV* macro (RV64UV / RV32UV / RV64UVX). `testData` is the
   *  byte payload for the input vectors (concatenated little-endian).
   */
  def render(
    name:           String,
    envName:        String,
    blocks:         List[TestBlock],
    testData:       Vector[Byte],
    resultBytes:    Int
  ): String =
    val sb = new StringBuilder

    sb.append("# Auto-generated by rvprobe's TestSEmit. Do not edit by hand.\n")
    sb.append(s"# Instruction: $name\n")
    sb.append("\n")
    sb.append("#include \"riscv_test.h\"\n")
    sb.append("#include \"test_macros.h\"\n")
    sb.append("\n")
    sb.append(s"$envName\n")
    sb.append("\n")
    sb.append("RVTEST_CODE_BEGIN\n")
    sb.append("\n")

    if blocks.nonEmpty then
      val head = blocks.head
      sb.append(s"  ${vsetvliAsm(head.envelope)}\n")
      sb.append("  vmv.v.i v0, 0\n")
      sb.append("  vmv.v.i v8, 0\n")
      sb.append("  vmv.v.i v16, 0\n")
      sb.append("  vmv.v.i v24, 0\n")
      sb.append("\n")

    blocks.zipWithIndex.foreach { case (b, idx) =>
      sb.append(s"  # ---- block $idx (group=${b.vectorGroup}, lmul=${b.envelope.vtype.lmul}, sew=${b.envelope.vtype.sewBits}) ----\n")
      // Setup phase
      b.setupAsm.foreach(line => sb.append(s"  $line\n"))
      b.dataLabel.foreach(label =>
        sb.append(s"  la a1, $label\n"))
      // Re-issue vsetvli for this block's envelope (in case it changed)
      sb.append(s"  ${vsetvliAsm(b.envelope)}\n")
      // The instruction under test
      sb.append(s"  ${b.insnAsm}\n")
      // Magic word — pspike injects expected values after this
      sb.append(s"  ${MagicInstrEmit.emitAsm(b.vectorGroup, b.envelope.vtype.lmul, b.vxsat)}\n")
      sb.append("\n")
    }

    sb.append("  TEST_CASE(2, x0, 0x0)\n")
    sb.append("  TEST_PASSFAIL\n")
    sb.append("\n")
    sb.append("RVTEST_CODE_END\n")
    sb.append("\n")
    sb.append("  .data\n")
    sb.append("RVTEST_DATA_BEGIN\n")
    sb.append("\n")
    sb.append("resultdata:\n")
    sb.append(s"  .zero $resultBytes\n")
    sb.append("testdata:\n")
    emitDataBytes(sb, testData)
    sb.append("\nRVTEST_DATA_END\n")
    sb.toString

  /** Emit a vsetvli that materializes the given envelope. Uses x5 as
   *  rs1 (avl source) and x6 as rd; the test harness zero-initialized
   *  these before this point.
   */
  def vsetvliAsm(env: VTypeEnvelope): String =
    val sew = env.vtype.sewBits match
      case 8  => "e8"
      case 16 => "e16"
      case 32 => "e32"
      case 64 => "e64"
    val lmul = env.vtype.lmul match
      case Lmul.M1  => "m1"
      case Lmul.M2  => "m2"
      case Lmul.M4  => "m4"
      case Lmul.M8  => "m8"
      case Lmul.Mf2 => "mf2"
      case Lmul.Mf4 => "mf4"
      case Lmul.Mf8 => "mf8"
    val vta = "ta"
    val vma = "ma"
    s"vsetvli x5, x0, $sew,$lmul,$vta,$vma"

  /** Choose the RVTEST_*UV* macro for a given (xlen, march-has-v)
   *  combination. Matches upstream Makefile's `EXT_V` branching.
   */
  def envMacro(xlen: Int, hasFullV: Boolean): String =
    (xlen, hasFullV) match
      case (64, true)  => "RVTEST_RV64UV"
      case (32, true)  => "RVTEST_RV32UV"
      case (64, false) => "RVTEST_RV64UVX"
      case (32, false) => "RVTEST_RV32UVX"
      case _           => throw new IllegalArgumentException(s"unsupported xlen=$xlen")

  private def emitDataBytes(sb: StringBuilder, data: Vector[Byte]): Unit =
    if data.isEmpty then sb.append("  .zero 0\n")
    else
      val perLine = 16
      data.grouped(perLine).foreach { chunk =>
        val bytes = chunk.map(b => f"0x${b & 0xff}%02x").mkString(", ")
        sb.append(s"  .byte $bytes\n")
      }
