// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Jianhao Ye <Clo91eaf@qq.com>
package me.jiuyang.rvprobe.rvv.unittest

import me.jiuyang.rvprobe.rvv.vtype.{Lmul, Sew, VTypeEnvelope, Vta, Vma}

/** Renders the complete `.S` file for a single per-instruction test.
 *  Matches the upstream macros/general/test_macros.h contract: include
 *  the RVTEST headers, set up vector mode via vsetvli, zero-init the
 *  result register groups (v0/v8/v16/v24), emit one per-iteration block
 *  per (predicate × SEW) cell with a magic word, terminate with
 *  TEST_CASE(2, x0, 0x0) + TEST_PASSFAIL, then RVTEST_DATA section
 *  with `resultdata` (.zero) + `testdata` (input bytes).
 *
 *  The downstream pspike + merger pipeline consumes the magic words to
 *  inject expected `TEST_CASE` rows in stage 2; merger.go interleaves
 *  the patch output. This emitter never invokes spike; it just
 *  produces the input `.S`.
 */
object TestSEmit:

  /** A single (predicate × SEW × LMUL) iteration in the per-instruction
   *  test sequence. Caller computes the operand witness vectors via
   *  ElemValueLowering and passes them here.
   *
   *  pspike contract (round-9 fix): after `insnAsm` executes, the
   *  emitter MUST store the result register group to `resultdata` and
   *  leave `a0` pointing at `resultdata` BEFORE the magic word.
   *  pspike's injected `TEST_CASE` rows read from `0(a0)` and
   *  increment, so without the store they read uninitialized memory.
   *
   *  - `resultEew`: bits per element of the result vector group (SEW
   *    for non-widening, 2×SEW for widening, 1 for mask-producing).
   *  - `resultGroup`: vector register index where the result lands.
   *    Magic word's `vector_group` field carries this.
   *  - `resultWholeRegisters`: whole-register count for the result
   *    group (1/2/4/8) — what pspike reads from `rs2[4:1]`. For
   *    widening at LMUL=4, this is 8 (dest EMUL), not 4 (base LMUL).
   */
  final case class TestBlock(
    envelope:             VTypeEnvelope,
    vectorGroup:          Int,
    vxsat:                Boolean,
    insnAsm:              String,                    // e.g., "vadd.vv v8, v16, v24"
    setupAsm:             List[String] = Nil,        // pre-instruction setup
    dataLabel:            Option[String] = None,     // memory label for load/store
    resultEew:            Int          = 32,         // result element bits
    resultGroup:          Int          = 8,          // dest vector register
    resultWholeRegisters: Int          = 1,          // for magic rs2[4:1]
    /** Post-instruction setup: emitted AFTER the instruction-under-
     *  test but BEFORE the resultdata store + magic word. Used by
     *  store-family emitters to reload from the dst label so the
     *  resultdata store captures the actual stored bytes, not the
     *  original source vector.
     */
    postInsn:             List[String] = Nil
  )

  /** Render the full `.S` file as a String. `envName` chooses the
   *  RVTEST_*UV* macro (RV64UV / RV32UV / RV64UVX). `testData` is the
   *  byte payload for the input vectors (concatenated little-endian).
   */
  def render(
    name:           String,
    envName:        String,
    blocks:         List[TestBlock],
    testData:       Vector[Byte],
    resultBytes:    Int
  ): String =
    val sb = new StringBuilder

    sb.append("# Auto-generated by rvprobe's TestSEmit. Do not edit by hand.\n")
    sb.append(s"# Instruction: $name\n")
    sb.append("\n")
    sb.append("#include \"riscv_test.h\"\n")
    sb.append("#include \"test_macros.h\"\n")
    sb.append("\n")
    sb.append(s"$envName\n")
    sb.append("\n")
    sb.append("RVTEST_CODE_BEGIN\n")
    sb.append("\n")

    if blocks.nonEmpty then
      val head = blocks.head
      sb.append(s"  ${vsetvliAsm(head.envelope)}\n")
      sb.append("  vmv.v.i v0, 0\n")
      sb.append("  vmv.v.i v8, 0\n")
      sb.append("  vmv.v.i v16, 0\n")
      sb.append("  vmv.v.i v24, 0\n")
      sb.append("\n")

    blocks.zipWithIndex.foreach { case (b, idx) =>
      sb.append(s"  # ---- block $idx (group=${b.vectorGroup}, lmul=${b.envelope.vtype.lmul}, sew=${b.envelope.vtype.sewBits}, resultEEW=${b.resultEew}, resultWR=${b.resultWholeRegisters}) ----\n")
      // Setup phase
      b.setupAsm.foreach(line => sb.append(s"  $line\n"))
      b.dataLabel.foreach(label =>
        sb.append(s"  la a1, $label\n"))
      // Re-issue vsetvli for this block's envelope
      sb.append(s"  ${vsetvliAsm(b.envelope)}\n")
      // The instruction under test
      sb.append(s"  ${b.insnAsm}\n")
      // Post-instruction setup (Codex r11 #2: store paths reload from
      // dst label here so the resultdata store captures stored bytes).
      b.postInsn.foreach(line => sb.append(s"  $line\n"))
      // pspike resultdata contract (round-9 fix): point a0 at
      // resultdata, store the result register group, then magic.
      sb.append(s"  la a0, resultdata\n")
      if b.resultEew == 1 then
        // Mask result: use vsm.v (mask store), no vsetvli swap.
        sb.append(s"  vsm.v v${b.resultGroup}, (a0)\n")
      else
        // Vector data result: swap vsetvli to result-EEW + result-EMUL
        // (round-10 fix: previously used base LMUL, losing widening footprint).
        if b.resultEew != b.envelope.vtype.sewBits ||
          MagicInstrEmit.wholeRegisterCount(b.envelope.vtype.lmul) != b.resultWholeRegisters
        then
          sb.append(s"  ${vsetvliAsmForResult(b.resultEew, b.resultWholeRegisters)}\n")
        sb.append(s"  vse${b.resultEew}.v v${b.resultGroup}, (a0)\n")
      // Restore vtype for next block / pspike injection.
      sb.append(s"  ${vsetvliAsm(b.envelope)}\n")
      // Magic word — pspike injects expected TEST_CASE rows after this.
      sb.append(s"  ${MagicInstrEmit.emitAsmWithCount(b.vectorGroup, b.resultWholeRegisters, b.vxsat)}\n")
      sb.append("\n")
    }

    sb.append("  TEST_CASE(2, x0, 0x0)\n")
    sb.append("  TEST_PASSFAIL\n")
    sb.append("\n")
    sb.append("RVTEST_CODE_END\n")
    sb.append("\n")
    sb.append("  .data\n")
    sb.append("RVTEST_DATA_BEGIN\n")
    sb.append("\n")
    sb.append("resultdata:\n")
    sb.append(s"  .zero $resultBytes\n")
    sb.append("testdata:\n")
    emitDataBytes(sb, testData)
    sb.append("\nRVTEST_DATA_END\n")
    sb.toString

  /** Emit a `vsetvli` that materializes the given envelope, using
   *  `env.vl` as the requested AVL (not VLMAX). Codex round-11 #1:
   *  using `x0` here means "request max-vl", which doesn't match the
   *  envelope's declared vl. Emits a `li t0, vl` setup line followed
   *  by the vsetvli with t0 as rs1. Returns a multi-line string
   *  (caller splits if needed).
   */
  def vsetvliAsm(env: VTypeEnvelope): String =
    val sew  = sewToken(env.vtype.sewBits)
    val lmul = lmulToken(env.vtype.lmul)
    val ta   = vtaToken(env.vtype.vta)
    val ma   = vmaToken(env.vtype.vma)
    s"li t0, ${env.vl}\n  vsetvli x5, t0, $sew,$lmul,$ta,$ma"

  /** Emit a `vsetvli x5, x0, ...` requesting VLMAX. Used only for
   *  result-store setup where we want to store all elements of the
   *  result register group, not just the original envelope's vl.
   *  Result-store vsetvli ALWAYS uses ta,ma (agnostic) because we want
   *  to dump the full register-group footprint regardless of the
   *  envelope's policy.
   */
  def vsetvliAsmVlmax(env: VTypeEnvelope): String =
    val sew  = sewToken(env.vtype.sewBits)
    val lmul = lmulToken(env.vtype.lmul)
    s"vsetvli x5, x0, $sew,$lmul,ta,ma"

  /** Emit a vsetvli for the result store, taking BOTH the result-EEW
   *  and the result whole-register count. Picks an LMUL that matches
   *  the result group footprint so the `vse<eew>.v` stores exactly the
   *  right number of registers. AVL = x0 (VLMAX) is appropriate here
   *  because we want to store the full register group footprint.
   *
   *  Mask destination (resultEew=1) routes through `vsm.v` (mask
   *  store, no vsetvli swap needed); callers should detect resultEew
   *  == 1 and skip vsetvli + use `vsm.v` instead.
   */
  def vsetvliAsmForResult(resultEew: Int, resultWholeRegisters: Int): String =
    require(resultEew != 1, "vsetvli is not used for mask result; use vsm.v instead")
    val sew  = sewToken(resultEew)
    val lmul = lmulTokenForWholeRegisters(resultWholeRegisters)
    s"vsetvli x5, x0, $sew,$lmul,ta,ma"

  /** Pick an LMUL token (m1/m2/m4/m8) that exposes exactly the given
   *  number of whole registers. Fractional LMULs collapse to m1
   *  (single register; the actual element count is determined by VL).
   */
  def lmulTokenForWholeRegisters(n: Int): String = n match
    case 1 => "m1"
    case 2 => "m2"
    case 4 => "m4"
    case 8 => "m8"
    case other =>
      throw new IllegalArgumentException(s"whole-register count must be in {1,2,4,8}, got $other")

  private def sewToken(bits: Int): String = bits match
    case 8  => "e8"
    case 16 => "e16"
    case 32 => "e32"
    case 64 => "e64"
    case n  => throw new IllegalArgumentException(s"unsupported SEW: $n")

  private def lmulToken(l: Lmul): String = l match
    case Lmul.M1  => "m1"
    case Lmul.M2  => "m2"
    case Lmul.M4  => "m4"
    case Lmul.M8  => "m8"
    case Lmul.Mf2 => "mf2"
    case Lmul.Mf4 => "mf4"
    case Lmul.Mf8 => "mf8"

  /** Emit the vta token honoring the envelope's policy. Codex r12
   *  blocking side issue #1: previous code hard-coded `ta,ma`, leaking
   *  agnostic policy into ordinary tests where upstream uses `tu,mu`.
   */
  private def vtaToken(v: Vta): String = v match
    case Vta.Undisturbed => "tu"
    case Vta.Agnostic    => "ta"

  /** Emit the vma token honoring the envelope's policy. */
  private def vmaToken(v: Vma): String = v match
    case Vma.Undisturbed => "mu"
    case Vma.Agnostic    => "ma"

  /** Choose the RVTEST_*UV* macro for a given (xlen, march-has-v)
   *  combination. Matches upstream Makefile's `EXT_V` branching.
   */
  def envMacro(xlen: Int, hasFullV: Boolean): String =
    (xlen, hasFullV) match
      case (64, true)  => "RVTEST_RV64UV"
      case (32, true)  => "RVTEST_RV32UV"
      case (64, false) => "RVTEST_RV64UVX"
      case (32, false) => "RVTEST_RV32UVX"
      case _           => throw new IllegalArgumentException(s"unsupported xlen=$xlen")

  private def emitDataBytes(sb: StringBuilder, data: Vector[Byte]): Unit =
    if data.isEmpty then sb.append("  .zero 0\n")
    else
      val perLine = 16
      data.grouped(perLine).foreach { chunk =>
        val bytes = chunk.map(b => f"0x${b & 0xff}%02x").mkString(", ")
        sb.append(s"  .byte $bytes\n")
      }
