name: CIRCT Bump
on:
  schedule:
    # Run this job everyday at 5:30 AM UTC+8
    - cron:  '30 21 * * *'
  workflow_dispatch:

jobs:
  bump-deps:
    name: "Bump CIRCT"
    if: ${{ !cancelled() }}
    runs-on: [self-hosted, linux, nixos]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump circt
        run: |
          oldFirtool="$(nix build '.#circt' --no-link --print-out-paths)/bin/firtool"
          nix flake update circt-nix
          newFirtool="$(nix build '.#circt' --no-link --print-out-paths)/bin/firtool"
          diff_bin="$(nix build '.#diffutils' --no-link --print-out-paths)/bin/diff"
          if "$diff_bin" -u <($oldFirtool --version) <($newFirtool --version); then
            # if circt version is not changed, abort this bump process
            git restore flake.lock
          fi
      - name: Bump Mill and Scala CLI dependencies
        run: nix develop -c ./bump-mill-lock.sh
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.PR_PAT }}
        run: |
          git config user.name Avimitin
          git config user.email dev@avimit.in

          currentDate=$(date +%F)
          branch="dependencies-bumping-$currentDate"
          git checkout -b "$branch"

          git add 'flake.lock'
          git add 'mtf.lock.json'
          git add 'circtlib/capi'
          git add 'mlirlib/capi'

          if ! git diff --quiet --cached --exit-code; then
            updatedFiles=$(git diff --cached --name-only)
            echo "File changed"
            git commit -m "[deps] Bump zaozi dependencies"
            git push origin "$branch" --force-with-lease
            nix run '.#gh' -- \
              pr create --title "Bump zaozi dependencies" --body "Updated: $updatedFiles"
          fi
