name: Zaozi JMH Benchmark
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled

# Cancel the current workflow when new commit pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-jmh:
    name: "Run zaozi JMH benchmark"
    runs-on: [self-hosted, linux, nixos]
    steps:
      - uses: actions/checkout@v4
      - run: nix develop -c bash -c "mill --no-daemon --ticker false zaozi.benchmark.runJmh -wi 0 -i 1 -r 1s -f 1 2>&1 | grep -E '^Iteration|^Benchmark|^ZaoziBenchmark' > $GITHUB_STEP_SUMMARY"
